// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "constants.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace biod {
class EnrollScanDone;
class EnrollScanDoneDefaultTypeInternal;
extern EnrollScanDoneDefaultTypeInternal _EnrollScanDone_default_instance_;
class FingerprintMessage;
class FingerprintMessageDefaultTypeInternal;
extern FingerprintMessageDefaultTypeInternal _FingerprintMessage_default_instance_;
}  // namespace biod
PROTOBUF_NAMESPACE_OPEN
template<> ::biod::EnrollScanDone* Arena::CreateMaybeMessage<::biod::EnrollScanDone>(Arena*);
template<> ::biod::FingerprintMessage* Arena::CreateMaybeMessage<::biod::FingerprintMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace biod {

// ===================================================================

class FingerprintMessage :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:biod.FingerprintMessage) */ {
 public:
  FingerprintMessage();
  virtual ~FingerprintMessage();

  FingerprintMessage(const FingerprintMessage& from);
  FingerprintMessage(FingerprintMessage&& from) noexcept
    : FingerprintMessage() {
    *this = ::std::move(from);
  }

  inline FingerprintMessage& operator=(const FingerprintMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline FingerprintMessage& operator=(FingerprintMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const FingerprintMessage& default_instance();

  enum MsgCase {
    kError = 1,
    kScanResult = 2,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FingerprintMessage* internal_default_instance() {
    return reinterpret_cast<const FingerprintMessage*>(
               &_FingerprintMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FingerprintMessage& a, FingerprintMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(FingerprintMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FingerprintMessage* New() const final {
    return CreateMaybeMessage<FingerprintMessage>(nullptr);
  }

  FingerprintMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FingerprintMessage>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const FingerprintMessage& from);
  void MergeFrom(const FingerprintMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FingerprintMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biod.FingerprintMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 1,
    kScanResultFieldNumber = 2,
  };
  // optional .biod.FingerprintError error = 1;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  ::biod::FingerprintError error() const;
  void set_error(::biod::FingerprintError value);
  private:
  ::biod::FingerprintError _internal_error() const;
  void _internal_set_error(::biod::FingerprintError value);
  public:

  // optional .biod.ScanResult scan_result = 2;
  bool has_scan_result() const;
  private:
  bool _internal_has_scan_result() const;
  public:
  void clear_scan_result();
  ::biod::ScanResult scan_result() const;
  void set_scan_result(::biod::ScanResult value);
  private:
  ::biod::ScanResult _internal_scan_result() const;
  void _internal_set_scan_result(::biod::ScanResult value);
  public:

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:biod.FingerprintMessage)
 private:
  class _Internal;
  void set_has_error();
  void set_has_scan_result();

  inline bool has_msg() const;
  inline void clear_has_msg();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  union MsgUnion {
    MsgUnion() {}
    int error_;
    int scan_result_;
  } msg_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class EnrollScanDone :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:biod.EnrollScanDone) */ {
 public:
  EnrollScanDone();
  virtual ~EnrollScanDone();

  EnrollScanDone(const EnrollScanDone& from);
  EnrollScanDone(EnrollScanDone&& from) noexcept
    : EnrollScanDone() {
    *this = ::std::move(from);
  }

  inline EnrollScanDone& operator=(const EnrollScanDone& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnrollScanDone& operator=(EnrollScanDone&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const EnrollScanDone& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnrollScanDone* internal_default_instance() {
    return reinterpret_cast<const EnrollScanDone*>(
               &_EnrollScanDone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EnrollScanDone& a, EnrollScanDone& b) {
    a.Swap(&b);
  }
  inline void Swap(EnrollScanDone* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EnrollScanDone* New() const final {
    return CreateMaybeMessage<EnrollScanDone>(nullptr);
  }

  EnrollScanDone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnrollScanDone>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const EnrollScanDone& from);
  void MergeFrom(const EnrollScanDone& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnrollScanDone* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biod.EnrollScanDone";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScanResultFieldNumber = 1,
    kDoneFieldNumber = 2,
    kPercentCompleteFieldNumber = 3,
  };
  // optional .biod.ScanResult scan_result = 1;
  bool has_scan_result() const;
  private:
  bool _internal_has_scan_result() const;
  public:
  void clear_scan_result();
  ::biod::ScanResult scan_result() const;
  void set_scan_result(::biod::ScanResult value);
  private:
  ::biod::ScanResult _internal_scan_result() const;
  void _internal_set_scan_result(::biod::ScanResult value);
  public:

  // optional bool done = 2;
  bool has_done() const;
  private:
  bool _internal_has_done() const;
  public:
  void clear_done();
  bool done() const;
  void set_done(bool value);
  private:
  bool _internal_done() const;
  void _internal_set_done(bool value);
  public:

  // optional int32 percent_complete = 3;
  bool has_percent_complete() const;
  private:
  bool _internal_has_percent_complete() const;
  public:
  void clear_percent_complete();
  ::PROTOBUF_NAMESPACE_ID::int32 percent_complete() const;
  void set_percent_complete(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_percent_complete() const;
  void _internal_set_percent_complete(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:biod.EnrollScanDone)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int scan_result_;
  bool done_;
  ::PROTOBUF_NAMESPACE_ID::int32 percent_complete_;
  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FingerprintMessage

// optional .biod.FingerprintError error = 1;
inline bool FingerprintMessage::_internal_has_error() const {
  return msg_case() == kError;
}
inline bool FingerprintMessage::has_error() const {
  return _internal_has_error();
}
inline void FingerprintMessage::set_has_error() {
  _oneof_case_[0] = kError;
}
inline void FingerprintMessage::clear_error() {
  if (_internal_has_error()) {
    msg_.error_ = 1;
    clear_has_msg();
  }
}
inline ::biod::FingerprintError FingerprintMessage::_internal_error() const {
  if (_internal_has_error()) {
    return static_cast< ::biod::FingerprintError >(msg_.error_);
  }
  return static_cast< ::biod::FingerprintError >(1);
}
inline ::biod::FingerprintError FingerprintMessage::error() const {
  // @@protoc_insertion_point(field_get:biod.FingerprintMessage.error)
  return _internal_error();
}
inline void FingerprintMessage::_internal_set_error(::biod::FingerprintError value) {
  assert(::biod::FingerprintError_IsValid(value));
  if (!_internal_has_error()) {
    clear_msg();
    set_has_error();
  }
  msg_.error_ = value;
}
inline void FingerprintMessage::set_error(::biod::FingerprintError value) {
  // @@protoc_insertion_point(field_set:biod.FingerprintMessage.error)
  _internal_set_error(value);
}

// optional .biod.ScanResult scan_result = 2;
inline bool FingerprintMessage::_internal_has_scan_result() const {
  return msg_case() == kScanResult;
}
inline bool FingerprintMessage::has_scan_result() const {
  return _internal_has_scan_result();
}
inline void FingerprintMessage::set_has_scan_result() {
  _oneof_case_[0] = kScanResult;
}
inline void FingerprintMessage::clear_scan_result() {
  if (_internal_has_scan_result()) {
    msg_.scan_result_ = 0;
    clear_has_msg();
  }
}
inline ::biod::ScanResult FingerprintMessage::_internal_scan_result() const {
  if (_internal_has_scan_result()) {
    return static_cast< ::biod::ScanResult >(msg_.scan_result_);
  }
  return static_cast< ::biod::ScanResult >(0);
}
inline ::biod::ScanResult FingerprintMessage::scan_result() const {
  // @@protoc_insertion_point(field_get:biod.FingerprintMessage.scan_result)
  return _internal_scan_result();
}
inline void FingerprintMessage::_internal_set_scan_result(::biod::ScanResult value) {
  assert(::biod::ScanResult_IsValid(value));
  if (!_internal_has_scan_result()) {
    clear_msg();
    set_has_scan_result();
  }
  msg_.scan_result_ = value;
}
inline void FingerprintMessage::set_scan_result(::biod::ScanResult value) {
  // @@protoc_insertion_point(field_set:biod.FingerprintMessage.scan_result)
  _internal_set_scan_result(value);
}

inline bool FingerprintMessage::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void FingerprintMessage::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline FingerprintMessage::MsgCase FingerprintMessage::msg_case() const {
  return FingerprintMessage::MsgCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// EnrollScanDone

// optional .biod.ScanResult scan_result = 1;
inline bool EnrollScanDone::_internal_has_scan_result() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool EnrollScanDone::has_scan_result() const {
  return _internal_has_scan_result();
}
inline void EnrollScanDone::clear_scan_result() {
  scan_result_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::biod::ScanResult EnrollScanDone::_internal_scan_result() const {
  return static_cast< ::biod::ScanResult >(scan_result_);
}
inline ::biod::ScanResult EnrollScanDone::scan_result() const {
  // @@protoc_insertion_point(field_get:biod.EnrollScanDone.scan_result)
  return _internal_scan_result();
}
inline void EnrollScanDone::_internal_set_scan_result(::biod::ScanResult value) {
  assert(::biod::ScanResult_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  scan_result_ = value;
}
inline void EnrollScanDone::set_scan_result(::biod::ScanResult value) {
  _internal_set_scan_result(value);
  // @@protoc_insertion_point(field_set:biod.EnrollScanDone.scan_result)
}

// optional bool done = 2;
inline bool EnrollScanDone::_internal_has_done() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool EnrollScanDone::has_done() const {
  return _internal_has_done();
}
inline void EnrollScanDone::clear_done() {
  done_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool EnrollScanDone::_internal_done() const {
  return done_;
}
inline bool EnrollScanDone::done() const {
  // @@protoc_insertion_point(field_get:biod.EnrollScanDone.done)
  return _internal_done();
}
inline void EnrollScanDone::_internal_set_done(bool value) {
  _has_bits_[0] |= 0x00000002u;
  done_ = value;
}
inline void EnrollScanDone::set_done(bool value) {
  _internal_set_done(value);
  // @@protoc_insertion_point(field_set:biod.EnrollScanDone.done)
}

// optional int32 percent_complete = 3;
inline bool EnrollScanDone::_internal_has_percent_complete() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool EnrollScanDone::has_percent_complete() const {
  return _internal_has_percent_complete();
}
inline void EnrollScanDone::clear_percent_complete() {
  percent_complete_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnrollScanDone::_internal_percent_complete() const {
  return percent_complete_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnrollScanDone::percent_complete() const {
  // @@protoc_insertion_point(field_get:biod.EnrollScanDone.percent_complete)
  return _internal_percent_complete();
}
inline void EnrollScanDone::_internal_set_percent_complete(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  percent_complete_ = value;
}
inline void EnrollScanDone::set_percent_complete(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_percent_complete(value);
  // @@protoc_insertion_point(field_set:biod.EnrollScanDone.percent_complete)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace biod

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
