// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_engine.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_update_5fengine_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_update_5fengine_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_update_5fengine_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_update_5fengine_2eproto {
  static const ::uint32_t offsets[];
};
namespace update_engine {
class ApplyUpdateConfig;
struct ApplyUpdateConfigDefaultTypeInternal;
extern ApplyUpdateConfigDefaultTypeInternal _ApplyUpdateConfig_default_instance_;
class Feature;
struct FeatureDefaultTypeInternal;
extern FeatureDefaultTypeInternal _Feature_default_instance_;
class InstallParams;
struct InstallParamsDefaultTypeInternal;
extern InstallParamsDefaultTypeInternal _InstallParams_default_instance_;
class StatusResult;
struct StatusResultDefaultTypeInternal;
extern StatusResultDefaultTypeInternal _StatusResult_default_instance_;
class UpdateFlags;
struct UpdateFlagsDefaultTypeInternal;
extern UpdateFlagsDefaultTypeInternal _UpdateFlags_default_instance_;
class UpdateParams;
struct UpdateParamsDefaultTypeInternal;
extern UpdateParamsDefaultTypeInternal _UpdateParams_default_instance_;
}  // namespace update_engine
PROTOBUF_NAMESPACE_OPEN
template <>
::update_engine::ApplyUpdateConfig* Arena::CreateMaybeMessage<::update_engine::ApplyUpdateConfig>(Arena*);
template <>
::update_engine::Feature* Arena::CreateMaybeMessage<::update_engine::Feature>(Arena*);
template <>
::update_engine::InstallParams* Arena::CreateMaybeMessage<::update_engine::InstallParams>(Arena*);
template <>
::update_engine::StatusResult* Arena::CreateMaybeMessage<::update_engine::StatusResult>(Arena*);
template <>
::update_engine::UpdateFlags* Arena::CreateMaybeMessage<::update_engine::UpdateFlags>(Arena*);
template <>
::update_engine::UpdateParams* Arena::CreateMaybeMessage<::update_engine::UpdateParams>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace update_engine {
enum Operation : int {
  IDLE = 0,
  CHECKING_FOR_UPDATE = 1,
  UPDATE_AVAILABLE = 2,
  DOWNLOADING = 3,
  VERIFYING = 4,
  FINALIZING = 5,
  UPDATED_NEED_REBOOT = 6,
  REPORTING_ERROR_EVENT = 7,
  ATTEMPTING_ROLLBACK = 8,
  DISABLED = 9,
  NEED_PERMISSION_TO_UPDATE = 10,
  CLEANUP_PREVIOUS_UPDATE = 11,
  UPDATED_BUT_DEFERRED = 12,
  ERROR = -1,
  Operation_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  Operation_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool Operation_IsValid(int value);
constexpr Operation Operation_MIN = static_cast<Operation>(-1);
constexpr Operation Operation_MAX = static_cast<Operation>(12);
constexpr int Operation_ARRAYSIZE = 12 + 1;
const std::string& Operation_Name(Operation value);
template <typename T>
const std::string& Operation_Name(T value) {
  static_assert(std::is_same<T, Operation>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Operation_Name().");
  return Operation_Name(static_cast<Operation>(value));
}
const std::string& Operation_Name(Operation value);
bool Operation_Parse(absl::string_view name, Operation* value);
enum UpdateUrgency : int {
  REGULAR = 0,
  CRITICAL = 1,
  UpdateUrgency_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  UpdateUrgency_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool UpdateUrgency_IsValid(int value);
constexpr UpdateUrgency UpdateUrgency_MIN = static_cast<UpdateUrgency>(0);
constexpr UpdateUrgency UpdateUrgency_MAX = static_cast<UpdateUrgency>(1);
constexpr int UpdateUrgency_ARRAYSIZE = 1 + 1;
const std::string& UpdateUrgency_Name(UpdateUrgency value);
template <typename T>
const std::string& UpdateUrgency_Name(T value) {
  static_assert(std::is_same<T, UpdateUrgency>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to UpdateUrgency_Name().");
  return UpdateUrgency_Name(static_cast<UpdateUrgency>(value));
}
const std::string& UpdateUrgency_Name(UpdateUrgency value);
bool UpdateUrgency_Parse(absl::string_view name, UpdateUrgency* value);
enum UpdateDoneAction : int {
  REBOOT = 0,
  SHUTDOWN = 1,
  UpdateDoneAction_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  UpdateDoneAction_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool UpdateDoneAction_IsValid(int value);
constexpr UpdateDoneAction UpdateDoneAction_MIN = static_cast<UpdateDoneAction>(0);
constexpr UpdateDoneAction UpdateDoneAction_MAX = static_cast<UpdateDoneAction>(1);
constexpr int UpdateDoneAction_ARRAYSIZE = 1 + 1;
const std::string& UpdateDoneAction_Name(UpdateDoneAction value);
template <typename T>
const std::string& UpdateDoneAction_Name(T value) {
  static_assert(std::is_same<T, UpdateDoneAction>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to UpdateDoneAction_Name().");
  return UpdateDoneAction_Name(static_cast<UpdateDoneAction>(value));
}
const std::string& UpdateDoneAction_Name(UpdateDoneAction value);
bool UpdateDoneAction_Parse(absl::string_view name, UpdateDoneAction* value);

// ===================================================================


// -------------------------------------------------------------------

class ApplyUpdateConfig final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.ApplyUpdateConfig) */ {
 public:
  inline ApplyUpdateConfig() : ApplyUpdateConfig(nullptr) {}
  ~ApplyUpdateConfig() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ApplyUpdateConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ApplyUpdateConfig(const ApplyUpdateConfig& from);
  ApplyUpdateConfig(ApplyUpdateConfig&& from) noexcept
    : ApplyUpdateConfig() {
    *this = ::std::move(from);
  }

  inline ApplyUpdateConfig& operator=(const ApplyUpdateConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApplyUpdateConfig& operator=(ApplyUpdateConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const ApplyUpdateConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApplyUpdateConfig* internal_default_instance() {
    return reinterpret_cast<const ApplyUpdateConfig*>(
               &_ApplyUpdateConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ApplyUpdateConfig& a, ApplyUpdateConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ApplyUpdateConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApplyUpdateConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApplyUpdateConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ApplyUpdateConfig>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ApplyUpdateConfig& from);
  void MergeFrom(const ApplyUpdateConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ApplyUpdateConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.ApplyUpdateConfig";
  }
  protected:
  explicit ApplyUpdateConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDoneActionFieldNumber = 1,
  };
  // .update_engine.UpdateDoneAction done_action = 1;
  void clear_done_action() ;
  ::update_engine::UpdateDoneAction done_action() const;
  void set_done_action(::update_engine::UpdateDoneAction value);

  private:
  ::update_engine::UpdateDoneAction _internal_done_action() const;
  void _internal_set_done_action(::update_engine::UpdateDoneAction value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.ApplyUpdateConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int done_action_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};// -------------------------------------------------------------------

class Feature final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.Feature) */ {
 public:
  inline Feature() : Feature(nullptr) {}
  ~Feature() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Feature(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Feature(const Feature& from);
  Feature(Feature&& from) noexcept
    : Feature() {
    *this = ::std::move(from);
  }

  inline Feature& operator=(const Feature& from) {
    CopyFrom(from);
    return *this;
  }
  inline Feature& operator=(Feature&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Feature& default_instance() {
    return *internal_default_instance();
  }
  static inline const Feature* internal_default_instance() {
    return reinterpret_cast<const Feature*>(
               &_Feature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Feature& a, Feature& b) {
    a.Swap(&b);
  }
  inline void Swap(Feature* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Feature* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Feature* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Feature>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Feature& from);
  void MergeFrom(const Feature& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Feature* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.Feature";
  }
  protected:
  explicit Feature(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kEnabledFieldNumber = 2,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* ptr);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // bool enabled = 2;
  void clear_enabled() ;
  bool enabled() const;
  void set_enabled(bool value);

  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.Feature)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    bool enabled_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};// -------------------------------------------------------------------

class StatusResult final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.StatusResult) */ {
 public:
  inline StatusResult() : StatusResult(nullptr) {}
  ~StatusResult() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR StatusResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StatusResult(const StatusResult& from);
  StatusResult(StatusResult&& from) noexcept
    : StatusResult() {
    *this = ::std::move(from);
  }

  inline StatusResult& operator=(const StatusResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusResult& operator=(StatusResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const StatusResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatusResult* internal_default_instance() {
    return reinterpret_cast<const StatusResult*>(
               &_StatusResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StatusResult& a, StatusResult& b) {
    a.Swap(&b);
  }
  inline void Swap(StatusResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StatusResult>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const StatusResult& from);
  void MergeFrom(const StatusResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StatusResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.StatusResult";
  }
  protected:
  explicit StatusResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFeaturesFieldNumber = 13,
    kNewVersionFieldNumber = 4,
    kLastCheckedTimeFieldNumber = 1,
    kProgressFieldNumber = 2,
    kNewSizeFieldNumber = 5,
    kCurrentOperationFieldNumber = 3,
    kIsEnterpriseRollbackFieldNumber = 6,
    kIsInstallFieldNumber = 7,
    kWillPowerwashAfterRebootFieldNumber = 9,
    kIsInteractiveFieldNumber = 14,
    kEolDateFieldNumber = 8,
    kLastAttemptErrorFieldNumber = 10,
    kUpdateUrgencyFieldNumber = 12,
    kWillDeferUpdateFieldNumber = 15,
  };
  // repeated .update_engine.Feature features = 13;
  int features_size() const;
  private:
  int _internal_features_size() const;

  public:
  void clear_features() ;
  ::update_engine::Feature* mutable_features(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::update_engine::Feature >*
      mutable_features();
  private:
  const ::update_engine::Feature& _internal_features(int index) const;
  ::update_engine::Feature* _internal_add_features();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::update_engine::Feature>& _internal_features() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::update_engine::Feature>* _internal_mutable_features();
  public:
  const ::update_engine::Feature& features(int index) const;
  ::update_engine::Feature* add_features();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::update_engine::Feature >&
      features() const;
  // string new_version = 4;
  void clear_new_version() ;
  const std::string& new_version() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_new_version(Arg_&& arg, Args_... args);
  std::string* mutable_new_version();
  PROTOBUF_NODISCARD std::string* release_new_version();
  void set_allocated_new_version(std::string* ptr);

  private:
  const std::string& _internal_new_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_new_version(
      const std::string& value);
  std::string* _internal_mutable_new_version();

  public:
  // int64 last_checked_time = 1;
  void clear_last_checked_time() ;
  ::int64_t last_checked_time() const;
  void set_last_checked_time(::int64_t value);

  private:
  ::int64_t _internal_last_checked_time() const;
  void _internal_set_last_checked_time(::int64_t value);

  public:
  // double progress = 2;
  void clear_progress() ;
  double progress() const;
  void set_progress(double value);

  private:
  double _internal_progress() const;
  void _internal_set_progress(double value);

  public:
  // int64 new_size = 5;
  void clear_new_size() ;
  ::int64_t new_size() const;
  void set_new_size(::int64_t value);

  private:
  ::int64_t _internal_new_size() const;
  void _internal_set_new_size(::int64_t value);

  public:
  // .update_engine.Operation current_operation = 3;
  void clear_current_operation() ;
  ::update_engine::Operation current_operation() const;
  void set_current_operation(::update_engine::Operation value);

  private:
  ::update_engine::Operation _internal_current_operation() const;
  void _internal_set_current_operation(::update_engine::Operation value);

  public:
  // bool is_enterprise_rollback = 6;
  void clear_is_enterprise_rollback() ;
  bool is_enterprise_rollback() const;
  void set_is_enterprise_rollback(bool value);

  private:
  bool _internal_is_enterprise_rollback() const;
  void _internal_set_is_enterprise_rollback(bool value);

  public:
  // bool is_install = 7;
  void clear_is_install() ;
  bool is_install() const;
  void set_is_install(bool value);

  private:
  bool _internal_is_install() const;
  void _internal_set_is_install(bool value);

  public:
  // bool will_powerwash_after_reboot = 9;
  void clear_will_powerwash_after_reboot() ;
  bool will_powerwash_after_reboot() const;
  void set_will_powerwash_after_reboot(bool value);

  private:
  bool _internal_will_powerwash_after_reboot() const;
  void _internal_set_will_powerwash_after_reboot(bool value);

  public:
  // bool is_interactive = 14;
  void clear_is_interactive() ;
  bool is_interactive() const;
  void set_is_interactive(bool value);

  private:
  bool _internal_is_interactive() const;
  void _internal_set_is_interactive(bool value);

  public:
  // int64 eol_date = 8;
  void clear_eol_date() ;
  ::int64_t eol_date() const;
  void set_eol_date(::int64_t value);

  private:
  ::int64_t _internal_eol_date() const;
  void _internal_set_eol_date(::int64_t value);

  public:
  // int32 last_attempt_error = 10;
  void clear_last_attempt_error() ;
  ::int32_t last_attempt_error() const;
  void set_last_attempt_error(::int32_t value);

  private:
  ::int32_t _internal_last_attempt_error() const;
  void _internal_set_last_attempt_error(::int32_t value);

  public:
  // .update_engine.UpdateUrgency update_urgency = 12;
  void clear_update_urgency() ;
  ::update_engine::UpdateUrgency update_urgency() const;
  void set_update_urgency(::update_engine::UpdateUrgency value);

  private:
  ::update_engine::UpdateUrgency _internal_update_urgency() const;
  void _internal_set_update_urgency(::update_engine::UpdateUrgency value);

  public:
  // bool will_defer_update = 15;
  void clear_will_defer_update() ;
  bool will_defer_update() const;
  void set_will_defer_update(bool value);

  private:
  bool _internal_will_defer_update() const;
  void _internal_set_will_defer_update(bool value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.StatusResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::update_engine::Feature > features_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr new_version_;
    ::int64_t last_checked_time_;
    double progress_;
    ::int64_t new_size_;
    int current_operation_;
    bool is_enterprise_rollback_;
    bool is_install_;
    bool will_powerwash_after_reboot_;
    bool is_interactive_;
    ::int64_t eol_date_;
    ::int32_t last_attempt_error_;
    int update_urgency_;
    bool will_defer_update_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};// -------------------------------------------------------------------

class UpdateFlags final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.UpdateFlags) */ {
 public:
  inline UpdateFlags() : UpdateFlags(nullptr) {}
  ~UpdateFlags() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateFlags(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateFlags(const UpdateFlags& from);
  UpdateFlags(UpdateFlags&& from) noexcept
    : UpdateFlags() {
    *this = ::std::move(from);
  }

  inline UpdateFlags& operator=(const UpdateFlags& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateFlags& operator=(UpdateFlags&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const UpdateFlags& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateFlags* internal_default_instance() {
    return reinterpret_cast<const UpdateFlags*>(
               &_UpdateFlags_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UpdateFlags& a, UpdateFlags& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateFlags* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateFlags* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateFlags* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateFlags>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const UpdateFlags& from);
  void MergeFrom(const UpdateFlags& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateFlags* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.UpdateFlags";
  }
  protected:
  explicit UpdateFlags(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNonInteractiveFieldNumber = 1,
  };
  // bool non_interactive = 1;
  void clear_non_interactive() ;
  bool non_interactive() const;
  void set_non_interactive(bool value);

  private:
  bool _internal_non_interactive() const;
  void _internal_set_non_interactive(bool value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.UpdateFlags)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool non_interactive_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};// -------------------------------------------------------------------

class UpdateParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.UpdateParams) */ {
 public:
  inline UpdateParams() : UpdateParams(nullptr) {}
  ~UpdateParams() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateParams(const UpdateParams& from);
  UpdateParams(UpdateParams&& from) noexcept
    : UpdateParams() {
    *this = ::std::move(from);
  }

  inline UpdateParams& operator=(const UpdateParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateParams& operator=(UpdateParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const UpdateParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateParams* internal_default_instance() {
    return reinterpret_cast<const UpdateParams*>(
               &_UpdateParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(UpdateParams& a, UpdateParams& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateParams* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const UpdateParams& from);
  void MergeFrom(const UpdateParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.UpdateParams";
  }
  protected:
  explicit UpdateParams(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppVersionFieldNumber = 1,
    kOmahaUrlFieldNumber = 2,
    kUpdateFlagsFieldNumber = 3,
    kSkipApplyingFieldNumber = 4,
    kForceFwUpdateFieldNumber = 5,
  };
  // string app_version = 1;
  void clear_app_version() ;
  const std::string& app_version() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_app_version(Arg_&& arg, Args_... args);
  std::string* mutable_app_version();
  PROTOBUF_NODISCARD std::string* release_app_version();
  void set_allocated_app_version(std::string* ptr);

  private:
  const std::string& _internal_app_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_version(
      const std::string& value);
  std::string* _internal_mutable_app_version();

  public:
  // string omaha_url = 2;
  void clear_omaha_url() ;
  const std::string& omaha_url() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_omaha_url(Arg_&& arg, Args_... args);
  std::string* mutable_omaha_url();
  PROTOBUF_NODISCARD std::string* release_omaha_url();
  void set_allocated_omaha_url(std::string* ptr);

  private:
  const std::string& _internal_omaha_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_omaha_url(
      const std::string& value);
  std::string* _internal_mutable_omaha_url();

  public:
  // .update_engine.UpdateFlags update_flags = 3;
  bool has_update_flags() const;
  void clear_update_flags() ;
  const ::update_engine::UpdateFlags& update_flags() const;
  PROTOBUF_NODISCARD ::update_engine::UpdateFlags* release_update_flags();
  ::update_engine::UpdateFlags* mutable_update_flags();
  void set_allocated_update_flags(::update_engine::UpdateFlags* update_flags);
  private:
  const ::update_engine::UpdateFlags& _internal_update_flags() const;
  ::update_engine::UpdateFlags* _internal_mutable_update_flags();
  public:
  void unsafe_arena_set_allocated_update_flags(
      ::update_engine::UpdateFlags* update_flags);
  ::update_engine::UpdateFlags* unsafe_arena_release_update_flags();
  // bool skip_applying = 4;
  void clear_skip_applying() ;
  bool skip_applying() const;
  void set_skip_applying(bool value);

  private:
  bool _internal_skip_applying() const;
  void _internal_set_skip_applying(bool value);

  public:
  // bool force_fw_update = 5;
  void clear_force_fw_update() ;
  bool force_fw_update() const;
  void set_force_fw_update(bool value);

  private:
  bool _internal_force_fw_update() const;
  void _internal_set_force_fw_update(bool value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.UpdateParams)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr omaha_url_;
    ::update_engine::UpdateFlags* update_flags_;
    bool skip_applying_;
    bool force_fw_update_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};// -------------------------------------------------------------------

class InstallParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:update_engine.InstallParams) */ {
 public:
  inline InstallParams() : InstallParams(nullptr) {}
  ~InstallParams() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR InstallParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstallParams(const InstallParams& from);
  InstallParams(InstallParams&& from) noexcept
    : InstallParams() {
    *this = ::std::move(from);
  }

  inline InstallParams& operator=(const InstallParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallParams& operator=(InstallParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const InstallParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstallParams* internal_default_instance() {
    return reinterpret_cast<const InstallParams*>(
               &_InstallParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InstallParams& a, InstallParams& b) {
    a.Swap(&b);
  }
  inline void Swap(InstallParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallParams* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstallParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const InstallParams& from);
  void MergeFrom(const InstallParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(InstallParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "update_engine.InstallParams";
  }
  protected:
  explicit InstallParams(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kOmahaUrlFieldNumber = 2,
    kScaledFieldNumber = 3,
  };
  // string id = 1;
  void clear_id() ;
  const std::string& id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* ptr);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // string omaha_url = 2;
  void clear_omaha_url() ;
  const std::string& omaha_url() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_omaha_url(Arg_&& arg, Args_... args);
  std::string* mutable_omaha_url();
  PROTOBUF_NODISCARD std::string* release_omaha_url();
  void set_allocated_omaha_url(std::string* ptr);

  private:
  const std::string& _internal_omaha_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_omaha_url(
      const std::string& value);
  std::string* _internal_mutable_omaha_url();

  public:
  // bool scaled = 3;
  void clear_scaled() ;
  bool scaled() const;
  void set_scaled(bool value);

  private:
  bool _internal_scaled() const;
  void _internal_set_scaled(bool value);

  public:
  // @@protoc_insertion_point(class_scope:update_engine.InstallParams)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr omaha_url_;
    bool scaled_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_5fengine_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ApplyUpdateConfig

// .update_engine.UpdateDoneAction done_action = 1;
inline void ApplyUpdateConfig::clear_done_action() {
  _impl_.done_action_ = 0;
}
inline ::update_engine::UpdateDoneAction ApplyUpdateConfig::done_action() const {
  // @@protoc_insertion_point(field_get:update_engine.ApplyUpdateConfig.done_action)
  return _internal_done_action();
}
inline void ApplyUpdateConfig::set_done_action(::update_engine::UpdateDoneAction value) {
   _internal_set_done_action(value);
  // @@protoc_insertion_point(field_set:update_engine.ApplyUpdateConfig.done_action)
}
inline ::update_engine::UpdateDoneAction ApplyUpdateConfig::_internal_done_action() const {
  return static_cast<::update_engine::UpdateDoneAction>(_impl_.done_action_);
}
inline void ApplyUpdateConfig::_internal_set_done_action(::update_engine::UpdateDoneAction value) {
  ;
  _impl_.done_action_ = value;
}

// -------------------------------------------------------------------

// Feature

// string name = 1;
inline void Feature::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Feature::name() const {
  // @@protoc_insertion_point(field_get:update_engine.Feature.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Feature::set_name(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.Feature.name)
}
inline std::string* Feature::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:update_engine.Feature.name)
  return _s;
}
inline const std::string& Feature::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Feature::_internal_set_name(const std::string& value) {
  ;


  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Feature::_internal_mutable_name() {
  ;
  return _impl_.name_.Mutable( GetArenaForAllocation());
}
inline std::string* Feature::release_name() {
  // @@protoc_insertion_point(field_release:update_engine.Feature.name)
  return _impl_.name_.Release();
}
inline void Feature::set_allocated_name(std::string* value) {
  _impl_.name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.Feature.name)
}

// bool enabled = 2;
inline void Feature::clear_enabled() {
  _impl_.enabled_ = false;
}
inline bool Feature::enabled() const {
  // @@protoc_insertion_point(field_get:update_engine.Feature.enabled)
  return _internal_enabled();
}
inline void Feature::set_enabled(bool value) {
  _internal_set_enabled(value);
  // @@protoc_insertion_point(field_set:update_engine.Feature.enabled)
}
inline bool Feature::_internal_enabled() const {
  return _impl_.enabled_;
}
inline void Feature::_internal_set_enabled(bool value) {
  ;
  _impl_.enabled_ = value;
}

// -------------------------------------------------------------------

// StatusResult

// int64 last_checked_time = 1;
inline void StatusResult::clear_last_checked_time() {
  _impl_.last_checked_time_ = ::int64_t{0};
}
inline ::int64_t StatusResult::last_checked_time() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.last_checked_time)
  return _internal_last_checked_time();
}
inline void StatusResult::set_last_checked_time(::int64_t value) {
  _internal_set_last_checked_time(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.last_checked_time)
}
inline ::int64_t StatusResult::_internal_last_checked_time() const {
  return _impl_.last_checked_time_;
}
inline void StatusResult::_internal_set_last_checked_time(::int64_t value) {
  ;
  _impl_.last_checked_time_ = value;
}

// double progress = 2;
inline void StatusResult::clear_progress() {
  _impl_.progress_ = 0;
}
inline double StatusResult::progress() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.progress)
  return _internal_progress();
}
inline void StatusResult::set_progress(double value) {
  _internal_set_progress(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.progress)
}
inline double StatusResult::_internal_progress() const {
  return _impl_.progress_;
}
inline void StatusResult::_internal_set_progress(double value) {
  ;
  _impl_.progress_ = value;
}

// .update_engine.Operation current_operation = 3;
inline void StatusResult::clear_current_operation() {
  _impl_.current_operation_ = 0;
}
inline ::update_engine::Operation StatusResult::current_operation() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.current_operation)
  return _internal_current_operation();
}
inline void StatusResult::set_current_operation(::update_engine::Operation value) {
   _internal_set_current_operation(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.current_operation)
}
inline ::update_engine::Operation StatusResult::_internal_current_operation() const {
  return static_cast<::update_engine::Operation>(_impl_.current_operation_);
}
inline void StatusResult::_internal_set_current_operation(::update_engine::Operation value) {
  ;
  _impl_.current_operation_ = value;
}

// string new_version = 4;
inline void StatusResult::clear_new_version() {
  _impl_.new_version_.ClearToEmpty();
}
inline const std::string& StatusResult::new_version() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.new_version)
  return _internal_new_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StatusResult::set_new_version(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.new_version_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.new_version)
}
inline std::string* StatusResult::mutable_new_version() {
  std::string* _s = _internal_mutable_new_version();
  // @@protoc_insertion_point(field_mutable:update_engine.StatusResult.new_version)
  return _s;
}
inline const std::string& StatusResult::_internal_new_version() const {
  return _impl_.new_version_.Get();
}
inline void StatusResult::_internal_set_new_version(const std::string& value) {
  ;


  _impl_.new_version_.Set(value, GetArenaForAllocation());
}
inline std::string* StatusResult::_internal_mutable_new_version() {
  ;
  return _impl_.new_version_.Mutable( GetArenaForAllocation());
}
inline std::string* StatusResult::release_new_version() {
  // @@protoc_insertion_point(field_release:update_engine.StatusResult.new_version)
  return _impl_.new_version_.Release();
}
inline void StatusResult::set_allocated_new_version(std::string* value) {
  _impl_.new_version_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.new_version_.IsDefault()) {
          _impl_.new_version_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.StatusResult.new_version)
}

// int64 new_size = 5;
inline void StatusResult::clear_new_size() {
  _impl_.new_size_ = ::int64_t{0};
}
inline ::int64_t StatusResult::new_size() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.new_size)
  return _internal_new_size();
}
inline void StatusResult::set_new_size(::int64_t value) {
  _internal_set_new_size(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.new_size)
}
inline ::int64_t StatusResult::_internal_new_size() const {
  return _impl_.new_size_;
}
inline void StatusResult::_internal_set_new_size(::int64_t value) {
  ;
  _impl_.new_size_ = value;
}

// bool is_enterprise_rollback = 6;
inline void StatusResult::clear_is_enterprise_rollback() {
  _impl_.is_enterprise_rollback_ = false;
}
inline bool StatusResult::is_enterprise_rollback() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.is_enterprise_rollback)
  return _internal_is_enterprise_rollback();
}
inline void StatusResult::set_is_enterprise_rollback(bool value) {
  _internal_set_is_enterprise_rollback(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.is_enterprise_rollback)
}
inline bool StatusResult::_internal_is_enterprise_rollback() const {
  return _impl_.is_enterprise_rollback_;
}
inline void StatusResult::_internal_set_is_enterprise_rollback(bool value) {
  ;
  _impl_.is_enterprise_rollback_ = value;
}

// bool is_install = 7;
inline void StatusResult::clear_is_install() {
  _impl_.is_install_ = false;
}
inline bool StatusResult::is_install() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.is_install)
  return _internal_is_install();
}
inline void StatusResult::set_is_install(bool value) {
  _internal_set_is_install(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.is_install)
}
inline bool StatusResult::_internal_is_install() const {
  return _impl_.is_install_;
}
inline void StatusResult::_internal_set_is_install(bool value) {
  ;
  _impl_.is_install_ = value;
}

// int64 eol_date = 8;
inline void StatusResult::clear_eol_date() {
  _impl_.eol_date_ = ::int64_t{0};
}
inline ::int64_t StatusResult::eol_date() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.eol_date)
  return _internal_eol_date();
}
inline void StatusResult::set_eol_date(::int64_t value) {
  _internal_set_eol_date(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.eol_date)
}
inline ::int64_t StatusResult::_internal_eol_date() const {
  return _impl_.eol_date_;
}
inline void StatusResult::_internal_set_eol_date(::int64_t value) {
  ;
  _impl_.eol_date_ = value;
}

// bool will_powerwash_after_reboot = 9;
inline void StatusResult::clear_will_powerwash_after_reboot() {
  _impl_.will_powerwash_after_reboot_ = false;
}
inline bool StatusResult::will_powerwash_after_reboot() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.will_powerwash_after_reboot)
  return _internal_will_powerwash_after_reboot();
}
inline void StatusResult::set_will_powerwash_after_reboot(bool value) {
  _internal_set_will_powerwash_after_reboot(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.will_powerwash_after_reboot)
}
inline bool StatusResult::_internal_will_powerwash_after_reboot() const {
  return _impl_.will_powerwash_after_reboot_;
}
inline void StatusResult::_internal_set_will_powerwash_after_reboot(bool value) {
  ;
  _impl_.will_powerwash_after_reboot_ = value;
}

// int32 last_attempt_error = 10;
inline void StatusResult::clear_last_attempt_error() {
  _impl_.last_attempt_error_ = 0;
}
inline ::int32_t StatusResult::last_attempt_error() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.last_attempt_error)
  return _internal_last_attempt_error();
}
inline void StatusResult::set_last_attempt_error(::int32_t value) {
  _internal_set_last_attempt_error(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.last_attempt_error)
}
inline ::int32_t StatusResult::_internal_last_attempt_error() const {
  return _impl_.last_attempt_error_;
}
inline void StatusResult::_internal_set_last_attempt_error(::int32_t value) {
  ;
  _impl_.last_attempt_error_ = value;
}

// .update_engine.UpdateUrgency update_urgency = 12;
inline void StatusResult::clear_update_urgency() {
  _impl_.update_urgency_ = 0;
}
inline ::update_engine::UpdateUrgency StatusResult::update_urgency() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.update_urgency)
  return _internal_update_urgency();
}
inline void StatusResult::set_update_urgency(::update_engine::UpdateUrgency value) {
   _internal_set_update_urgency(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.update_urgency)
}
inline ::update_engine::UpdateUrgency StatusResult::_internal_update_urgency() const {
  return static_cast<::update_engine::UpdateUrgency>(_impl_.update_urgency_);
}
inline void StatusResult::_internal_set_update_urgency(::update_engine::UpdateUrgency value) {
  ;
  _impl_.update_urgency_ = value;
}

// repeated .update_engine.Feature features = 13;
inline int StatusResult::_internal_features_size() const {
  return _impl_.features_.size();
}
inline int StatusResult::features_size() const {
  return _internal_features_size();
}
inline void StatusResult::clear_features() {
  _internal_mutable_features()->Clear();
}
inline ::update_engine::Feature* StatusResult::mutable_features(int index) {
  // @@protoc_insertion_point(field_mutable:update_engine.StatusResult.features)
  return _internal_mutable_features()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::update_engine::Feature >*
StatusResult::mutable_features() {
  // @@protoc_insertion_point(field_mutable_list:update_engine.StatusResult.features)
  return _internal_mutable_features();
}
inline const ::update_engine::Feature& StatusResult::_internal_features(int index) const {
  return _internal_features().Get(index);
}
inline const ::update_engine::Feature& StatusResult::features(int index) const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.features)
  return _internal_features(index);
}
inline ::update_engine::Feature* StatusResult::_internal_add_features() {
  return _internal_mutable_features()->Add();
}
inline ::update_engine::Feature* StatusResult::add_features() {
  ::update_engine::Feature* _add = _internal_add_features();
  // @@protoc_insertion_point(field_add:update_engine.StatusResult.features)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::update_engine::Feature >&
StatusResult::features() const {
  // @@protoc_insertion_point(field_list:update_engine.StatusResult.features)
  return _internal_features();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::update_engine::Feature>&
StatusResult::_internal_features() const {
  return _impl_.features_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::update_engine::Feature>*
StatusResult::_internal_mutable_features() {
  return &_impl_.features_;
}

// bool is_interactive = 14;
inline void StatusResult::clear_is_interactive() {
  _impl_.is_interactive_ = false;
}
inline bool StatusResult::is_interactive() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.is_interactive)
  return _internal_is_interactive();
}
inline void StatusResult::set_is_interactive(bool value) {
  _internal_set_is_interactive(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.is_interactive)
}
inline bool StatusResult::_internal_is_interactive() const {
  return _impl_.is_interactive_;
}
inline void StatusResult::_internal_set_is_interactive(bool value) {
  ;
  _impl_.is_interactive_ = value;
}

// bool will_defer_update = 15;
inline void StatusResult::clear_will_defer_update() {
  _impl_.will_defer_update_ = false;
}
inline bool StatusResult::will_defer_update() const {
  // @@protoc_insertion_point(field_get:update_engine.StatusResult.will_defer_update)
  return _internal_will_defer_update();
}
inline void StatusResult::set_will_defer_update(bool value) {
  _internal_set_will_defer_update(value);
  // @@protoc_insertion_point(field_set:update_engine.StatusResult.will_defer_update)
}
inline bool StatusResult::_internal_will_defer_update() const {
  return _impl_.will_defer_update_;
}
inline void StatusResult::_internal_set_will_defer_update(bool value) {
  ;
  _impl_.will_defer_update_ = value;
}

// -------------------------------------------------------------------

// UpdateFlags

// bool non_interactive = 1;
inline void UpdateFlags::clear_non_interactive() {
  _impl_.non_interactive_ = false;
}
inline bool UpdateFlags::non_interactive() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateFlags.non_interactive)
  return _internal_non_interactive();
}
inline void UpdateFlags::set_non_interactive(bool value) {
  _internal_set_non_interactive(value);
  // @@protoc_insertion_point(field_set:update_engine.UpdateFlags.non_interactive)
}
inline bool UpdateFlags::_internal_non_interactive() const {
  return _impl_.non_interactive_;
}
inline void UpdateFlags::_internal_set_non_interactive(bool value) {
  ;
  _impl_.non_interactive_ = value;
}

// -------------------------------------------------------------------

// UpdateParams

// string app_version = 1;
inline void UpdateParams::clear_app_version() {
  _impl_.app_version_.ClearToEmpty();
}
inline const std::string& UpdateParams::app_version() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateParams.app_version)
  return _internal_app_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateParams::set_app_version(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.app_version_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.UpdateParams.app_version)
}
inline std::string* UpdateParams::mutable_app_version() {
  std::string* _s = _internal_mutable_app_version();
  // @@protoc_insertion_point(field_mutable:update_engine.UpdateParams.app_version)
  return _s;
}
inline const std::string& UpdateParams::_internal_app_version() const {
  return _impl_.app_version_.Get();
}
inline void UpdateParams::_internal_set_app_version(const std::string& value) {
  ;


  _impl_.app_version_.Set(value, GetArenaForAllocation());
}
inline std::string* UpdateParams::_internal_mutable_app_version() {
  ;
  return _impl_.app_version_.Mutable( GetArenaForAllocation());
}
inline std::string* UpdateParams::release_app_version() {
  // @@protoc_insertion_point(field_release:update_engine.UpdateParams.app_version)
  return _impl_.app_version_.Release();
}
inline void UpdateParams::set_allocated_app_version(std::string* value) {
  _impl_.app_version_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.app_version_.IsDefault()) {
          _impl_.app_version_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.UpdateParams.app_version)
}

// string omaha_url = 2;
inline void UpdateParams::clear_omaha_url() {
  _impl_.omaha_url_.ClearToEmpty();
}
inline const std::string& UpdateParams::omaha_url() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateParams.omaha_url)
  return _internal_omaha_url();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateParams::set_omaha_url(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.omaha_url_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.UpdateParams.omaha_url)
}
inline std::string* UpdateParams::mutable_omaha_url() {
  std::string* _s = _internal_mutable_omaha_url();
  // @@protoc_insertion_point(field_mutable:update_engine.UpdateParams.omaha_url)
  return _s;
}
inline const std::string& UpdateParams::_internal_omaha_url() const {
  return _impl_.omaha_url_.Get();
}
inline void UpdateParams::_internal_set_omaha_url(const std::string& value) {
  ;


  _impl_.omaha_url_.Set(value, GetArenaForAllocation());
}
inline std::string* UpdateParams::_internal_mutable_omaha_url() {
  ;
  return _impl_.omaha_url_.Mutable( GetArenaForAllocation());
}
inline std::string* UpdateParams::release_omaha_url() {
  // @@protoc_insertion_point(field_release:update_engine.UpdateParams.omaha_url)
  return _impl_.omaha_url_.Release();
}
inline void UpdateParams::set_allocated_omaha_url(std::string* value) {
  _impl_.omaha_url_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.omaha_url_.IsDefault()) {
          _impl_.omaha_url_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.UpdateParams.omaha_url)
}

// .update_engine.UpdateFlags update_flags = 3;
inline bool UpdateParams::has_update_flags() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.update_flags_ != nullptr);
  return value;
}
inline void UpdateParams::clear_update_flags() {
  if (_impl_.update_flags_ != nullptr) _impl_.update_flags_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::update_engine::UpdateFlags& UpdateParams::_internal_update_flags() const {
  const ::update_engine::UpdateFlags* p = _impl_.update_flags_;
  return p != nullptr ? *p : reinterpret_cast<const ::update_engine::UpdateFlags&>(
      ::update_engine::_UpdateFlags_default_instance_);
}
inline const ::update_engine::UpdateFlags& UpdateParams::update_flags() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateParams.update_flags)
  return _internal_update_flags();
}
inline void UpdateParams::unsafe_arena_set_allocated_update_flags(
    ::update_engine::UpdateFlags* update_flags) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.update_flags_);
  }
  _impl_.update_flags_ = update_flags;
  if (update_flags) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:update_engine.UpdateParams.update_flags)
}
inline ::update_engine::UpdateFlags* UpdateParams::release_update_flags() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::update_engine::UpdateFlags* temp = _impl_.update_flags_;
  _impl_.update_flags_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::update_engine::UpdateFlags* UpdateParams::unsafe_arena_release_update_flags() {
  // @@protoc_insertion_point(field_release:update_engine.UpdateParams.update_flags)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::update_engine::UpdateFlags* temp = _impl_.update_flags_;
  _impl_.update_flags_ = nullptr;
  return temp;
}
inline ::update_engine::UpdateFlags* UpdateParams::_internal_mutable_update_flags() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.update_flags_ == nullptr) {
    auto* p = CreateMaybeMessage<::update_engine::UpdateFlags>(GetArenaForAllocation());
    _impl_.update_flags_ = p;
  }
  return _impl_.update_flags_;
}
inline ::update_engine::UpdateFlags* UpdateParams::mutable_update_flags() {
  ::update_engine::UpdateFlags* _msg = _internal_mutable_update_flags();
  // @@protoc_insertion_point(field_mutable:update_engine.UpdateParams.update_flags)
  return _msg;
}
inline void UpdateParams::set_allocated_update_flags(::update_engine::UpdateFlags* update_flags) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.update_flags_;
  }
  if (update_flags) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(update_flags);
    if (message_arena != submessage_arena) {
      update_flags = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_flags, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.update_flags_ = update_flags;
  // @@protoc_insertion_point(field_set_allocated:update_engine.UpdateParams.update_flags)
}

// bool skip_applying = 4;
inline void UpdateParams::clear_skip_applying() {
  _impl_.skip_applying_ = false;
}
inline bool UpdateParams::skip_applying() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateParams.skip_applying)
  return _internal_skip_applying();
}
inline void UpdateParams::set_skip_applying(bool value) {
  _internal_set_skip_applying(value);
  // @@protoc_insertion_point(field_set:update_engine.UpdateParams.skip_applying)
}
inline bool UpdateParams::_internal_skip_applying() const {
  return _impl_.skip_applying_;
}
inline void UpdateParams::_internal_set_skip_applying(bool value) {
  ;
  _impl_.skip_applying_ = value;
}

// bool force_fw_update = 5;
inline void UpdateParams::clear_force_fw_update() {
  _impl_.force_fw_update_ = false;
}
inline bool UpdateParams::force_fw_update() const {
  // @@protoc_insertion_point(field_get:update_engine.UpdateParams.force_fw_update)
  return _internal_force_fw_update();
}
inline void UpdateParams::set_force_fw_update(bool value) {
  _internal_set_force_fw_update(value);
  // @@protoc_insertion_point(field_set:update_engine.UpdateParams.force_fw_update)
}
inline bool UpdateParams::_internal_force_fw_update() const {
  return _impl_.force_fw_update_;
}
inline void UpdateParams::_internal_set_force_fw_update(bool value) {
  ;
  _impl_.force_fw_update_ = value;
}

// -------------------------------------------------------------------

// InstallParams

// string id = 1;
inline void InstallParams::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& InstallParams::id() const {
  // @@protoc_insertion_point(field_get:update_engine.InstallParams.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InstallParams::set_id(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.InstallParams.id)
}
inline std::string* InstallParams::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:update_engine.InstallParams.id)
  return _s;
}
inline const std::string& InstallParams::_internal_id() const {
  return _impl_.id_.Get();
}
inline void InstallParams::_internal_set_id(const std::string& value) {
  ;


  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* InstallParams::_internal_mutable_id() {
  ;
  return _impl_.id_.Mutable( GetArenaForAllocation());
}
inline std::string* InstallParams::release_id() {
  // @@protoc_insertion_point(field_release:update_engine.InstallParams.id)
  return _impl_.id_.Release();
}
inline void InstallParams::set_allocated_id(std::string* value) {
  _impl_.id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.InstallParams.id)
}

// string omaha_url = 2;
inline void InstallParams::clear_omaha_url() {
  _impl_.omaha_url_.ClearToEmpty();
}
inline const std::string& InstallParams::omaha_url() const {
  // @@protoc_insertion_point(field_get:update_engine.InstallParams.omaha_url)
  return _internal_omaha_url();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InstallParams::set_omaha_url(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.omaha_url_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:update_engine.InstallParams.omaha_url)
}
inline std::string* InstallParams::mutable_omaha_url() {
  std::string* _s = _internal_mutable_omaha_url();
  // @@protoc_insertion_point(field_mutable:update_engine.InstallParams.omaha_url)
  return _s;
}
inline const std::string& InstallParams::_internal_omaha_url() const {
  return _impl_.omaha_url_.Get();
}
inline void InstallParams::_internal_set_omaha_url(const std::string& value) {
  ;


  _impl_.omaha_url_.Set(value, GetArenaForAllocation());
}
inline std::string* InstallParams::_internal_mutable_omaha_url() {
  ;
  return _impl_.omaha_url_.Mutable( GetArenaForAllocation());
}
inline std::string* InstallParams::release_omaha_url() {
  // @@protoc_insertion_point(field_release:update_engine.InstallParams.omaha_url)
  return _impl_.omaha_url_.Release();
}
inline void InstallParams::set_allocated_omaha_url(std::string* value) {
  _impl_.omaha_url_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.omaha_url_.IsDefault()) {
          _impl_.omaha_url_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:update_engine.InstallParams.omaha_url)
}

// bool scaled = 3;
inline void InstallParams::clear_scaled() {
  _impl_.scaled_ = false;
}
inline bool InstallParams::scaled() const {
  // @@protoc_insertion_point(field_get:update_engine.InstallParams.scaled)
  return _internal_scaled();
}
inline void InstallParams::set_scaled(bool value) {
  _internal_set_scaled(value);
  // @@protoc_insertion_point(field_set:update_engine.InstallParams.scaled)
}
inline bool InstallParams::_internal_scaled() const {
  return _impl_.scaled_;
}
inline void InstallParams::_internal_set_scaled(bool value) {
  ;
  _impl_.scaled_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace update_engine


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::update_engine::Operation> : std::true_type {};
template <>
struct is_proto_enum<::update_engine::UpdateUrgency> : std::true_type {};
template <>
struct is_proto_enum<::update_engine::UpdateDoneAction> : std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_update_5fengine_2eproto_2epb_2eh
