// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chunneld_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chunneld_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chunneld_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry_lite.h>
#include <google/protobuf/map_field_lite.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chunneld_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chunneld_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace vm_tools {
namespace chunneld {
class UpdateListeningPortsRequest;
class UpdateListeningPortsRequestDefaultTypeInternal;
extern UpdateListeningPortsRequestDefaultTypeInternal _UpdateListeningPortsRequest_default_instance_;
class UpdateListeningPortsRequest_Tcp4ForwardTarget;
class UpdateListeningPortsRequest_Tcp4ForwardTargetDefaultTypeInternal;
extern UpdateListeningPortsRequest_Tcp4ForwardTargetDefaultTypeInternal _UpdateListeningPortsRequest_Tcp4ForwardTarget_default_instance_;
class UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse;
class UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUseDefaultTypeInternal;
extern UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUseDefaultTypeInternal _UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse_default_instance_;
class UpdateListeningPortsResponse;
class UpdateListeningPortsResponseDefaultTypeInternal;
extern UpdateListeningPortsResponseDefaultTypeInternal _UpdateListeningPortsResponse_default_instance_;
}  // namespace chunneld
}  // namespace vm_tools
PROTOBUF_NAMESPACE_OPEN
template<> ::vm_tools::chunneld::UpdateListeningPortsRequest* Arena::CreateMaybeMessage<::vm_tools::chunneld::UpdateListeningPortsRequest>(Arena*);
template<> ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget* Arena::CreateMaybeMessage<::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget>(Arena*);
template<> ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse* Arena::CreateMaybeMessage<::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse>(Arena*);
template<> ::vm_tools::chunneld::UpdateListeningPortsResponse* Arena::CreateMaybeMessage<::vm_tools::chunneld::UpdateListeningPortsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vm_tools {
namespace chunneld {

enum UpdateListeningPortsResponse_Status : int {
  UpdateListeningPortsResponse_Status_UNKNOWN = 0,
  UpdateListeningPortsResponse_Status_SUCCESS = 1,
  UpdateListeningPortsResponse_Status_FAILED = 2,
  UpdateListeningPortsResponse_Status_UpdateListeningPortsResponse_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  UpdateListeningPortsResponse_Status_UpdateListeningPortsResponse_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool UpdateListeningPortsResponse_Status_IsValid(int value);
constexpr UpdateListeningPortsResponse_Status UpdateListeningPortsResponse_Status_Status_MIN = UpdateListeningPortsResponse_Status_UNKNOWN;
constexpr UpdateListeningPortsResponse_Status UpdateListeningPortsResponse_Status_Status_MAX = UpdateListeningPortsResponse_Status_FAILED;
constexpr int UpdateListeningPortsResponse_Status_Status_ARRAYSIZE = UpdateListeningPortsResponse_Status_Status_MAX + 1;

const std::string& UpdateListeningPortsResponse_Status_Name(UpdateListeningPortsResponse_Status value);
template<typename T>
inline const std::string& UpdateListeningPortsResponse_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UpdateListeningPortsResponse_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UpdateListeningPortsResponse_Status_Name.");
  return UpdateListeningPortsResponse_Status_Name(static_cast<UpdateListeningPortsResponse_Status>(enum_t_value));
}
bool UpdateListeningPortsResponse_Status_Parse(
    const std::string& name, UpdateListeningPortsResponse_Status* value);
// ===================================================================

class UpdateListeningPortsRequest_Tcp4ForwardTarget :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget) */ {
 public:
  UpdateListeningPortsRequest_Tcp4ForwardTarget();
  virtual ~UpdateListeningPortsRequest_Tcp4ForwardTarget();

  UpdateListeningPortsRequest_Tcp4ForwardTarget(const UpdateListeningPortsRequest_Tcp4ForwardTarget& from);
  UpdateListeningPortsRequest_Tcp4ForwardTarget(UpdateListeningPortsRequest_Tcp4ForwardTarget&& from) noexcept
    : UpdateListeningPortsRequest_Tcp4ForwardTarget() {
    *this = ::std::move(from);
  }

  inline UpdateListeningPortsRequest_Tcp4ForwardTarget& operator=(const UpdateListeningPortsRequest_Tcp4ForwardTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateListeningPortsRequest_Tcp4ForwardTarget& operator=(UpdateListeningPortsRequest_Tcp4ForwardTarget&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const UpdateListeningPortsRequest_Tcp4ForwardTarget& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateListeningPortsRequest_Tcp4ForwardTarget* internal_default_instance() {
    return reinterpret_cast<const UpdateListeningPortsRequest_Tcp4ForwardTarget*>(
               &_UpdateListeningPortsRequest_Tcp4ForwardTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpdateListeningPortsRequest_Tcp4ForwardTarget& a, UpdateListeningPortsRequest_Tcp4ForwardTarget& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateListeningPortsRequest_Tcp4ForwardTarget* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateListeningPortsRequest_Tcp4ForwardTarget* New() const final {
    return CreateMaybeMessage<UpdateListeningPortsRequest_Tcp4ForwardTarget>(nullptr);
  }

  UpdateListeningPortsRequest_Tcp4ForwardTarget* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateListeningPortsRequest_Tcp4ForwardTarget>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const UpdateListeningPortsRequest_Tcp4ForwardTarget& from);
  void MergeFrom(const UpdateListeningPortsRequest_Tcp4ForwardTarget& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateListeningPortsRequest_Tcp4ForwardTarget* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVmNameFieldNumber = 1,
    kContainerNameFieldNumber = 2,
    kOwnerIdFieldNumber = 3,
    kVsockCidFieldNumber = 4,
  };
  // string vm_name = 1;
  void clear_vm_name();
  const std::string& vm_name() const;
  void set_vm_name(const std::string& value);
  void set_vm_name(std::string&& value);
  void set_vm_name(const char* value);
  void set_vm_name(const char* value, size_t size);
  std::string* mutable_vm_name();
  std::string* release_vm_name();
  void set_allocated_vm_name(std::string* vm_name);
  private:
  const std::string& _internal_vm_name() const;
  void _internal_set_vm_name(const std::string& value);
  std::string* _internal_mutable_vm_name();
  public:

  // string container_name = 2;
  void clear_container_name();
  const std::string& container_name() const;
  void set_container_name(const std::string& value);
  void set_container_name(std::string&& value);
  void set_container_name(const char* value);
  void set_container_name(const char* value, size_t size);
  std::string* mutable_container_name();
  std::string* release_container_name();
  void set_allocated_container_name(std::string* container_name);
  private:
  const std::string& _internal_container_name() const;
  void _internal_set_container_name(const std::string& value);
  std::string* _internal_mutable_container_name();
  public:

  // string owner_id = 3;
  void clear_owner_id();
  const std::string& owner_id() const;
  void set_owner_id(const std::string& value);
  void set_owner_id(std::string&& value);
  void set_owner_id(const char* value);
  void set_owner_id(const char* value, size_t size);
  std::string* mutable_owner_id();
  std::string* release_owner_id();
  void set_allocated_owner_id(std::string* owner_id);
  private:
  const std::string& _internal_owner_id() const;
  void _internal_set_owner_id(const std::string& value);
  std::string* _internal_mutable_owner_id();
  public:

  // uint32 vsock_cid = 4;
  void clear_vsock_cid();
  ::PROTOBUF_NAMESPACE_ID::uint32 vsock_cid() const;
  void set_vsock_cid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_vsock_cid() const;
  void _internal_set_vsock_cid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vm_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr container_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr owner_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 vsock_cid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_chunneld_5fservice_2eproto;
};
// -------------------------------------------------------------------

class UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntryLite<UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntryLite<UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse();
  UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse& other);
  static const UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse*>(&_UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
};

// -------------------------------------------------------------------

class UpdateListeningPortsRequest :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vm_tools.chunneld.UpdateListeningPortsRequest) */ {
 public:
  UpdateListeningPortsRequest();
  virtual ~UpdateListeningPortsRequest();

  UpdateListeningPortsRequest(const UpdateListeningPortsRequest& from);
  UpdateListeningPortsRequest(UpdateListeningPortsRequest&& from) noexcept
    : UpdateListeningPortsRequest() {
    *this = ::std::move(from);
  }

  inline UpdateListeningPortsRequest& operator=(const UpdateListeningPortsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateListeningPortsRequest& operator=(UpdateListeningPortsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const UpdateListeningPortsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateListeningPortsRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateListeningPortsRequest*>(
               &_UpdateListeningPortsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UpdateListeningPortsRequest& a, UpdateListeningPortsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateListeningPortsRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateListeningPortsRequest* New() const final {
    return CreateMaybeMessage<UpdateListeningPortsRequest>(nullptr);
  }

  UpdateListeningPortsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateListeningPortsRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const UpdateListeningPortsRequest& from);
  void MergeFrom(const UpdateListeningPortsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateListeningPortsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vm_tools.chunneld.UpdateListeningPortsRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef UpdateListeningPortsRequest_Tcp4ForwardTarget Tcp4ForwardTarget;

  // accessors -------------------------------------------------------

  enum : int {
    kTcp4ForwardTargetsFieldNumber = 1,
  };
  // map<uint32, .vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget> tcp4_forward_targets = 1;
  int tcp4_forward_targets_size() const;
  private:
  int _internal_tcp4_forward_targets_size() const;
  public:
  void clear_tcp4_forward_targets();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >&
      _internal_tcp4_forward_targets() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >*
      _internal_mutable_tcp4_forward_targets();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >&
      tcp4_forward_targets() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >*
      mutable_tcp4_forward_targets();

  // @@protoc_insertion_point(class_scope:vm_tools.chunneld.UpdateListeningPortsRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapFieldLite<
      UpdateListeningPortsRequest_Tcp4ForwardTargetsEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > tcp4_forward_targets_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_chunneld_5fservice_2eproto;
};
// -------------------------------------------------------------------

class UpdateListeningPortsResponse :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vm_tools.chunneld.UpdateListeningPortsResponse) */ {
 public:
  UpdateListeningPortsResponse();
  virtual ~UpdateListeningPortsResponse();

  UpdateListeningPortsResponse(const UpdateListeningPortsResponse& from);
  UpdateListeningPortsResponse(UpdateListeningPortsResponse&& from) noexcept
    : UpdateListeningPortsResponse() {
    *this = ::std::move(from);
  }

  inline UpdateListeningPortsResponse& operator=(const UpdateListeningPortsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateListeningPortsResponse& operator=(UpdateListeningPortsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const UpdateListeningPortsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateListeningPortsResponse* internal_default_instance() {
    return reinterpret_cast<const UpdateListeningPortsResponse*>(
               &_UpdateListeningPortsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UpdateListeningPortsResponse& a, UpdateListeningPortsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateListeningPortsResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateListeningPortsResponse* New() const final {
    return CreateMaybeMessage<UpdateListeningPortsResponse>(nullptr);
  }

  UpdateListeningPortsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateListeningPortsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const UpdateListeningPortsResponse& from);
  void MergeFrom(const UpdateListeningPortsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateListeningPortsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vm_tools.chunneld.UpdateListeningPortsResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef UpdateListeningPortsResponse_Status Status;
  static constexpr Status UNKNOWN =
    UpdateListeningPortsResponse_Status_UNKNOWN;
  static constexpr Status SUCCESS =
    UpdateListeningPortsResponse_Status_SUCCESS;
  static constexpr Status FAILED =
    UpdateListeningPortsResponse_Status_FAILED;
  static inline bool Status_IsValid(int value) {
    return UpdateListeningPortsResponse_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    UpdateListeningPortsResponse_Status_Status_MIN;
  static constexpr Status Status_MAX =
    UpdateListeningPortsResponse_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    UpdateListeningPortsResponse_Status_Status_ARRAYSIZE;
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return UpdateListeningPortsResponse_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(const std::string& name,
      Status* value) {
    return UpdateListeningPortsResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // .vm_tools.chunneld.UpdateListeningPortsResponse.Status status = 1;
  void clear_status();
  ::vm_tools::chunneld::UpdateListeningPortsResponse_Status status() const;
  void set_status(::vm_tools::chunneld::UpdateListeningPortsResponse_Status value);
  private:
  ::vm_tools::chunneld::UpdateListeningPortsResponse_Status _internal_status() const;
  void _internal_set_status(::vm_tools::chunneld::UpdateListeningPortsResponse_Status value);
  public:

  // @@protoc_insertion_point(class_scope:vm_tools.chunneld.UpdateListeningPortsResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_chunneld_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpdateListeningPortsRequest_Tcp4ForwardTarget

// string vm_name = 1;
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::clear_vm_name() {
  vm_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::vm_name() const {
  // @@protoc_insertion_point(field_get:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
  return _internal_vm_name();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_vm_name(const std::string& value) {
  _internal_set_vm_name(value);
  // @@protoc_insertion_point(field_set:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::mutable_vm_name() {
  // @@protoc_insertion_point(field_mutable:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
  return _internal_mutable_vm_name();
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_vm_name() const {
  return vm_name_.GetNoArena();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_set_vm_name(const std::string& value) {
  
  vm_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_vm_name(std::string&& value) {
  
  vm_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_vm_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  vm_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_vm_name(const char* value, size_t size) {
  
  vm_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_mutable_vm_name() {
  
  return vm_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::release_vm_name() {
  // @@protoc_insertion_point(field_release:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
  
  return vm_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_allocated_vm_name(std::string* vm_name) {
  if (vm_name != nullptr) {
    
  } else {
    
  }
  vm_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vm_name);
  // @@protoc_insertion_point(field_set_allocated:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vm_name)
}

// string container_name = 2;
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::clear_container_name() {
  container_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::container_name() const {
  // @@protoc_insertion_point(field_get:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
  return _internal_container_name();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_container_name(const std::string& value) {
  _internal_set_container_name(value);
  // @@protoc_insertion_point(field_set:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::mutable_container_name() {
  // @@protoc_insertion_point(field_mutable:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
  return _internal_mutable_container_name();
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_container_name() const {
  return container_name_.GetNoArena();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_set_container_name(const std::string& value) {
  
  container_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_container_name(std::string&& value) {
  
  container_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_container_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  container_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_container_name(const char* value, size_t size) {
  
  container_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_mutable_container_name() {
  
  return container_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::release_container_name() {
  // @@protoc_insertion_point(field_release:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
  
  return container_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_allocated_container_name(std::string* container_name) {
  if (container_name != nullptr) {
    
  } else {
    
  }
  container_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), container_name);
  // @@protoc_insertion_point(field_set_allocated:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.container_name)
}

// string owner_id = 3;
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::clear_owner_id() {
  owner_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::owner_id() const {
  // @@protoc_insertion_point(field_get:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
  return _internal_owner_id();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_owner_id(const std::string& value) {
  _internal_set_owner_id(value);
  // @@protoc_insertion_point(field_set:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::mutable_owner_id() {
  // @@protoc_insertion_point(field_mutable:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
  return _internal_mutable_owner_id();
}
inline const std::string& UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_owner_id() const {
  return owner_id_.GetNoArena();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_set_owner_id(const std::string& value) {
  
  owner_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_owner_id(std::string&& value) {
  
  owner_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_owner_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  owner_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_owner_id(const char* value, size_t size) {
  
  owner_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_mutable_owner_id() {
  
  return owner_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* UpdateListeningPortsRequest_Tcp4ForwardTarget::release_owner_id() {
  // @@protoc_insertion_point(field_release:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
  
  return owner_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_allocated_owner_id(std::string* owner_id) {
  if (owner_id != nullptr) {
    
  } else {
    
  }
  owner_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), owner_id);
  // @@protoc_insertion_point(field_set_allocated:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.owner_id)
}

// uint32 vsock_cid = 4;
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::clear_vsock_cid() {
  vsock_cid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_vsock_cid() const {
  return vsock_cid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UpdateListeningPortsRequest_Tcp4ForwardTarget::vsock_cid() const {
  // @@protoc_insertion_point(field_get:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vsock_cid)
  return _internal_vsock_cid();
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::_internal_set_vsock_cid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  vsock_cid_ = value;
}
inline void UpdateListeningPortsRequest_Tcp4ForwardTarget::set_vsock_cid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_vsock_cid(value);
  // @@protoc_insertion_point(field_set:vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget.vsock_cid)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// UpdateListeningPortsRequest

// map<uint32, .vm_tools.chunneld.UpdateListeningPortsRequest.Tcp4ForwardTarget> tcp4_forward_targets = 1;
inline int UpdateListeningPortsRequest::_internal_tcp4_forward_targets_size() const {
  return tcp4_forward_targets_.size();
}
inline int UpdateListeningPortsRequest::tcp4_forward_targets_size() const {
  return _internal_tcp4_forward_targets_size();
}
inline void UpdateListeningPortsRequest::clear_tcp4_forward_targets() {
  tcp4_forward_targets_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >&
UpdateListeningPortsRequest::_internal_tcp4_forward_targets() const {
  return tcp4_forward_targets_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >&
UpdateListeningPortsRequest::tcp4_forward_targets() const {
  // @@protoc_insertion_point(field_map:vm_tools.chunneld.UpdateListeningPortsRequest.tcp4_forward_targets)
  return _internal_tcp4_forward_targets();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >*
UpdateListeningPortsRequest::_internal_mutable_tcp4_forward_targets() {
  return tcp4_forward_targets_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::vm_tools::chunneld::UpdateListeningPortsRequest_Tcp4ForwardTarget >*
UpdateListeningPortsRequest::mutable_tcp4_forward_targets() {
  // @@protoc_insertion_point(field_mutable_map:vm_tools.chunneld.UpdateListeningPortsRequest.tcp4_forward_targets)
  return _internal_mutable_tcp4_forward_targets();
}

// -------------------------------------------------------------------

// UpdateListeningPortsResponse

// .vm_tools.chunneld.UpdateListeningPortsResponse.Status status = 1;
inline void UpdateListeningPortsResponse::clear_status() {
  status_ = 0;
}
inline ::vm_tools::chunneld::UpdateListeningPortsResponse_Status UpdateListeningPortsResponse::_internal_status() const {
  return static_cast< ::vm_tools::chunneld::UpdateListeningPortsResponse_Status >(status_);
}
inline ::vm_tools::chunneld::UpdateListeningPortsResponse_Status UpdateListeningPortsResponse::status() const {
  // @@protoc_insertion_point(field_get:vm_tools.chunneld.UpdateListeningPortsResponse.status)
  return _internal_status();
}
inline void UpdateListeningPortsResponse::_internal_set_status(::vm_tools::chunneld::UpdateListeningPortsResponse_Status value) {
  
  status_ = value;
}
inline void UpdateListeningPortsResponse::set_status(::vm_tools::chunneld::UpdateListeningPortsResponse_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:vm_tools.chunneld.UpdateListeningPortsResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chunneld
}  // namespace vm_tools

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::vm_tools::chunneld::UpdateListeningPortsResponse_Status> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chunneld_5fservice_2eproto
