// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vm_sk_forwarding/sk_forwarding.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto {
  static const ::uint32_t offsets[];
};
namespace vm_tools {
namespace sk_forwarding {
class ForwardSecurityKeyMessageRequest;
struct ForwardSecurityKeyMessageRequestDefaultTypeInternal;
extern ForwardSecurityKeyMessageRequestDefaultTypeInternal _ForwardSecurityKeyMessageRequest_default_instance_;
class ForwardSecurityKeyMessageResponse;
struct ForwardSecurityKeyMessageResponseDefaultTypeInternal;
extern ForwardSecurityKeyMessageResponseDefaultTypeInternal _ForwardSecurityKeyMessageResponse_default_instance_;
}  // namespace sk_forwarding
}  // namespace vm_tools
PROTOBUF_NAMESPACE_OPEN
template <>
::vm_tools::sk_forwarding::ForwardSecurityKeyMessageRequest* Arena::CreateMaybeMessage<::vm_tools::sk_forwarding::ForwardSecurityKeyMessageRequest>(Arena*);
template <>
::vm_tools::sk_forwarding::ForwardSecurityKeyMessageResponse* Arena::CreateMaybeMessage<::vm_tools::sk_forwarding::ForwardSecurityKeyMessageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace vm_tools {
namespace sk_forwarding {

// ===================================================================


// -------------------------------------------------------------------

class ForwardSecurityKeyMessageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest) */ {
 public:
  inline ForwardSecurityKeyMessageRequest() : ForwardSecurityKeyMessageRequest(nullptr) {}
  ~ForwardSecurityKeyMessageRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ForwardSecurityKeyMessageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardSecurityKeyMessageRequest(const ForwardSecurityKeyMessageRequest& from);
  ForwardSecurityKeyMessageRequest(ForwardSecurityKeyMessageRequest&& from) noexcept
    : ForwardSecurityKeyMessageRequest() {
    *this = ::std::move(from);
  }

  inline ForwardSecurityKeyMessageRequest& operator=(const ForwardSecurityKeyMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardSecurityKeyMessageRequest& operator=(ForwardSecurityKeyMessageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const ForwardSecurityKeyMessageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardSecurityKeyMessageRequest* internal_default_instance() {
    return reinterpret_cast<const ForwardSecurityKeyMessageRequest*>(
               &_ForwardSecurityKeyMessageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ForwardSecurityKeyMessageRequest& a, ForwardSecurityKeyMessageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardSecurityKeyMessageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardSecurityKeyMessageRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardSecurityKeyMessageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardSecurityKeyMessageRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ForwardSecurityKeyMessageRequest& from);
  void MergeFrom(const ForwardSecurityKeyMessageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ForwardSecurityKeyMessageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest";
  }
  protected:
  explicit ForwardSecurityKeyMessageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kVmNameFieldNumber = 2,
    kOwnerIdFieldNumber = 3,
  };
  // string message = 1;
  void clear_message() ;
  const std::string& message() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* ptr);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // string vm_name = 2;
  void clear_vm_name() ;
  const std::string& vm_name() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_vm_name(Arg_&& arg, Args_... args);
  std::string* mutable_vm_name();
  PROTOBUF_NODISCARD std::string* release_vm_name();
  void set_allocated_vm_name(std::string* ptr);

  private:
  const std::string& _internal_vm_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_vm_name(
      const std::string& value);
  std::string* _internal_mutable_vm_name();

  public:
  // string owner_id = 3;
  void clear_owner_id() ;
  const std::string& owner_id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_owner_id(Arg_&& arg, Args_... args);
  std::string* mutable_owner_id();
  PROTOBUF_NODISCARD std::string* release_owner_id();
  void set_allocated_owner_id(std::string* ptr);

  private:
  const std::string& _internal_owner_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_owner_id(
      const std::string& value);
  std::string* _internal_mutable_owner_id();

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vm_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr owner_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto;
};// -------------------------------------------------------------------

class ForwardSecurityKeyMessageResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse) */ {
 public:
  inline ForwardSecurityKeyMessageResponse() : ForwardSecurityKeyMessageResponse(nullptr) {}
  ~ForwardSecurityKeyMessageResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ForwardSecurityKeyMessageResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ForwardSecurityKeyMessageResponse(const ForwardSecurityKeyMessageResponse& from);
  ForwardSecurityKeyMessageResponse(ForwardSecurityKeyMessageResponse&& from) noexcept
    : ForwardSecurityKeyMessageResponse() {
    *this = ::std::move(from);
  }

  inline ForwardSecurityKeyMessageResponse& operator=(const ForwardSecurityKeyMessageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardSecurityKeyMessageResponse& operator=(ForwardSecurityKeyMessageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const ForwardSecurityKeyMessageResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ForwardSecurityKeyMessageResponse* internal_default_instance() {
    return reinterpret_cast<const ForwardSecurityKeyMessageResponse*>(
               &_ForwardSecurityKeyMessageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ForwardSecurityKeyMessageResponse& a, ForwardSecurityKeyMessageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardSecurityKeyMessageResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardSecurityKeyMessageResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ForwardSecurityKeyMessageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ForwardSecurityKeyMessageResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ForwardSecurityKeyMessageResponse& from);
  void MergeFrom(const ForwardSecurityKeyMessageResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ForwardSecurityKeyMessageResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse";
  }
  protected:
  explicit ForwardSecurityKeyMessageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message() ;
  const std::string& message() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* ptr);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ForwardSecurityKeyMessageRequest

// string message = 1;
inline void ForwardSecurityKeyMessageRequest::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ForwardSecurityKeyMessageRequest::message() const {
  // @@protoc_insertion_point(field_get:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ForwardSecurityKeyMessageRequest::set_message(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.message)
}
inline std::string* ForwardSecurityKeyMessageRequest::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.message)
  return _s;
}
inline const std::string& ForwardSecurityKeyMessageRequest::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ForwardSecurityKeyMessageRequest::_internal_set_message(const std::string& value) {
  ;


  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::_internal_mutable_message() {
  ;
  return _impl_.message_.Mutable( GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::release_message() {
  // @@protoc_insertion_point(field_release:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.message)
  return _impl_.message_.Release();
}
inline void ForwardSecurityKeyMessageRequest::set_allocated_message(std::string* value) {
  _impl_.message_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.message)
}

// string vm_name = 2;
inline void ForwardSecurityKeyMessageRequest::clear_vm_name() {
  _impl_.vm_name_.ClearToEmpty();
}
inline const std::string& ForwardSecurityKeyMessageRequest::vm_name() const {
  // @@protoc_insertion_point(field_get:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.vm_name)
  return _internal_vm_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ForwardSecurityKeyMessageRequest::set_vm_name(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.vm_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.vm_name)
}
inline std::string* ForwardSecurityKeyMessageRequest::mutable_vm_name() {
  std::string* _s = _internal_mutable_vm_name();
  // @@protoc_insertion_point(field_mutable:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.vm_name)
  return _s;
}
inline const std::string& ForwardSecurityKeyMessageRequest::_internal_vm_name() const {
  return _impl_.vm_name_.Get();
}
inline void ForwardSecurityKeyMessageRequest::_internal_set_vm_name(const std::string& value) {
  ;


  _impl_.vm_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::_internal_mutable_vm_name() {
  ;
  return _impl_.vm_name_.Mutable( GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::release_vm_name() {
  // @@protoc_insertion_point(field_release:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.vm_name)
  return _impl_.vm_name_.Release();
}
inline void ForwardSecurityKeyMessageRequest::set_allocated_vm_name(std::string* value) {
  _impl_.vm_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.vm_name_.IsDefault()) {
          _impl_.vm_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.vm_name)
}

// string owner_id = 3;
inline void ForwardSecurityKeyMessageRequest::clear_owner_id() {
  _impl_.owner_id_.ClearToEmpty();
}
inline const std::string& ForwardSecurityKeyMessageRequest::owner_id() const {
  // @@protoc_insertion_point(field_get:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.owner_id)
  return _internal_owner_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ForwardSecurityKeyMessageRequest::set_owner_id(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.owner_id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.owner_id)
}
inline std::string* ForwardSecurityKeyMessageRequest::mutable_owner_id() {
  std::string* _s = _internal_mutable_owner_id();
  // @@protoc_insertion_point(field_mutable:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.owner_id)
  return _s;
}
inline const std::string& ForwardSecurityKeyMessageRequest::_internal_owner_id() const {
  return _impl_.owner_id_.Get();
}
inline void ForwardSecurityKeyMessageRequest::_internal_set_owner_id(const std::string& value) {
  ;


  _impl_.owner_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::_internal_mutable_owner_id() {
  ;
  return _impl_.owner_id_.Mutable( GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageRequest::release_owner_id() {
  // @@protoc_insertion_point(field_release:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.owner_id)
  return _impl_.owner_id_.Release();
}
inline void ForwardSecurityKeyMessageRequest::set_allocated_owner_id(std::string* value) {
  _impl_.owner_id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.owner_id_.IsDefault()) {
          _impl_.owner_id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.sk_forwarding.ForwardSecurityKeyMessageRequest.owner_id)
}

// -------------------------------------------------------------------

// ForwardSecurityKeyMessageResponse

// string message = 1;
inline void ForwardSecurityKeyMessageResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ForwardSecurityKeyMessageResponse::message() const {
  // @@protoc_insertion_point(field_get:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ForwardSecurityKeyMessageResponse::set_message(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse.message)
}
inline std::string* ForwardSecurityKeyMessageResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse.message)
  return _s;
}
inline const std::string& ForwardSecurityKeyMessageResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ForwardSecurityKeyMessageResponse::_internal_set_message(const std::string& value) {
  ;


  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageResponse::_internal_mutable_message() {
  ;
  return _impl_.message_.Mutable( GetArenaForAllocation());
}
inline std::string* ForwardSecurityKeyMessageResponse::release_message() {
  // @@protoc_insertion_point(field_release:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse.message)
  return _impl_.message_.Release();
}
inline void ForwardSecurityKeyMessageResponse::set_allocated_message(std::string* value) {
  _impl_.message_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.sk_forwarding.ForwardSecurityKeyMessageResponse.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sk_forwarding
}  // namespace vm_tools


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_vm_5fsk_5fforwarding_2fsk_5fforwarding_2eproto_2epb_2eh
