/* Generated automatically by the program `genattr-common'
   from the machine description file `md'.  */

#ifndef GCC_INSN_ATTR_COMMON_H
#define GCC_INSN_ATTR_COMMON_H

enum attr_pipeline_model {PIPELINE_MODEL_N7, PIPELINE_MODEL_N8, PIPELINE_MODEL_E8, PIPELINE_MODEL_N9, PIPELINE_MODEL_N10, PIPELINE_MODEL_GRAYWOLF, PIPELINE_MODEL_N13, PIPELINE_MODEL_SIMPLE};
enum attr_type {TYPE_UNKNOWN, TYPE_LOAD, TYPE_STORE, TYPE_LOAD_MULTIPLE, TYPE_STORE_MULTIPLE, TYPE_ALU, TYPE_ALU_SHIFT, TYPE_PBSAD, TYPE_PBSADA, TYPE_MUL, TYPE_MAC, TYPE_DIV, TYPE_BRANCH, TYPE_MMU, TYPE_MISC, TYPE_FALU, TYPE_FMULS, TYPE_FMULD, TYPE_FMACS, TYPE_FMACD, TYPE_FDIVS, TYPE_FDIVD, TYPE_FSQRTS, TYPE_FSQRTD, TYPE_FCMP, TYPE_FABS, TYPE_FCPY, TYPE_FCMOV, TYPE_FMFSR, TYPE_FMFDR, TYPE_FMTSR, TYPE_FMTDR, TYPE_FLOAD, TYPE_FSTORE, TYPE_DALU, TYPE_DALU64, TYPE_DALUROUND, TYPE_DCMP, TYPE_DCLIP, TYPE_DMUL, TYPE_DMAC, TYPE_DINSB, TYPE_DPACK, TYPE_DBPICK, TYPE_DWEXT};
enum attr_subtype {SUBTYPE_SIMPLE, SUBTYPE_SHIFT, SUBTYPE_SATURATION};
enum attr_combo {COMBO_0, COMBO_1, COMBO_2, COMBO_3, COMBO_4, COMBO_5, COMBO_6, COMBO_7, COMBO_8, COMBO_9, COMBO_10, COMBO_11, COMBO_12, COMBO_13, COMBO_14, COMBO_15, COMBO_16, COMBO_17, COMBO_18, COMBO_19, COMBO_20, COMBO_21, COMBO_22, COMBO_23, COMBO_24, COMBO_25};
enum attr_feature {FEATURE_V1, FEATURE_V2, FEATURE_V3M, FEATURE_V3, FEATURE_PE1, FEATURE_PE2, FEATURE_SE, FEATURE_FPU};
enum attr_enabled {ENABLED_NO, ENABLED_YES};
#define INSN_SCHEDULING
#define DELAY_SLOTS 0

#endif /* GCC_INSN_ATTR_COMMON_H */
