// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_information.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5finformation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5finformation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5finformation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5finformation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace chromeos {
namespace cdm {
class ClientInformation;
class ClientInformationDefaultTypeInternal;
extern ClientInformationDefaultTypeInternal _ClientInformation_default_instance_;
}  // namespace cdm
}  // namespace chromeos
PROTOBUF_NAMESPACE_OPEN
template<> ::chromeos::cdm::ClientInformation* Arena::CreateMaybeMessage<::chromeos::cdm::ClientInformation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chromeos {
namespace cdm {

// ===================================================================

class ClientInformation :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chromeos.cdm.ClientInformation) */ {
 public:
  ClientInformation();
  virtual ~ClientInformation();

  ClientInformation(const ClientInformation& from);
  ClientInformation(ClientInformation&& from) noexcept
    : ClientInformation() {
    *this = ::std::move(from);
  }

  inline ClientInformation& operator=(const ClientInformation& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientInformation& operator=(ClientInformation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClientInformation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientInformation* internal_default_instance() {
    return reinterpret_cast<const ClientInformation*>(
               &_ClientInformation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientInformation& a, ClientInformation& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientInformation* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientInformation* New() const final {
    return CreateMaybeMessage<ClientInformation>(nullptr);
  }

  ClientInformation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientInformation>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ClientInformation& from);
  void MergeFrom(const ClientInformation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientInformation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chromeos.cdm.ClientInformation";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMakeFieldNumber = 1,
    kModelFieldNumber = 2,
    kManufacturerFieldNumber = 3,
  };
  // bytes make = 1;
  void clear_make();
  const std::string& make() const;
  void set_make(const std::string& value);
  void set_make(std::string&& value);
  void set_make(const char* value);
  void set_make(const void* value, size_t size);
  std::string* mutable_make();
  std::string* release_make();
  void set_allocated_make(std::string* make);
  private:
  const std::string& _internal_make() const;
  void _internal_set_make(const std::string& value);
  std::string* _internal_mutable_make();
  public:

  // bytes model = 2;
  void clear_model();
  const std::string& model() const;
  void set_model(const std::string& value);
  void set_model(std::string&& value);
  void set_model(const char* value);
  void set_model(const void* value, size_t size);
  std::string* mutable_model();
  std::string* release_model();
  void set_allocated_model(std::string* model);
  private:
  const std::string& _internal_model() const;
  void _internal_set_model(const std::string& value);
  std::string* _internal_mutable_model();
  public:

  // bytes manufacturer = 3;
  void clear_manufacturer();
  const std::string& manufacturer() const;
  void set_manufacturer(const std::string& value);
  void set_manufacturer(std::string&& value);
  void set_manufacturer(const char* value);
  void set_manufacturer(const void* value, size_t size);
  std::string* mutable_manufacturer();
  std::string* release_manufacturer();
  void set_allocated_manufacturer(std::string* manufacturer);
  private:
  const std::string& _internal_manufacturer() const;
  void _internal_set_manufacturer(const std::string& value);
  std::string* _internal_mutable_manufacturer();
  public:

  // @@protoc_insertion_point(class_scope:chromeos.cdm.ClientInformation)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr make_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr manufacturer_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5finformation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientInformation

// bytes make = 1;
inline void ClientInformation::clear_make() {
  make_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientInformation::make() const {
  // @@protoc_insertion_point(field_get:chromeos.cdm.ClientInformation.make)
  return _internal_make();
}
inline void ClientInformation::set_make(const std::string& value) {
  _internal_set_make(value);
  // @@protoc_insertion_point(field_set:chromeos.cdm.ClientInformation.make)
}
inline std::string* ClientInformation::mutable_make() {
  // @@protoc_insertion_point(field_mutable:chromeos.cdm.ClientInformation.make)
  return _internal_mutable_make();
}
inline const std::string& ClientInformation::_internal_make() const {
  return make_.GetNoArena();
}
inline void ClientInformation::_internal_set_make(const std::string& value) {
  
  make_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientInformation::set_make(std::string&& value) {
  
  make_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:chromeos.cdm.ClientInformation.make)
}
inline void ClientInformation::set_make(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  make_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chromeos.cdm.ClientInformation.make)
}
inline void ClientInformation::set_make(const void* value, size_t size) {
  
  make_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chromeos.cdm.ClientInformation.make)
}
inline std::string* ClientInformation::_internal_mutable_make() {
  
  return make_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientInformation::release_make() {
  // @@protoc_insertion_point(field_release:chromeos.cdm.ClientInformation.make)
  
  return make_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientInformation::set_allocated_make(std::string* make) {
  if (make != nullptr) {
    
  } else {
    
  }
  make_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), make);
  // @@protoc_insertion_point(field_set_allocated:chromeos.cdm.ClientInformation.make)
}

// bytes model = 2;
inline void ClientInformation::clear_model() {
  model_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientInformation::model() const {
  // @@protoc_insertion_point(field_get:chromeos.cdm.ClientInformation.model)
  return _internal_model();
}
inline void ClientInformation::set_model(const std::string& value) {
  _internal_set_model(value);
  // @@protoc_insertion_point(field_set:chromeos.cdm.ClientInformation.model)
}
inline std::string* ClientInformation::mutable_model() {
  // @@protoc_insertion_point(field_mutable:chromeos.cdm.ClientInformation.model)
  return _internal_mutable_model();
}
inline const std::string& ClientInformation::_internal_model() const {
  return model_.GetNoArena();
}
inline void ClientInformation::_internal_set_model(const std::string& value) {
  
  model_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientInformation::set_model(std::string&& value) {
  
  model_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:chromeos.cdm.ClientInformation.model)
}
inline void ClientInformation::set_model(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chromeos.cdm.ClientInformation.model)
}
inline void ClientInformation::set_model(const void* value, size_t size) {
  
  model_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chromeos.cdm.ClientInformation.model)
}
inline std::string* ClientInformation::_internal_mutable_model() {
  
  return model_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientInformation::release_model() {
  // @@protoc_insertion_point(field_release:chromeos.cdm.ClientInformation.model)
  
  return model_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientInformation::set_allocated_model(std::string* model) {
  if (model != nullptr) {
    
  } else {
    
  }
  model_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model);
  // @@protoc_insertion_point(field_set_allocated:chromeos.cdm.ClientInformation.model)
}

// bytes manufacturer = 3;
inline void ClientInformation::clear_manufacturer() {
  manufacturer_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientInformation::manufacturer() const {
  // @@protoc_insertion_point(field_get:chromeos.cdm.ClientInformation.manufacturer)
  return _internal_manufacturer();
}
inline void ClientInformation::set_manufacturer(const std::string& value) {
  _internal_set_manufacturer(value);
  // @@protoc_insertion_point(field_set:chromeos.cdm.ClientInformation.manufacturer)
}
inline std::string* ClientInformation::mutable_manufacturer() {
  // @@protoc_insertion_point(field_mutable:chromeos.cdm.ClientInformation.manufacturer)
  return _internal_mutable_manufacturer();
}
inline const std::string& ClientInformation::_internal_manufacturer() const {
  return manufacturer_.GetNoArena();
}
inline void ClientInformation::_internal_set_manufacturer(const std::string& value) {
  
  manufacturer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientInformation::set_manufacturer(std::string&& value) {
  
  manufacturer_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:chromeos.cdm.ClientInformation.manufacturer)
}
inline void ClientInformation::set_manufacturer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  manufacturer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:chromeos.cdm.ClientInformation.manufacturer)
}
inline void ClientInformation::set_manufacturer(const void* value, size_t size) {
  
  manufacturer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:chromeos.cdm.ClientInformation.manufacturer)
}
inline std::string* ClientInformation::_internal_mutable_manufacturer() {
  
  return manufacturer_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientInformation::release_manufacturer() {
  // @@protoc_insertion_point(field_release:chromeos.cdm.ClientInformation.manufacturer)
  
  return manufacturer_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientInformation::set_allocated_manufacturer(std::string* manufacturer) {
  if (manufacturer != nullptr) {
    
  } else {
    
  }
  manufacturer_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), manufacturer);
  // @@protoc_insertion_point(field_set_allocated:chromeos.cdm.ClientInformation.manufacturer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cdm
}  // namespace chromeos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5finformation_2eproto
