// Generated by partition_alloc/write_buildflag_header.py
// From "//libchrome:partition_allocator_raw_ptr_buildflags"

#ifndef LIBCHROME_BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_
#define LIBCHROME_BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_

#include "base/allocator/partition_allocator/src/partition_alloc/buildflag.h" // IWYU pragma: export

#include "build/buildflag.h" // IWYU pragma: export

#define PA_BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_CONSTRUCT() (1)
#define PA_BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_MOVE() (1)
#define PA_BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_DESTRUCT() (0)

#endif  // LIBCHROME_BASE_ALLOCATOR_PARTITION_ALLOCATOR_SRC_PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_
