// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fusebox.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fusebox_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_fusebox_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fusebox_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fusebox_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace fusebox {
class DirEntryListProto;
class DirEntryListProtoDefaultTypeInternal;
extern DirEntryListProtoDefaultTypeInternal _DirEntryListProto_default_instance_;
class DirEntryProto;
class DirEntryProtoDefaultTypeInternal;
extern DirEntryProtoDefaultTypeInternal _DirEntryProto_default_instance_;
}  // namespace fusebox
PROTOBUF_NAMESPACE_OPEN
template<> ::fusebox::DirEntryListProto* Arena::CreateMaybeMessage<::fusebox::DirEntryListProto>(Arena*);
template<> ::fusebox::DirEntryProto* Arena::CreateMaybeMessage<::fusebox::DirEntryProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fusebox {

// ===================================================================

class DirEntryProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:fusebox.DirEntryProto) */ {
 public:
  DirEntryProto();
  virtual ~DirEntryProto();

  DirEntryProto(const DirEntryProto& from);
  DirEntryProto(DirEntryProto&& from) noexcept
    : DirEntryProto() {
    *this = ::std::move(from);
  }

  inline DirEntryProto& operator=(const DirEntryProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirEntryProto& operator=(DirEntryProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const DirEntryProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirEntryProto* internal_default_instance() {
    return reinterpret_cast<const DirEntryProto*>(
               &_DirEntryProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DirEntryProto& a, DirEntryProto& b) {
    a.Swap(&b);
  }
  inline void Swap(DirEntryProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DirEntryProto* New() const final {
    return CreateMaybeMessage<DirEntryProto>(nullptr);
  }

  DirEntryProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DirEntryProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const DirEntryProto& from);
  void MergeFrom(const DirEntryProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DirEntryProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fusebox.DirEntryProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIsDirectoryFieldNumber = 1,
  };
  // optional string name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional bool is_directory = 1;
  bool has_is_directory() const;
  private:
  bool _internal_has_is_directory() const;
  public:
  void clear_is_directory();
  bool is_directory() const;
  void set_is_directory(bool value);
  private:
  bool _internal_is_directory() const;
  void _internal_set_is_directory(bool value);
  public:

  // @@protoc_insertion_point(class_scope:fusebox.DirEntryProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  bool is_directory_;
  friend struct ::TableStruct_fusebox_2eproto;
};
// -------------------------------------------------------------------

class DirEntryListProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:fusebox.DirEntryListProto) */ {
 public:
  DirEntryListProto();
  virtual ~DirEntryListProto();

  DirEntryListProto(const DirEntryListProto& from);
  DirEntryListProto(DirEntryListProto&& from) noexcept
    : DirEntryListProto() {
    *this = ::std::move(from);
  }

  inline DirEntryListProto& operator=(const DirEntryListProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirEntryListProto& operator=(DirEntryListProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const DirEntryListProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirEntryListProto* internal_default_instance() {
    return reinterpret_cast<const DirEntryListProto*>(
               &_DirEntryListProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DirEntryListProto& a, DirEntryListProto& b) {
    a.Swap(&b);
  }
  inline void Swap(DirEntryListProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DirEntryListProto* New() const final {
    return CreateMaybeMessage<DirEntryListProto>(nullptr);
  }

  DirEntryListProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DirEntryListProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const DirEntryListProto& from);
  void MergeFrom(const DirEntryListProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DirEntryListProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fusebox.DirEntryListProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 1,
  };
  // repeated .fusebox.DirEntryProto entries = 1;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::fusebox::DirEntryProto* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fusebox::DirEntryProto >*
      mutable_entries();
  private:
  const ::fusebox::DirEntryProto& _internal_entries(int index) const;
  ::fusebox::DirEntryProto* _internal_add_entries();
  public:
  const ::fusebox::DirEntryProto& entries(int index) const;
  ::fusebox::DirEntryProto* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fusebox::DirEntryProto >&
      entries() const;

  // @@protoc_insertion_point(class_scope:fusebox.DirEntryListProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fusebox::DirEntryProto > entries_;
  friend struct ::TableStruct_fusebox_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DirEntryProto

// optional bool is_directory = 1;
inline bool DirEntryProto::_internal_has_is_directory() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DirEntryProto::has_is_directory() const {
  return _internal_has_is_directory();
}
inline void DirEntryProto::clear_is_directory() {
  is_directory_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool DirEntryProto::_internal_is_directory() const {
  return is_directory_;
}
inline bool DirEntryProto::is_directory() const {
  // @@protoc_insertion_point(field_get:fusebox.DirEntryProto.is_directory)
  return _internal_is_directory();
}
inline void DirEntryProto::_internal_set_is_directory(bool value) {
  _has_bits_[0] |= 0x00000002u;
  is_directory_ = value;
}
inline void DirEntryProto::set_is_directory(bool value) {
  _internal_set_is_directory(value);
  // @@protoc_insertion_point(field_set:fusebox.DirEntryProto.is_directory)
}

// optional string name = 2;
inline bool DirEntryProto::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DirEntryProto::has_name() const {
  return _internal_has_name();
}
inline void DirEntryProto::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DirEntryProto::name() const {
  // @@protoc_insertion_point(field_get:fusebox.DirEntryProto.name)
  return _internal_name();
}
inline void DirEntryProto::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:fusebox.DirEntryProto.name)
}
inline std::string* DirEntryProto::mutable_name() {
  // @@protoc_insertion_point(field_mutable:fusebox.DirEntryProto.name)
  return _internal_mutable_name();
}
inline const std::string& DirEntryProto::_internal_name() const {
  return name_.GetNoArena();
}
inline void DirEntryProto::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DirEntryProto::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fusebox.DirEntryProto.name)
}
inline void DirEntryProto::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fusebox.DirEntryProto.name)
}
inline void DirEntryProto::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fusebox.DirEntryProto.name)
}
inline std::string* DirEntryProto::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DirEntryProto::release_name() {
  // @@protoc_insertion_point(field_release:fusebox.DirEntryProto.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DirEntryProto::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:fusebox.DirEntryProto.name)
}

// -------------------------------------------------------------------

// DirEntryListProto

// repeated .fusebox.DirEntryProto entries = 1;
inline int DirEntryListProto::_internal_entries_size() const {
  return entries_.size();
}
inline int DirEntryListProto::entries_size() const {
  return _internal_entries_size();
}
inline void DirEntryListProto::clear_entries() {
  entries_.Clear();
}
inline ::fusebox::DirEntryProto* DirEntryListProto::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:fusebox.DirEntryListProto.entries)
  return entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fusebox::DirEntryProto >*
DirEntryListProto::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:fusebox.DirEntryListProto.entries)
  return &entries_;
}
inline const ::fusebox::DirEntryProto& DirEntryListProto::_internal_entries(int index) const {
  return entries_.Get(index);
}
inline const ::fusebox::DirEntryProto& DirEntryListProto::entries(int index) const {
  // @@protoc_insertion_point(field_get:fusebox.DirEntryListProto.entries)
  return _internal_entries(index);
}
inline ::fusebox::DirEntryProto* DirEntryListProto::_internal_add_entries() {
  return entries_.Add();
}
inline ::fusebox::DirEntryProto* DirEntryListProto::add_entries() {
  // @@protoc_insertion_point(field_add:fusebox.DirEntryListProto.entries)
  return _internal_add_entries();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fusebox::DirEntryProto >&
DirEntryListProto::entries() const {
  // @@protoc_insertion_point(field_list:fusebox.DirEntryListProto.entries)
  return entries_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fusebox

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_fusebox_2eproto
