// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directory_entry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_directory_5fentry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_directory_5fentry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_directory_5fentry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_directory_5fentry_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace smbprovider {
class DirectoryEntryListProto;
class DirectoryEntryListProtoDefaultTypeInternal;
extern DirectoryEntryListProtoDefaultTypeInternal _DirectoryEntryListProto_default_instance_;
class DirectoryEntryProto;
class DirectoryEntryProtoDefaultTypeInternal;
extern DirectoryEntryProtoDefaultTypeInternal _DirectoryEntryProto_default_instance_;
class GetSharesOptionsProto;
class GetSharesOptionsProtoDefaultTypeInternal;
extern GetSharesOptionsProtoDefaultTypeInternal _GetSharesOptionsProto_default_instance_;
class HostnamesProto;
class HostnamesProtoDefaultTypeInternal;
extern HostnamesProtoDefaultTypeInternal _HostnamesProto_default_instance_;
}  // namespace smbprovider
PROTOBUF_NAMESPACE_OPEN
template<> ::smbprovider::DirectoryEntryListProto* Arena::CreateMaybeMessage<::smbprovider::DirectoryEntryListProto>(Arena*);
template<> ::smbprovider::DirectoryEntryProto* Arena::CreateMaybeMessage<::smbprovider::DirectoryEntryProto>(Arena*);
template<> ::smbprovider::GetSharesOptionsProto* Arena::CreateMaybeMessage<::smbprovider::GetSharesOptionsProto>(Arena*);
template<> ::smbprovider::HostnamesProto* Arena::CreateMaybeMessage<::smbprovider::HostnamesProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace smbprovider {

enum ErrorType : int {
  ERROR_NONE = 0,
  ERROR_OK = 1,
  ERROR_FAILED = 2,
  ERROR_IN_USE = 3,
  ERROR_EXISTS = 4,
  ERROR_NOT_FOUND = 5,
  ERROR_ACCESS_DENIED = 6,
  ERROR_TOO_MANY_OPENED = 7,
  ERROR_NO_MEMORY = 8,
  ERROR_NO_SPACE = 9,
  ERROR_NOT_A_DIRECTORY = 10,
  ERROR_INVALID_OPERATION = 11,
  ERROR_SECURITY = 12,
  ERROR_ABORT = 13,
  ERROR_NOT_A_FILE = 14,
  ERROR_NOT_EMPTY = 15,
  ERROR_INVALID_URL = 16,
  ERROR_IO = 17,
  ERROR_PROVIDER_ERROR_COUNT = 18,
  ERROR_DBUS_PARSE_FAILED = 50,
  ERROR_COPY_PENDING = 51,
  ERROR_COPY_FAILED = 52,
  ERROR_SMB1_UNSUPPORTED = 53,
  ERROR_OPERATION_PENDING = 54,
  ERROR_OPERATION_FAILED = 55
};
bool ErrorType_IsValid(int value);
constexpr ErrorType ErrorType_MIN = ERROR_NONE;
constexpr ErrorType ErrorType_MAX = ERROR_OPERATION_FAILED;
constexpr int ErrorType_ARRAYSIZE = ErrorType_MAX + 1;

const std::string& ErrorType_Name(ErrorType value);
template<typename T>
inline const std::string& ErrorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorType_Name.");
  return ErrorType_Name(static_cast<ErrorType>(enum_t_value));
}
bool ErrorType_Parse(
    const std::string& name, ErrorType* value);
// ===================================================================

class DirectoryEntryProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:smbprovider.DirectoryEntryProto) */ {
 public:
  DirectoryEntryProto();
  virtual ~DirectoryEntryProto();

  DirectoryEntryProto(const DirectoryEntryProto& from);
  DirectoryEntryProto(DirectoryEntryProto&& from) noexcept
    : DirectoryEntryProto() {
    *this = ::std::move(from);
  }

  inline DirectoryEntryProto& operator=(const DirectoryEntryProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirectoryEntryProto& operator=(DirectoryEntryProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const DirectoryEntryProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirectoryEntryProto* internal_default_instance() {
    return reinterpret_cast<const DirectoryEntryProto*>(
               &_DirectoryEntryProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DirectoryEntryProto& a, DirectoryEntryProto& b) {
    a.Swap(&b);
  }
  inline void Swap(DirectoryEntryProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DirectoryEntryProto* New() const final {
    return CreateMaybeMessage<DirectoryEntryProto>(nullptr);
  }

  DirectoryEntryProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DirectoryEntryProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const DirectoryEntryProto& from);
  void MergeFrom(const DirectoryEntryProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DirectoryEntryProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smbprovider.DirectoryEntryProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kSizeFieldNumber = 3,
    kLastModifiedTimeFieldNumber = 4,
    kIsDirectoryFieldNumber = 1,
  };
  // optional string name = 2;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional int64 size = 3;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  ::PROTOBUF_NAMESPACE_ID::int64 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_size() const;
  void _internal_set_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int64 last_modified_time = 4;
  bool has_last_modified_time() const;
  private:
  bool _internal_has_last_modified_time() const;
  public:
  void clear_last_modified_time();
  ::PROTOBUF_NAMESPACE_ID::int64 last_modified_time() const;
  void set_last_modified_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_last_modified_time() const;
  void _internal_set_last_modified_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional bool is_directory = 1;
  bool has_is_directory() const;
  private:
  bool _internal_has_is_directory() const;
  public:
  void clear_is_directory();
  bool is_directory() const;
  void set_is_directory(bool value);
  private:
  bool _internal_is_directory() const;
  void _internal_set_is_directory(bool value);
  public:

  // @@protoc_insertion_point(class_scope:smbprovider.DirectoryEntryProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int64 size_;
  ::PROTOBUF_NAMESPACE_ID::int64 last_modified_time_;
  bool is_directory_;
  friend struct ::TableStruct_directory_5fentry_2eproto;
};
// -------------------------------------------------------------------

class DirectoryEntryListProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:smbprovider.DirectoryEntryListProto) */ {
 public:
  DirectoryEntryListProto();
  virtual ~DirectoryEntryListProto();

  DirectoryEntryListProto(const DirectoryEntryListProto& from);
  DirectoryEntryListProto(DirectoryEntryListProto&& from) noexcept
    : DirectoryEntryListProto() {
    *this = ::std::move(from);
  }

  inline DirectoryEntryListProto& operator=(const DirectoryEntryListProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirectoryEntryListProto& operator=(DirectoryEntryListProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const DirectoryEntryListProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DirectoryEntryListProto* internal_default_instance() {
    return reinterpret_cast<const DirectoryEntryListProto*>(
               &_DirectoryEntryListProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DirectoryEntryListProto& a, DirectoryEntryListProto& b) {
    a.Swap(&b);
  }
  inline void Swap(DirectoryEntryListProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DirectoryEntryListProto* New() const final {
    return CreateMaybeMessage<DirectoryEntryListProto>(nullptr);
  }

  DirectoryEntryListProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DirectoryEntryListProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const DirectoryEntryListProto& from);
  void MergeFrom(const DirectoryEntryListProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DirectoryEntryListProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smbprovider.DirectoryEntryListProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 1,
  };
  // repeated .smbprovider.DirectoryEntryProto entries = 1;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::smbprovider::DirectoryEntryProto* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::smbprovider::DirectoryEntryProto >*
      mutable_entries();
  private:
  const ::smbprovider::DirectoryEntryProto& _internal_entries(int index) const;
  ::smbprovider::DirectoryEntryProto* _internal_add_entries();
  public:
  const ::smbprovider::DirectoryEntryProto& entries(int index) const;
  ::smbprovider::DirectoryEntryProto* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::smbprovider::DirectoryEntryProto >&
      entries() const;

  // @@protoc_insertion_point(class_scope:smbprovider.DirectoryEntryListProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::smbprovider::DirectoryEntryProto > entries_;
  friend struct ::TableStruct_directory_5fentry_2eproto;
};
// -------------------------------------------------------------------

class GetSharesOptionsProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:smbprovider.GetSharesOptionsProto) */ {
 public:
  GetSharesOptionsProto();
  virtual ~GetSharesOptionsProto();

  GetSharesOptionsProto(const GetSharesOptionsProto& from);
  GetSharesOptionsProto(GetSharesOptionsProto&& from) noexcept
    : GetSharesOptionsProto() {
    *this = ::std::move(from);
  }

  inline GetSharesOptionsProto& operator=(const GetSharesOptionsProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetSharesOptionsProto& operator=(GetSharesOptionsProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const GetSharesOptionsProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetSharesOptionsProto* internal_default_instance() {
    return reinterpret_cast<const GetSharesOptionsProto*>(
               &_GetSharesOptionsProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetSharesOptionsProto& a, GetSharesOptionsProto& b) {
    a.Swap(&b);
  }
  inline void Swap(GetSharesOptionsProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetSharesOptionsProto* New() const final {
    return CreateMaybeMessage<GetSharesOptionsProto>(nullptr);
  }

  GetSharesOptionsProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetSharesOptionsProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const GetSharesOptionsProto& from);
  void MergeFrom(const GetSharesOptionsProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetSharesOptionsProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smbprovider.GetSharesOptionsProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerUrlFieldNumber = 1,
  };
  // optional string server_url = 1;
  bool has_server_url() const;
  private:
  bool _internal_has_server_url() const;
  public:
  void clear_server_url();
  const std::string& server_url() const;
  void set_server_url(const std::string& value);
  void set_server_url(std::string&& value);
  void set_server_url(const char* value);
  void set_server_url(const char* value, size_t size);
  std::string* mutable_server_url();
  std::string* release_server_url();
  void set_allocated_server_url(std::string* server_url);
  private:
  const std::string& _internal_server_url() const;
  void _internal_set_server_url(const std::string& value);
  std::string* _internal_mutable_server_url();
  public:

  // @@protoc_insertion_point(class_scope:smbprovider.GetSharesOptionsProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_url_;
  friend struct ::TableStruct_directory_5fentry_2eproto;
};
// -------------------------------------------------------------------

class HostnamesProto :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:smbprovider.HostnamesProto) */ {
 public:
  HostnamesProto();
  virtual ~HostnamesProto();

  HostnamesProto(const HostnamesProto& from);
  HostnamesProto(HostnamesProto&& from) noexcept
    : HostnamesProto() {
    *this = ::std::move(from);
  }

  inline HostnamesProto& operator=(const HostnamesProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostnamesProto& operator=(HostnamesProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const HostnamesProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HostnamesProto* internal_default_instance() {
    return reinterpret_cast<const HostnamesProto*>(
               &_HostnamesProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HostnamesProto& a, HostnamesProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HostnamesProto* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline HostnamesProto* New() const final {
    return CreateMaybeMessage<HostnamesProto>(nullptr);
  }

  HostnamesProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<HostnamesProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const HostnamesProto& from);
  void MergeFrom(const HostnamesProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HostnamesProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "smbprovider.HostnamesProto";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostnamesFieldNumber = 1,
  };
  // repeated string hostnames = 1;
  int hostnames_size() const;
  private:
  int _internal_hostnames_size() const;
  public:
  void clear_hostnames();
  const std::string& hostnames(int index) const;
  std::string* mutable_hostnames(int index);
  void set_hostnames(int index, const std::string& value);
  void set_hostnames(int index, std::string&& value);
  void set_hostnames(int index, const char* value);
  void set_hostnames(int index, const char* value, size_t size);
  std::string* add_hostnames();
  void add_hostnames(const std::string& value);
  void add_hostnames(std::string&& value);
  void add_hostnames(const char* value);
  void add_hostnames(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& hostnames() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_hostnames();
  private:
  const std::string& _internal_hostnames(int index) const;
  std::string* _internal_add_hostnames();
  public:

  // @@protoc_insertion_point(class_scope:smbprovider.HostnamesProto)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> hostnames_;
  friend struct ::TableStruct_directory_5fentry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DirectoryEntryProto

// optional bool is_directory = 1;
inline bool DirectoryEntryProto::_internal_has_is_directory() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool DirectoryEntryProto::has_is_directory() const {
  return _internal_has_is_directory();
}
inline void DirectoryEntryProto::clear_is_directory() {
  is_directory_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool DirectoryEntryProto::_internal_is_directory() const {
  return is_directory_;
}
inline bool DirectoryEntryProto::is_directory() const {
  // @@protoc_insertion_point(field_get:smbprovider.DirectoryEntryProto.is_directory)
  return _internal_is_directory();
}
inline void DirectoryEntryProto::_internal_set_is_directory(bool value) {
  _has_bits_[0] |= 0x00000008u;
  is_directory_ = value;
}
inline void DirectoryEntryProto::set_is_directory(bool value) {
  _internal_set_is_directory(value);
  // @@protoc_insertion_point(field_set:smbprovider.DirectoryEntryProto.is_directory)
}

// optional string name = 2;
inline bool DirectoryEntryProto::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DirectoryEntryProto::has_name() const {
  return _internal_has_name();
}
inline void DirectoryEntryProto::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DirectoryEntryProto::name() const {
  // @@protoc_insertion_point(field_get:smbprovider.DirectoryEntryProto.name)
  return _internal_name();
}
inline void DirectoryEntryProto::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:smbprovider.DirectoryEntryProto.name)
}
inline std::string* DirectoryEntryProto::mutable_name() {
  // @@protoc_insertion_point(field_mutable:smbprovider.DirectoryEntryProto.name)
  return _internal_mutable_name();
}
inline const std::string& DirectoryEntryProto::_internal_name() const {
  return name_.GetNoArena();
}
inline void DirectoryEntryProto::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DirectoryEntryProto::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:smbprovider.DirectoryEntryProto.name)
}
inline void DirectoryEntryProto::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:smbprovider.DirectoryEntryProto.name)
}
inline void DirectoryEntryProto::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:smbprovider.DirectoryEntryProto.name)
}
inline std::string* DirectoryEntryProto::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DirectoryEntryProto::release_name() {
  // @@protoc_insertion_point(field_release:smbprovider.DirectoryEntryProto.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DirectoryEntryProto::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:smbprovider.DirectoryEntryProto.name)
}

// optional int64 size = 3;
inline bool DirectoryEntryProto::_internal_has_size() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DirectoryEntryProto::has_size() const {
  return _internal_has_size();
}
inline void DirectoryEntryProto::clear_size() {
  size_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DirectoryEntryProto::_internal_size() const {
  return size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DirectoryEntryProto::size() const {
  // @@protoc_insertion_point(field_get:smbprovider.DirectoryEntryProto.size)
  return _internal_size();
}
inline void DirectoryEntryProto::_internal_set_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  size_ = value;
}
inline void DirectoryEntryProto::set_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:smbprovider.DirectoryEntryProto.size)
}

// optional int64 last_modified_time = 4;
inline bool DirectoryEntryProto::_internal_has_last_modified_time() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool DirectoryEntryProto::has_last_modified_time() const {
  return _internal_has_last_modified_time();
}
inline void DirectoryEntryProto::clear_last_modified_time() {
  last_modified_time_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DirectoryEntryProto::_internal_last_modified_time() const {
  return last_modified_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DirectoryEntryProto::last_modified_time() const {
  // @@protoc_insertion_point(field_get:smbprovider.DirectoryEntryProto.last_modified_time)
  return _internal_last_modified_time();
}
inline void DirectoryEntryProto::_internal_set_last_modified_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  last_modified_time_ = value;
}
inline void DirectoryEntryProto::set_last_modified_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_last_modified_time(value);
  // @@protoc_insertion_point(field_set:smbprovider.DirectoryEntryProto.last_modified_time)
}

// -------------------------------------------------------------------

// DirectoryEntryListProto

// repeated .smbprovider.DirectoryEntryProto entries = 1;
inline int DirectoryEntryListProto::_internal_entries_size() const {
  return entries_.size();
}
inline int DirectoryEntryListProto::entries_size() const {
  return _internal_entries_size();
}
inline void DirectoryEntryListProto::clear_entries() {
  entries_.Clear();
}
inline ::smbprovider::DirectoryEntryProto* DirectoryEntryListProto::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:smbprovider.DirectoryEntryListProto.entries)
  return entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::smbprovider::DirectoryEntryProto >*
DirectoryEntryListProto::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:smbprovider.DirectoryEntryListProto.entries)
  return &entries_;
}
inline const ::smbprovider::DirectoryEntryProto& DirectoryEntryListProto::_internal_entries(int index) const {
  return entries_.Get(index);
}
inline const ::smbprovider::DirectoryEntryProto& DirectoryEntryListProto::entries(int index) const {
  // @@protoc_insertion_point(field_get:smbprovider.DirectoryEntryListProto.entries)
  return _internal_entries(index);
}
inline ::smbprovider::DirectoryEntryProto* DirectoryEntryListProto::_internal_add_entries() {
  return entries_.Add();
}
inline ::smbprovider::DirectoryEntryProto* DirectoryEntryListProto::add_entries() {
  // @@protoc_insertion_point(field_add:smbprovider.DirectoryEntryListProto.entries)
  return _internal_add_entries();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::smbprovider::DirectoryEntryProto >&
DirectoryEntryListProto::entries() const {
  // @@protoc_insertion_point(field_list:smbprovider.DirectoryEntryListProto.entries)
  return entries_;
}

// -------------------------------------------------------------------

// GetSharesOptionsProto

// optional string server_url = 1;
inline bool GetSharesOptionsProto::_internal_has_server_url() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GetSharesOptionsProto::has_server_url() const {
  return _internal_has_server_url();
}
inline void GetSharesOptionsProto::clear_server_url() {
  server_url_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GetSharesOptionsProto::server_url() const {
  // @@protoc_insertion_point(field_get:smbprovider.GetSharesOptionsProto.server_url)
  return _internal_server_url();
}
inline void GetSharesOptionsProto::set_server_url(const std::string& value) {
  _internal_set_server_url(value);
  // @@protoc_insertion_point(field_set:smbprovider.GetSharesOptionsProto.server_url)
}
inline std::string* GetSharesOptionsProto::mutable_server_url() {
  // @@protoc_insertion_point(field_mutable:smbprovider.GetSharesOptionsProto.server_url)
  return _internal_mutable_server_url();
}
inline const std::string& GetSharesOptionsProto::_internal_server_url() const {
  return server_url_.GetNoArena();
}
inline void GetSharesOptionsProto::_internal_set_server_url(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  server_url_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void GetSharesOptionsProto::set_server_url(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  server_url_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:smbprovider.GetSharesOptionsProto.server_url)
}
inline void GetSharesOptionsProto::set_server_url(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  server_url_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:smbprovider.GetSharesOptionsProto.server_url)
}
inline void GetSharesOptionsProto::set_server_url(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  server_url_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:smbprovider.GetSharesOptionsProto.server_url)
}
inline std::string* GetSharesOptionsProto::_internal_mutable_server_url() {
  _has_bits_[0] |= 0x00000001u;
  return server_url_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GetSharesOptionsProto::release_server_url() {
  // @@protoc_insertion_point(field_release:smbprovider.GetSharesOptionsProto.server_url)
  if (!_internal_has_server_url()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return server_url_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GetSharesOptionsProto::set_allocated_server_url(std::string* server_url) {
  if (server_url != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  server_url_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), server_url);
  // @@protoc_insertion_point(field_set_allocated:smbprovider.GetSharesOptionsProto.server_url)
}

// -------------------------------------------------------------------

// HostnamesProto

// repeated string hostnames = 1;
inline int HostnamesProto::_internal_hostnames_size() const {
  return hostnames_.size();
}
inline int HostnamesProto::hostnames_size() const {
  return _internal_hostnames_size();
}
inline void HostnamesProto::clear_hostnames() {
  hostnames_.Clear();
}
inline std::string* HostnamesProto::add_hostnames() {
  // @@protoc_insertion_point(field_add_mutable:smbprovider.HostnamesProto.hostnames)
  return _internal_add_hostnames();
}
inline const std::string& HostnamesProto::_internal_hostnames(int index) const {
  return hostnames_.Get(index);
}
inline const std::string& HostnamesProto::hostnames(int index) const {
  // @@protoc_insertion_point(field_get:smbprovider.HostnamesProto.hostnames)
  return _internal_hostnames(index);
}
inline std::string* HostnamesProto::mutable_hostnames(int index) {
  // @@protoc_insertion_point(field_mutable:smbprovider.HostnamesProto.hostnames)
  return hostnames_.Mutable(index);
}
inline void HostnamesProto::set_hostnames(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:smbprovider.HostnamesProto.hostnames)
  hostnames_.Mutable(index)->assign(value);
}
inline void HostnamesProto::set_hostnames(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:smbprovider.HostnamesProto.hostnames)
  hostnames_.Mutable(index)->assign(std::move(value));
}
inline void HostnamesProto::set_hostnames(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  hostnames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:smbprovider.HostnamesProto.hostnames)
}
inline void HostnamesProto::set_hostnames(int index, const char* value, size_t size) {
  hostnames_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:smbprovider.HostnamesProto.hostnames)
}
inline std::string* HostnamesProto::_internal_add_hostnames() {
  return hostnames_.Add();
}
inline void HostnamesProto::add_hostnames(const std::string& value) {
  hostnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:smbprovider.HostnamesProto.hostnames)
}
inline void HostnamesProto::add_hostnames(std::string&& value) {
  hostnames_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:smbprovider.HostnamesProto.hostnames)
}
inline void HostnamesProto::add_hostnames(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  hostnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:smbprovider.HostnamesProto.hostnames)
}
inline void HostnamesProto::add_hostnames(const char* value, size_t size) {
  hostnames_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:smbprovider.HostnamesProto.hostnames)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
HostnamesProto::hostnames() const {
  // @@protoc_insertion_point(field_list:smbprovider.HostnamesProto.hostnames)
  return hostnames_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
HostnamesProto::mutable_hostnames() {
  // @@protoc_insertion_point(field_mutable_list:smbprovider.HostnamesProto.hostnames)
  return &hostnames_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace smbprovider

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::smbprovider::ErrorType> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_directory_5fentry_2eproto
