// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vm_host.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vm_5fhost_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_vm_5fhost_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vm_5fhost_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vm_5fhost_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_vm_5fhost_2eproto;
namespace vm_tools {
class LogRecord;
struct LogRecordDefaultTypeInternal;
extern LogRecordDefaultTypeInternal _LogRecord_default_instance_;
class LogRequest;
struct LogRequestDefaultTypeInternal;
extern LogRequestDefaultTypeInternal _LogRequest_default_instance_;
class Timestamp;
struct TimestampDefaultTypeInternal;
extern TimestampDefaultTypeInternal _Timestamp_default_instance_;
class VmInstallState;
struct VmInstallStateDefaultTypeInternal;
extern VmInstallStateDefaultTypeInternal _VmInstallState_default_instance_;
class VmKernelLogRequest;
struct VmKernelLogRequestDefaultTypeInternal;
extern VmKernelLogRequestDefaultTypeInternal _VmKernelLogRequest_default_instance_;
}  // namespace vm_tools
PROTOBUF_NAMESPACE_OPEN
template <>
::vm_tools::LogRecord* Arena::CreateMaybeMessage<::vm_tools::LogRecord>(Arena*);
template <>
::vm_tools::LogRequest* Arena::CreateMaybeMessage<::vm_tools::LogRequest>(Arena*);
template <>
::vm_tools::Timestamp* Arena::CreateMaybeMessage<::vm_tools::Timestamp>(Arena*);
template <>
::vm_tools::VmInstallState* Arena::CreateMaybeMessage<::vm_tools::VmInstallState>(Arena*);
template <>
::vm_tools::VmKernelLogRequest* Arena::CreateMaybeMessage<::vm_tools::VmKernelLogRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace vm_tools {
enum VmInstallState_State : int {
  VmInstallState_State_UNKNOWN = 0,
  VmInstallState_State_IN_PROGRESS = 1,
  VmInstallState_State_FAILED = 2,
  VmInstallState_State_SUCCEEDED = 3,
  VmInstallState_State_VmInstallState_State_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  VmInstallState_State_VmInstallState_State_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool VmInstallState_State_IsValid(int value);
constexpr VmInstallState_State VmInstallState_State_State_MIN = static_cast<VmInstallState_State>(0);
constexpr VmInstallState_State VmInstallState_State_State_MAX = static_cast<VmInstallState_State>(3);
constexpr int VmInstallState_State_State_ARRAYSIZE = 3 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
VmInstallState_State_descriptor();
template <typename T>
const std::string& VmInstallState_State_Name(T value) {
  static_assert(std::is_same<T, VmInstallState_State>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to State_Name().");
  return VmInstallState_State_Name(static_cast<VmInstallState_State>(value));
}
template <>
inline const std::string& VmInstallState_State_Name(VmInstallState_State value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<VmInstallState_State_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool VmInstallState_State_Parse(absl::string_view name, VmInstallState_State* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<VmInstallState_State>(
      VmInstallState_State_descriptor(), name, value);
}
enum VmInstallState_Step : int {
  VmInstallState_Step_unknown = 0,
  VmInstallState_Step_launcher_start = 1,
  VmInstallState_Step_core_start = 2,
  VmInstallState_Step_install_fetch_image = 3,
  VmInstallState_Step_install_configure = 4,
  VmInstallState_Step_install_done = 5,
  VmInstallState_Step_install_success = 6,
  VmInstallState_Step_install_failure = 7,
  VmInstallState_Step_VmInstallState_Step_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  VmInstallState_Step_VmInstallState_Step_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool VmInstallState_Step_IsValid(int value);
constexpr VmInstallState_Step VmInstallState_Step_Step_MIN = static_cast<VmInstallState_Step>(0);
constexpr VmInstallState_Step VmInstallState_Step_Step_MAX = static_cast<VmInstallState_Step>(7);
constexpr int VmInstallState_Step_Step_ARRAYSIZE = 7 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
VmInstallState_Step_descriptor();
template <typename T>
const std::string& VmInstallState_Step_Name(T value) {
  static_assert(std::is_same<T, VmInstallState_Step>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Step_Name().");
  return VmInstallState_Step_Name(static_cast<VmInstallState_Step>(value));
}
template <>
inline const std::string& VmInstallState_Step_Name(VmInstallState_Step value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<VmInstallState_Step_descriptor,
                                                 0, 7>(
      static_cast<int>(value));
}
inline bool VmInstallState_Step_Parse(absl::string_view name, VmInstallState_Step* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<VmInstallState_Step>(
      VmInstallState_Step_descriptor(), name, value);
}
enum VmKernelLogRequest_VmType : int {
  VmKernelLogRequest_VmType_UNKNOWN = 0,
  VmKernelLogRequest_VmType_TERMINA = 1,
  VmKernelLogRequest_VmType_ARC_VM = 2,
  VmKernelLogRequest_VmType_PLUGIN_VM = 3,
  VmKernelLogRequest_VmType_BOREALIS = 4,
  VmKernelLogRequest_VmType_BRUSCHETTA = 5,
  VmKernelLogRequest_VmType_BAGUETTE = 6,
  VmKernelLogRequest_VmType_VmKernelLogRequest_VmType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  VmKernelLogRequest_VmType_VmKernelLogRequest_VmType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool VmKernelLogRequest_VmType_IsValid(int value);
constexpr VmKernelLogRequest_VmType VmKernelLogRequest_VmType_VmType_MIN = static_cast<VmKernelLogRequest_VmType>(0);
constexpr VmKernelLogRequest_VmType VmKernelLogRequest_VmType_VmType_MAX = static_cast<VmKernelLogRequest_VmType>(6);
constexpr int VmKernelLogRequest_VmType_VmType_ARRAYSIZE = 6 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
VmKernelLogRequest_VmType_descriptor();
template <typename T>
const std::string& VmKernelLogRequest_VmType_Name(T value) {
  static_assert(std::is_same<T, VmKernelLogRequest_VmType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to VmType_Name().");
  return VmKernelLogRequest_VmType_Name(static_cast<VmKernelLogRequest_VmType>(value));
}
template <>
inline const std::string& VmKernelLogRequest_VmType_Name(VmKernelLogRequest_VmType value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<VmKernelLogRequest_VmType_descriptor,
                                                 0, 6>(
      static_cast<int>(value));
}
inline bool VmKernelLogRequest_VmType_Parse(absl::string_view name, VmKernelLogRequest_VmType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<VmKernelLogRequest_VmType>(
      VmKernelLogRequest_VmType_descriptor(), name, value);
}
enum LogSeverity : int {
  MISSING = 0,
  EMERGENCY = 1,
  ALERT = 2,
  CRITICAL = 3,
  ERROR = 4,
  WARNING = 5,
  NOTICE = 6,
  INFO = 7,
  DEBUG = 8,
  LogSeverity_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  LogSeverity_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool LogSeverity_IsValid(int value);
constexpr LogSeverity LogSeverity_MIN = static_cast<LogSeverity>(0);
constexpr LogSeverity LogSeverity_MAX = static_cast<LogSeverity>(8);
constexpr int LogSeverity_ARRAYSIZE = 8 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
LogSeverity_descriptor();
template <typename T>
const std::string& LogSeverity_Name(T value) {
  static_assert(std::is_same<T, LogSeverity>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to LogSeverity_Name().");
  return LogSeverity_Name(static_cast<LogSeverity>(value));
}
template <>
inline const std::string& LogSeverity_Name(LogSeverity value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<LogSeverity_descriptor,
                                                 0, 8>(
      static_cast<int>(value));
}
inline bool LogSeverity_Parse(absl::string_view name, LogSeverity* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogSeverity>(
      LogSeverity_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Timestamp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vm_tools.Timestamp) */ {
 public:
  inline Timestamp() : Timestamp(nullptr) {}
  ~Timestamp() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Timestamp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Timestamp(const Timestamp& from);
  Timestamp(Timestamp&& from) noexcept
    : Timestamp() {
    *this = ::std::move(from);
  }

  inline Timestamp& operator=(const Timestamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline Timestamp& operator=(Timestamp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Timestamp& default_instance() {
    return *internal_default_instance();
  }
  static inline const Timestamp* internal_default_instance() {
    return reinterpret_cast<const Timestamp*>(
               &_Timestamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Timestamp& a, Timestamp& b) {
    a.Swap(&b);
  }
  inline void Swap(Timestamp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Timestamp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Timestamp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Timestamp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Timestamp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Timestamp& from) {
    Timestamp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Timestamp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.Timestamp";
  }
  protected:
  explicit Timestamp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSecondsFieldNumber = 1,
    kNanosFieldNumber = 2,
  };
  // int64 seconds = 1;
  void clear_seconds() ;
  ::int64_t seconds() const;
  void set_seconds(::int64_t value);

  private:
  ::int64_t _internal_seconds() const;
  void _internal_set_seconds(::int64_t value);

  public:
  // int32 nanos = 2;
  void clear_nanos() ;
  ::int32_t nanos() const;
  void set_nanos(::int32_t value);

  private:
  ::int32_t _internal_nanos() const;
  void _internal_set_nanos(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.Timestamp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::int64_t seconds_;
    ::int32_t nanos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fhost_2eproto;
};// -------------------------------------------------------------------

class LogRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vm_tools.LogRecord) */ {
 public:
  inline LogRecord() : LogRecord(nullptr) {}
  ~LogRecord() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LogRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogRecord(const LogRecord& from);
  LogRecord(LogRecord&& from) noexcept
    : LogRecord() {
    *this = ::std::move(from);
  }

  inline LogRecord& operator=(const LogRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogRecord& operator=(LogRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogRecord* internal_default_instance() {
    return reinterpret_cast<const LogRecord*>(
               &_LogRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LogRecord& a, LogRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(LogRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogRecord* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogRecord& from) {
    LogRecord::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.LogRecord";
  }
  protected:
  explicit LogRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 5,
    kTimestampFieldNumber = 2,
    kSeverityFieldNumber = 1,
  };
  // bytes content = 5;
  void clear_content() ;
  const std::string& content() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* ptr);

  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(
      const std::string& value);
  std::string* _internal_mutable_content();

  public:
  // .vm_tools.Timestamp timestamp = 2;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::vm_tools::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::vm_tools::Timestamp* release_timestamp();
  ::vm_tools::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::vm_tools::Timestamp* timestamp);
  private:
  const ::vm_tools::Timestamp& _internal_timestamp() const;
  ::vm_tools::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::vm_tools::Timestamp* timestamp);
  ::vm_tools::Timestamp* unsafe_arena_release_timestamp();
  // .vm_tools.LogSeverity severity = 1;
  void clear_severity() ;
  ::vm_tools::LogSeverity severity() const;
  void set_severity(::vm_tools::LogSeverity value);

  private:
  ::vm_tools::LogSeverity _internal_severity() const;
  void _internal_set_severity(::vm_tools::LogSeverity value);

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.LogRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    ::vm_tools::Timestamp* timestamp_;
    int severity_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fhost_2eproto;
};// -------------------------------------------------------------------

class LogRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vm_tools.LogRequest) */ {
 public:
  inline LogRequest() : LogRequest(nullptr) {}
  ~LogRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LogRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogRequest(const LogRequest& from);
  LogRequest(LogRequest&& from) noexcept
    : LogRequest() {
    *this = ::std::move(from);
  }

  inline LogRequest& operator=(const LogRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogRequest& operator=(LogRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogRequest* internal_default_instance() {
    return reinterpret_cast<const LogRequest*>(
               &_LogRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LogRequest& a, LogRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LogRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogRequest& from) {
    LogRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.LogRequest";
  }
  protected:
  explicit LogRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 1,
  };
  // repeated .vm_tools.LogRecord records = 1;
  int records_size() const;
  private:
  int _internal_records_size() const;

  public:
  void clear_records() ;
  ::vm_tools::LogRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >*
      mutable_records();
  private:
  const ::vm_tools::LogRecord& _internal_records(int index) const;
  ::vm_tools::LogRecord* _internal_add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>& _internal_records() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>* _internal_mutable_records();
  public:
  const ::vm_tools::LogRecord& records(int index) const;
  ::vm_tools::LogRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >&
      records() const;
  // @@protoc_insertion_point(class_scope:vm_tools.LogRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord > records_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fhost_2eproto;
};// -------------------------------------------------------------------

class VmInstallState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vm_tools.VmInstallState) */ {
 public:
  inline VmInstallState() : VmInstallState(nullptr) {}
  ~VmInstallState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VmInstallState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VmInstallState(const VmInstallState& from);
  VmInstallState(VmInstallState&& from) noexcept
    : VmInstallState() {
    *this = ::std::move(from);
  }

  inline VmInstallState& operator=(const VmInstallState& from) {
    CopyFrom(from);
    return *this;
  }
  inline VmInstallState& operator=(VmInstallState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VmInstallState& default_instance() {
    return *internal_default_instance();
  }
  static inline const VmInstallState* internal_default_instance() {
    return reinterpret_cast<const VmInstallState*>(
               &_VmInstallState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VmInstallState& a, VmInstallState& b) {
    a.Swap(&b);
  }
  inline void Swap(VmInstallState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VmInstallState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VmInstallState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VmInstallState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VmInstallState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VmInstallState& from) {
    VmInstallState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VmInstallState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.VmInstallState";
  }
  protected:
  explicit VmInstallState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using State = VmInstallState_State;
  static constexpr State UNKNOWN = VmInstallState_State_UNKNOWN;
  static constexpr State IN_PROGRESS = VmInstallState_State_IN_PROGRESS;
  static constexpr State FAILED = VmInstallState_State_FAILED;
  static constexpr State SUCCEEDED = VmInstallState_State_SUCCEEDED;
  static inline bool State_IsValid(int value) {
    return VmInstallState_State_IsValid(value);
  }
  static constexpr State State_MIN = VmInstallState_State_State_MIN;
  static constexpr State State_MAX = VmInstallState_State_State_MAX;
  static constexpr int State_ARRAYSIZE = VmInstallState_State_State_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* State_descriptor() {
    return VmInstallState_State_descriptor();
  }
  template <typename T>
  static inline const std::string& State_Name(T value) {
    return VmInstallState_State_Name(value);
  }
  static inline bool State_Parse(absl::string_view name, State* value) {
    return VmInstallState_State_Parse(name, value);
  }

  using Step = VmInstallState_Step;
  static constexpr Step unknown = VmInstallState_Step_unknown;
  static constexpr Step launcher_start = VmInstallState_Step_launcher_start;
  static constexpr Step core_start = VmInstallState_Step_core_start;
  static constexpr Step install_fetch_image = VmInstallState_Step_install_fetch_image;
  static constexpr Step install_configure = VmInstallState_Step_install_configure;
  static constexpr Step install_done = VmInstallState_Step_install_done;
  static constexpr Step install_success = VmInstallState_Step_install_success;
  static constexpr Step install_failure = VmInstallState_Step_install_failure;
  static inline bool Step_IsValid(int value) {
    return VmInstallState_Step_IsValid(value);
  }
  static constexpr Step Step_MIN = VmInstallState_Step_Step_MIN;
  static constexpr Step Step_MAX = VmInstallState_Step_Step_MAX;
  static constexpr int Step_ARRAYSIZE = VmInstallState_Step_Step_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Step_descriptor() {
    return VmInstallState_Step_descriptor();
  }
  template <typename T>
  static inline const std::string& Step_Name(T value) {
    return VmInstallState_Step_Name(value);
  }
  static inline bool Step_Parse(absl::string_view name, Step* value) {
    return VmInstallState_Step_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kFailedReasonFieldNumber = 4,
    kStateFieldNumber = 1,
    kInProgressStepFieldNumber = 2,
    kInProgressPercentFieldNumber = 3,
  };
  // string failed_reason = 4;
  void clear_failed_reason() ;
  const std::string& failed_reason() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_failed_reason(Arg_&& arg, Args_... args);
  std::string* mutable_failed_reason();
  PROTOBUF_NODISCARD std::string* release_failed_reason();
  void set_allocated_failed_reason(std::string* ptr);

  private:
  const std::string& _internal_failed_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_failed_reason(
      const std::string& value);
  std::string* _internal_mutable_failed_reason();

  public:
  // .vm_tools.VmInstallState.State state = 1;
  void clear_state() ;
  ::vm_tools::VmInstallState_State state() const;
  void set_state(::vm_tools::VmInstallState_State value);

  private:
  ::vm_tools::VmInstallState_State _internal_state() const;
  void _internal_set_state(::vm_tools::VmInstallState_State value);

  public:
  // .vm_tools.VmInstallState.Step in_progress_step = 2;
  void clear_in_progress_step() ;
  ::vm_tools::VmInstallState_Step in_progress_step() const;
  void set_in_progress_step(::vm_tools::VmInstallState_Step value);

  private:
  ::vm_tools::VmInstallState_Step _internal_in_progress_step() const;
  void _internal_set_in_progress_step(::vm_tools::VmInstallState_Step value);

  public:
  // int64 in_progress_percent = 3;
  void clear_in_progress_percent() ;
  ::int64_t in_progress_percent() const;
  void set_in_progress_percent(::int64_t value);

  private:
  ::int64_t _internal_in_progress_percent() const;
  void _internal_set_in_progress_percent(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.VmInstallState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr failed_reason_;
    int state_;
    int in_progress_step_;
    ::int64_t in_progress_percent_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fhost_2eproto;
};// -------------------------------------------------------------------

class VmKernelLogRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vm_tools.VmKernelLogRequest) */ {
 public:
  inline VmKernelLogRequest() : VmKernelLogRequest(nullptr) {}
  ~VmKernelLogRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VmKernelLogRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VmKernelLogRequest(const VmKernelLogRequest& from);
  VmKernelLogRequest(VmKernelLogRequest&& from) noexcept
    : VmKernelLogRequest() {
    *this = ::std::move(from);
  }

  inline VmKernelLogRequest& operator=(const VmKernelLogRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VmKernelLogRequest& operator=(VmKernelLogRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VmKernelLogRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VmKernelLogRequest* internal_default_instance() {
    return reinterpret_cast<const VmKernelLogRequest*>(
               &_VmKernelLogRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VmKernelLogRequest& a, VmKernelLogRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VmKernelLogRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VmKernelLogRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VmKernelLogRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VmKernelLogRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VmKernelLogRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VmKernelLogRequest& from) {
    VmKernelLogRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VmKernelLogRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "vm_tools.VmKernelLogRequest";
  }
  protected:
  explicit VmKernelLogRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using VmType = VmKernelLogRequest_VmType;
  static constexpr VmType UNKNOWN = VmKernelLogRequest_VmType_UNKNOWN;
  static constexpr VmType TERMINA = VmKernelLogRequest_VmType_TERMINA;
  static constexpr VmType ARC_VM = VmKernelLogRequest_VmType_ARC_VM;
  static constexpr VmType PLUGIN_VM = VmKernelLogRequest_VmType_PLUGIN_VM;
  static constexpr VmType BOREALIS = VmKernelLogRequest_VmType_BOREALIS;
  static constexpr VmType BRUSCHETTA = VmKernelLogRequest_VmType_BRUSCHETTA;
  static constexpr VmType BAGUETTE = VmKernelLogRequest_VmType_BAGUETTE;
  static inline bool VmType_IsValid(int value) {
    return VmKernelLogRequest_VmType_IsValid(value);
  }
  static constexpr VmType VmType_MIN = VmKernelLogRequest_VmType_VmType_MIN;
  static constexpr VmType VmType_MAX = VmKernelLogRequest_VmType_VmType_MAX;
  static constexpr int VmType_ARRAYSIZE = VmKernelLogRequest_VmType_VmType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* VmType_descriptor() {
    return VmKernelLogRequest_VmType_descriptor();
  }
  template <typename T>
  static inline const std::string& VmType_Name(T value) {
    return VmKernelLogRequest_VmType_Name(value);
  }
  static inline bool VmType_Parse(absl::string_view name, VmType* value) {
    return VmKernelLogRequest_VmType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 3,
    kVmTypeFieldNumber = 1,
    kCidFieldNumber = 2,
  };
  // repeated .vm_tools.LogRecord records = 3;
  int records_size() const;
  private:
  int _internal_records_size() const;

  public:
  void clear_records() ;
  ::vm_tools::LogRecord* mutable_records(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >*
      mutable_records();
  private:
  const ::vm_tools::LogRecord& _internal_records(int index) const;
  ::vm_tools::LogRecord* _internal_add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>& _internal_records() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>* _internal_mutable_records();
  public:
  const ::vm_tools::LogRecord& records(int index) const;
  ::vm_tools::LogRecord* add_records();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >&
      records() const;
  // .vm_tools.VmKernelLogRequest.VmType vm_type = 1;
  void clear_vm_type() ;
  ::vm_tools::VmKernelLogRequest_VmType vm_type() const;
  void set_vm_type(::vm_tools::VmKernelLogRequest_VmType value);

  private:
  ::vm_tools::VmKernelLogRequest_VmType _internal_vm_type() const;
  void _internal_set_vm_type(::vm_tools::VmKernelLogRequest_VmType value);

  public:
  // int32 cid = 2;
  void clear_cid() ;
  ::int32_t cid() const;
  void set_cid(::int32_t value);

  private:
  ::int32_t _internal_cid() const;
  void _internal_set_cid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:vm_tools.VmKernelLogRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord > records_;
    int vm_type_;
    ::int32_t cid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vm_5fhost_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Timestamp

// int64 seconds = 1;
inline void Timestamp::clear_seconds() {
  _impl_.seconds_ = ::int64_t{0};
}
inline ::int64_t Timestamp::seconds() const {
  // @@protoc_insertion_point(field_get:vm_tools.Timestamp.seconds)
  return _internal_seconds();
}
inline void Timestamp::set_seconds(::int64_t value) {
  _internal_set_seconds(value);
  // @@protoc_insertion_point(field_set:vm_tools.Timestamp.seconds)
}
inline ::int64_t Timestamp::_internal_seconds() const {
  return _impl_.seconds_;
}
inline void Timestamp::_internal_set_seconds(::int64_t value) {
  ;
  _impl_.seconds_ = value;
}

// int32 nanos = 2;
inline void Timestamp::clear_nanos() {
  _impl_.nanos_ = 0;
}
inline ::int32_t Timestamp::nanos() const {
  // @@protoc_insertion_point(field_get:vm_tools.Timestamp.nanos)
  return _internal_nanos();
}
inline void Timestamp::set_nanos(::int32_t value) {
  _internal_set_nanos(value);
  // @@protoc_insertion_point(field_set:vm_tools.Timestamp.nanos)
}
inline ::int32_t Timestamp::_internal_nanos() const {
  return _impl_.nanos_;
}
inline void Timestamp::_internal_set_nanos(::int32_t value) {
  ;
  _impl_.nanos_ = value;
}

// -------------------------------------------------------------------

// LogRecord

// .vm_tools.LogSeverity severity = 1;
inline void LogRecord::clear_severity() {
  _impl_.severity_ = 0;
}
inline ::vm_tools::LogSeverity LogRecord::severity() const {
  // @@protoc_insertion_point(field_get:vm_tools.LogRecord.severity)
  return _internal_severity();
}
inline void LogRecord::set_severity(::vm_tools::LogSeverity value) {
   _internal_set_severity(value);
  // @@protoc_insertion_point(field_set:vm_tools.LogRecord.severity)
}
inline ::vm_tools::LogSeverity LogRecord::_internal_severity() const {
  return static_cast<::vm_tools::LogSeverity>(_impl_.severity_);
}
inline void LogRecord::_internal_set_severity(::vm_tools::LogSeverity value) {
  ;
  _impl_.severity_ = value;
}

// .vm_tools.Timestamp timestamp = 2;
inline bool LogRecord::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline void LogRecord::clear_timestamp() {
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::vm_tools::Timestamp& LogRecord::_internal_timestamp() const {
  const ::vm_tools::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::vm_tools::Timestamp&>(
      ::vm_tools::_Timestamp_default_instance_);
}
inline const ::vm_tools::Timestamp& LogRecord::timestamp() const {
  // @@protoc_insertion_point(field_get:vm_tools.LogRecord.timestamp)
  return _internal_timestamp();
}
inline void LogRecord::unsafe_arena_set_allocated_timestamp(
    ::vm_tools::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = timestamp;
  if (timestamp) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:vm_tools.LogRecord.timestamp)
}
inline ::vm_tools::Timestamp* LogRecord::release_timestamp() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::vm_tools::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vm_tools::Timestamp* LogRecord::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:vm_tools.LogRecord.timestamp)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::vm_tools::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::vm_tools::Timestamp* LogRecord::_internal_mutable_timestamp() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::vm_tools::Timestamp>(GetArenaForAllocation());
    _impl_.timestamp_ = p;
  }
  return _impl_.timestamp_;
}
inline ::vm_tools::Timestamp* LogRecord::mutable_timestamp() {
  ::vm_tools::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:vm_tools.LogRecord.timestamp)
  return _msg;
}
inline void LogRecord::set_allocated_timestamp(::vm_tools::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.timestamp_;
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(timestamp);
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:vm_tools.LogRecord.timestamp)
}

// bytes content = 5;
inline void LogRecord::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& LogRecord::content() const {
  // @@protoc_insertion_point(field_get:vm_tools.LogRecord.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LogRecord::set_content(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.LogRecord.content)
}
inline std::string* LogRecord::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:vm_tools.LogRecord.content)
  return _s;
}
inline const std::string& LogRecord::_internal_content() const {
  return _impl_.content_.Get();
}
inline void LogRecord::_internal_set_content(const std::string& value) {
  ;


  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* LogRecord::_internal_mutable_content() {
  ;
  return _impl_.content_.Mutable( GetArenaForAllocation());
}
inline std::string* LogRecord::release_content() {
  // @@protoc_insertion_point(field_release:vm_tools.LogRecord.content)
  return _impl_.content_.Release();
}
inline void LogRecord::set_allocated_content(std::string* value) {
  _impl_.content_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.content_.IsDefault()) {
          _impl_.content_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.LogRecord.content)
}

// -------------------------------------------------------------------

// LogRequest

// repeated .vm_tools.LogRecord records = 1;
inline int LogRequest::_internal_records_size() const {
  return _impl_.records_.size();
}
inline int LogRequest::records_size() const {
  return _internal_records_size();
}
inline void LogRequest::clear_records() {
  _internal_mutable_records()->Clear();
}
inline ::vm_tools::LogRecord* LogRequest::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:vm_tools.LogRequest.records)
  return _internal_mutable_records()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >*
LogRequest::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:vm_tools.LogRequest.records)
  return _internal_mutable_records();
}
inline const ::vm_tools::LogRecord& LogRequest::_internal_records(int index) const {
  return _internal_records().Get(index);
}
inline const ::vm_tools::LogRecord& LogRequest::records(int index) const {
  // @@protoc_insertion_point(field_get:vm_tools.LogRequest.records)
  return _internal_records(index);
}
inline ::vm_tools::LogRecord* LogRequest::_internal_add_records() {
  return _internal_mutable_records()->Add();
}
inline ::vm_tools::LogRecord* LogRequest::add_records() {
  ::vm_tools::LogRecord* _add = _internal_add_records();
  // @@protoc_insertion_point(field_add:vm_tools.LogRequest.records)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >&
LogRequest::records() const {
  // @@protoc_insertion_point(field_list:vm_tools.LogRequest.records)
  return _internal_records();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>&
LogRequest::_internal_records() const {
  return _impl_.records_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>*
LogRequest::_internal_mutable_records() {
  return &_impl_.records_;
}

// -------------------------------------------------------------------

// VmInstallState

// .vm_tools.VmInstallState.State state = 1;
inline void VmInstallState::clear_state() {
  _impl_.state_ = 0;
}
inline ::vm_tools::VmInstallState_State VmInstallState::state() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmInstallState.state)
  return _internal_state();
}
inline void VmInstallState::set_state(::vm_tools::VmInstallState_State value) {
   _internal_set_state(value);
  // @@protoc_insertion_point(field_set:vm_tools.VmInstallState.state)
}
inline ::vm_tools::VmInstallState_State VmInstallState::_internal_state() const {
  return static_cast<::vm_tools::VmInstallState_State>(_impl_.state_);
}
inline void VmInstallState::_internal_set_state(::vm_tools::VmInstallState_State value) {
  ;
  _impl_.state_ = value;
}

// .vm_tools.VmInstallState.Step in_progress_step = 2;
inline void VmInstallState::clear_in_progress_step() {
  _impl_.in_progress_step_ = 0;
}
inline ::vm_tools::VmInstallState_Step VmInstallState::in_progress_step() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmInstallState.in_progress_step)
  return _internal_in_progress_step();
}
inline void VmInstallState::set_in_progress_step(::vm_tools::VmInstallState_Step value) {
   _internal_set_in_progress_step(value);
  // @@protoc_insertion_point(field_set:vm_tools.VmInstallState.in_progress_step)
}
inline ::vm_tools::VmInstallState_Step VmInstallState::_internal_in_progress_step() const {
  return static_cast<::vm_tools::VmInstallState_Step>(_impl_.in_progress_step_);
}
inline void VmInstallState::_internal_set_in_progress_step(::vm_tools::VmInstallState_Step value) {
  ;
  _impl_.in_progress_step_ = value;
}

// int64 in_progress_percent = 3;
inline void VmInstallState::clear_in_progress_percent() {
  _impl_.in_progress_percent_ = ::int64_t{0};
}
inline ::int64_t VmInstallState::in_progress_percent() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmInstallState.in_progress_percent)
  return _internal_in_progress_percent();
}
inline void VmInstallState::set_in_progress_percent(::int64_t value) {
  _internal_set_in_progress_percent(value);
  // @@protoc_insertion_point(field_set:vm_tools.VmInstallState.in_progress_percent)
}
inline ::int64_t VmInstallState::_internal_in_progress_percent() const {
  return _impl_.in_progress_percent_;
}
inline void VmInstallState::_internal_set_in_progress_percent(::int64_t value) {
  ;
  _impl_.in_progress_percent_ = value;
}

// string failed_reason = 4;
inline void VmInstallState::clear_failed_reason() {
  _impl_.failed_reason_.ClearToEmpty();
}
inline const std::string& VmInstallState::failed_reason() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmInstallState.failed_reason)
  return _internal_failed_reason();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VmInstallState::set_failed_reason(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.failed_reason_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vm_tools.VmInstallState.failed_reason)
}
inline std::string* VmInstallState::mutable_failed_reason() {
  std::string* _s = _internal_mutable_failed_reason();
  // @@protoc_insertion_point(field_mutable:vm_tools.VmInstallState.failed_reason)
  return _s;
}
inline const std::string& VmInstallState::_internal_failed_reason() const {
  return _impl_.failed_reason_.Get();
}
inline void VmInstallState::_internal_set_failed_reason(const std::string& value) {
  ;


  _impl_.failed_reason_.Set(value, GetArenaForAllocation());
}
inline std::string* VmInstallState::_internal_mutable_failed_reason() {
  ;
  return _impl_.failed_reason_.Mutable( GetArenaForAllocation());
}
inline std::string* VmInstallState::release_failed_reason() {
  // @@protoc_insertion_point(field_release:vm_tools.VmInstallState.failed_reason)
  return _impl_.failed_reason_.Release();
}
inline void VmInstallState::set_allocated_failed_reason(std::string* value) {
  _impl_.failed_reason_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.failed_reason_.IsDefault()) {
          _impl_.failed_reason_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vm_tools.VmInstallState.failed_reason)
}

// -------------------------------------------------------------------

// VmKernelLogRequest

// .vm_tools.VmKernelLogRequest.VmType vm_type = 1;
inline void VmKernelLogRequest::clear_vm_type() {
  _impl_.vm_type_ = 0;
}
inline ::vm_tools::VmKernelLogRequest_VmType VmKernelLogRequest::vm_type() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmKernelLogRequest.vm_type)
  return _internal_vm_type();
}
inline void VmKernelLogRequest::set_vm_type(::vm_tools::VmKernelLogRequest_VmType value) {
   _internal_set_vm_type(value);
  // @@protoc_insertion_point(field_set:vm_tools.VmKernelLogRequest.vm_type)
}
inline ::vm_tools::VmKernelLogRequest_VmType VmKernelLogRequest::_internal_vm_type() const {
  return static_cast<::vm_tools::VmKernelLogRequest_VmType>(_impl_.vm_type_);
}
inline void VmKernelLogRequest::_internal_set_vm_type(::vm_tools::VmKernelLogRequest_VmType value) {
  ;
  _impl_.vm_type_ = value;
}

// int32 cid = 2;
inline void VmKernelLogRequest::clear_cid() {
  _impl_.cid_ = 0;
}
inline ::int32_t VmKernelLogRequest::cid() const {
  // @@protoc_insertion_point(field_get:vm_tools.VmKernelLogRequest.cid)
  return _internal_cid();
}
inline void VmKernelLogRequest::set_cid(::int32_t value) {
  _internal_set_cid(value);
  // @@protoc_insertion_point(field_set:vm_tools.VmKernelLogRequest.cid)
}
inline ::int32_t VmKernelLogRequest::_internal_cid() const {
  return _impl_.cid_;
}
inline void VmKernelLogRequest::_internal_set_cid(::int32_t value) {
  ;
  _impl_.cid_ = value;
}

// repeated .vm_tools.LogRecord records = 3;
inline int VmKernelLogRequest::_internal_records_size() const {
  return _impl_.records_.size();
}
inline int VmKernelLogRequest::records_size() const {
  return _internal_records_size();
}
inline void VmKernelLogRequest::clear_records() {
  _internal_mutable_records()->Clear();
}
inline ::vm_tools::LogRecord* VmKernelLogRequest::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:vm_tools.VmKernelLogRequest.records)
  return _internal_mutable_records()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >*
VmKernelLogRequest::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:vm_tools.VmKernelLogRequest.records)
  return _internal_mutable_records();
}
inline const ::vm_tools::LogRecord& VmKernelLogRequest::_internal_records(int index) const {
  return _internal_records().Get(index);
}
inline const ::vm_tools::LogRecord& VmKernelLogRequest::records(int index) const {
  // @@protoc_insertion_point(field_get:vm_tools.VmKernelLogRequest.records)
  return _internal_records(index);
}
inline ::vm_tools::LogRecord* VmKernelLogRequest::_internal_add_records() {
  return _internal_mutable_records()->Add();
}
inline ::vm_tools::LogRecord* VmKernelLogRequest::add_records() {
  ::vm_tools::LogRecord* _add = _internal_add_records();
  // @@protoc_insertion_point(field_add:vm_tools.VmKernelLogRequest.records)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vm_tools::LogRecord >&
VmKernelLogRequest::records() const {
  // @@protoc_insertion_point(field_list:vm_tools.VmKernelLogRequest.records)
  return _internal_records();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>&
VmKernelLogRequest::_internal_records() const {
  return _impl_.records_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::vm_tools::LogRecord>*
VmKernelLogRequest::_internal_mutable_records() {
  return &_impl_.records_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace vm_tools


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::vm_tools::VmInstallState_State> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::vm_tools::VmInstallState_State>() {
  return ::vm_tools::VmInstallState_State_descriptor();
}
template <>
struct is_proto_enum<::vm_tools::VmInstallState_Step> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::vm_tools::VmInstallState_Step>() {
  return ::vm_tools::VmInstallState_Step_descriptor();
}
template <>
struct is_proto_enum<::vm_tools::VmKernelLogRequest_VmType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::vm_tools::VmKernelLogRequest_VmType>() {
  return ::vm_tools::VmKernelLogRequest_VmType_descriptor();
}
template <>
struct is_proto_enum<::vm_tools::LogSeverity> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::vm_tools::LogSeverity>() {
  return ::vm_tools::LogSeverity_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_vm_5fhost_2eproto_2epb_2eh
