// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ck_structs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ck_5fstructs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ck_5fstructs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ck_5fstructs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ck_5fstructs_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace chaps {
class MechanismInfo;
struct MechanismInfoDefaultTypeInternal;
extern MechanismInfoDefaultTypeInternal _MechanismInfo_default_instance_;
class SessionInfo;
struct SessionInfoDefaultTypeInternal;
extern SessionInfoDefaultTypeInternal _SessionInfo_default_instance_;
class SlotInfo;
struct SlotInfoDefaultTypeInternal;
extern SlotInfoDefaultTypeInternal _SlotInfo_default_instance_;
class TokenInfo;
struct TokenInfoDefaultTypeInternal;
extern TokenInfoDefaultTypeInternal _TokenInfo_default_instance_;
class Version;
struct VersionDefaultTypeInternal;
extern VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace chaps
PROTOBUF_NAMESPACE_OPEN
template<> ::chaps::MechanismInfo* Arena::CreateMaybeMessage<::chaps::MechanismInfo>(Arena*);
template<> ::chaps::SessionInfo* Arena::CreateMaybeMessage<::chaps::SessionInfo>(Arena*);
template<> ::chaps::SlotInfo* Arena::CreateMaybeMessage<::chaps::SlotInfo>(Arena*);
template<> ::chaps::TokenInfo* Arena::CreateMaybeMessage<::chaps::TokenInfo>(Arena*);
template<> ::chaps::Version* Arena::CreateMaybeMessage<::chaps::Version>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chaps {

// ===================================================================

class MechanismInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chaps.MechanismInfo) */ {
 public:
  inline MechanismInfo() : MechanismInfo(nullptr) {}
  ~MechanismInfo() override;
  explicit constexpr MechanismInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MechanismInfo(const MechanismInfo& from);
  MechanismInfo(MechanismInfo&& from) noexcept
    : MechanismInfo() {
    *this = ::std::move(from);
  }

  inline MechanismInfo& operator=(const MechanismInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline MechanismInfo& operator=(MechanismInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const MechanismInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const MechanismInfo* internal_default_instance() {
    return reinterpret_cast<const MechanismInfo*>(
               &_MechanismInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MechanismInfo& a, MechanismInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(MechanismInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MechanismInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MechanismInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MechanismInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const MechanismInfo& from);
  void MergeFrom(const MechanismInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MechanismInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chaps.MechanismInfo";
  }
  protected:
  explicit MechanismInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMinKeySizeFieldNumber = 1,
    kMaxKeySizeFieldNumber = 2,
    kFlagsFieldNumber = 3,
  };
  // optional uint64 min_key_size = 1;
  bool has_min_key_size() const;
  private:
  bool _internal_has_min_key_size() const;
  public:
  void clear_min_key_size();
  uint64_t min_key_size() const;
  void set_min_key_size(uint64_t value);
  private:
  uint64_t _internal_min_key_size() const;
  void _internal_set_min_key_size(uint64_t value);
  public:

  // optional uint64 max_key_size = 2;
  bool has_max_key_size() const;
  private:
  bool _internal_has_max_key_size() const;
  public:
  void clear_max_key_size();
  uint64_t max_key_size() const;
  void set_max_key_size(uint64_t value);
  private:
  uint64_t _internal_max_key_size() const;
  void _internal_set_max_key_size(uint64_t value);
  public:

  // optional uint64 flags = 3;
  bool has_flags() const;
  private:
  bool _internal_has_flags() const;
  public:
  void clear_flags();
  uint64_t flags() const;
  void set_flags(uint64_t value);
  private:
  uint64_t _internal_flags() const;
  void _internal_set_flags(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:chaps.MechanismInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint64_t min_key_size_;
  uint64_t max_key_size_;
  uint64_t flags_;
  friend struct ::TableStruct_ck_5fstructs_2eproto;
};
// -------------------------------------------------------------------

class SessionInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chaps.SessionInfo) */ {
 public:
  inline SessionInfo() : SessionInfo(nullptr) {}
  ~SessionInfo() override;
  explicit constexpr SessionInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SessionInfo(const SessionInfo& from);
  SessionInfo(SessionInfo&& from) noexcept
    : SessionInfo() {
    *this = ::std::move(from);
  }

  inline SessionInfo& operator=(const SessionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionInfo& operator=(SessionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const SessionInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionInfo* internal_default_instance() {
    return reinterpret_cast<const SessionInfo*>(
               &_SessionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SessionInfo& a, SessionInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SessionInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SessionInfo& from);
  void MergeFrom(const SessionInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SessionInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chaps.SessionInfo";
  }
  protected:
  explicit SessionInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSlotIdFieldNumber = 1,
    kStateFieldNumber = 2,
    kFlagsFieldNumber = 3,
    kDeviceErrorFieldNumber = 4,
  };
  // optional uint64 slot_id = 1;
  bool has_slot_id() const;
  private:
  bool _internal_has_slot_id() const;
  public:
  void clear_slot_id();
  uint64_t slot_id() const;
  void set_slot_id(uint64_t value);
  private:
  uint64_t _internal_slot_id() const;
  void _internal_set_slot_id(uint64_t value);
  public:

  // optional uint64 state = 2;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  uint64_t state() const;
  void set_state(uint64_t value);
  private:
  uint64_t _internal_state() const;
  void _internal_set_state(uint64_t value);
  public:

  // optional uint64 flags = 3;
  bool has_flags() const;
  private:
  bool _internal_has_flags() const;
  public:
  void clear_flags();
  uint64_t flags() const;
  void set_flags(uint64_t value);
  private:
  uint64_t _internal_flags() const;
  void _internal_set_flags(uint64_t value);
  public:

  // optional uint64 device_error = 4;
  bool has_device_error() const;
  private:
  bool _internal_has_device_error() const;
  public:
  void clear_device_error();
  uint64_t device_error() const;
  void set_device_error(uint64_t value);
  private:
  uint64_t _internal_device_error() const;
  void _internal_set_device_error(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:chaps.SessionInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint64_t slot_id_;
  uint64_t state_;
  uint64_t flags_;
  uint64_t device_error_;
  friend struct ::TableStruct_ck_5fstructs_2eproto;
};
// -------------------------------------------------------------------

class Version final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chaps.Version) */ {
 public:
  inline Version() : Version(nullptr) {}
  ~Version() override;
  explicit constexpr Version(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Version(const Version& from);
  Version(Version&& from) noexcept
    : Version() {
    *this = ::std::move(from);
  }

  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  inline Version& operator=(Version&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Version& default_instance() {
    return *internal_default_instance();
  }
  static inline const Version* internal_default_instance() {
    return reinterpret_cast<const Version*>(
               &_Version_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Version& a, Version& b) {
    a.Swap(&b);
  }
  inline void Swap(Version* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Version* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Version* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Version>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Version* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chaps.Version";
  }
  protected:
  explicit Version(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMajorFieldNumber = 1,
    kMinorFieldNumber = 2,
  };
  // optional uint32 major = 1;
  bool has_major() const;
  private:
  bool _internal_has_major() const;
  public:
  void clear_major();
  uint32_t major() const;
  void set_major(uint32_t value);
  private:
  uint32_t _internal_major() const;
  void _internal_set_major(uint32_t value);
  public:

  // optional uint32 minor = 2;
  bool has_minor() const;
  private:
  bool _internal_has_minor() const;
  public:
  void clear_minor();
  uint32_t minor() const;
  void set_minor(uint32_t value);
  private:
  uint32_t _internal_minor() const;
  void _internal_set_minor(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chaps.Version)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t major_;
  uint32_t minor_;
  friend struct ::TableStruct_ck_5fstructs_2eproto;
};
// -------------------------------------------------------------------

class SlotInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chaps.SlotInfo) */ {
 public:
  inline SlotInfo() : SlotInfo(nullptr) {}
  ~SlotInfo() override;
  explicit constexpr SlotInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SlotInfo(const SlotInfo& from);
  SlotInfo(SlotInfo&& from) noexcept
    : SlotInfo() {
    *this = ::std::move(from);
  }

  inline SlotInfo& operator=(const SlotInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SlotInfo& operator=(SlotInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const SlotInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const SlotInfo* internal_default_instance() {
    return reinterpret_cast<const SlotInfo*>(
               &_SlotInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SlotInfo& a, SlotInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(SlotInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SlotInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SlotInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SlotInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SlotInfo& from);
  void MergeFrom(const SlotInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SlotInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chaps.SlotInfo";
  }
  protected:
  explicit SlotInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSlotDescriptionFieldNumber = 1,
    kManufacturerIdFieldNumber = 2,
    kHardwareVersionFieldNumber = 4,
    kFirmwareVersionFieldNumber = 5,
    kFlagsFieldNumber = 3,
  };
  // optional bytes slot_description = 1;
  bool has_slot_description() const;
  private:
  bool _internal_has_slot_description() const;
  public:
  void clear_slot_description();
  const std::string& slot_description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_slot_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_slot_description();
  PROTOBUF_NODISCARD std::string* release_slot_description();
  void set_allocated_slot_description(std::string* slot_description);
  private:
  const std::string& _internal_slot_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_slot_description(const std::string& value);
  std::string* _internal_mutable_slot_description();
  public:

  // optional bytes manufacturer_id = 2;
  bool has_manufacturer_id() const;
  private:
  bool _internal_has_manufacturer_id() const;
  public:
  void clear_manufacturer_id();
  const std::string& manufacturer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_manufacturer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_manufacturer_id();
  PROTOBUF_NODISCARD std::string* release_manufacturer_id();
  void set_allocated_manufacturer_id(std::string* manufacturer_id);
  private:
  const std::string& _internal_manufacturer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_manufacturer_id(const std::string& value);
  std::string* _internal_mutable_manufacturer_id();
  public:

  // optional .chaps.Version hardware_version = 4;
  bool has_hardware_version() const;
  private:
  bool _internal_has_hardware_version() const;
  public:
  void clear_hardware_version();
  const ::chaps::Version& hardware_version() const;
  PROTOBUF_NODISCARD ::chaps::Version* release_hardware_version();
  ::chaps::Version* mutable_hardware_version();
  void set_allocated_hardware_version(::chaps::Version* hardware_version);
  private:
  const ::chaps::Version& _internal_hardware_version() const;
  ::chaps::Version* _internal_mutable_hardware_version();
  public:
  void unsafe_arena_set_allocated_hardware_version(
      ::chaps::Version* hardware_version);
  ::chaps::Version* unsafe_arena_release_hardware_version();

  // optional .chaps.Version firmware_version = 5;
  bool has_firmware_version() const;
  private:
  bool _internal_has_firmware_version() const;
  public:
  void clear_firmware_version();
  const ::chaps::Version& firmware_version() const;
  PROTOBUF_NODISCARD ::chaps::Version* release_firmware_version();
  ::chaps::Version* mutable_firmware_version();
  void set_allocated_firmware_version(::chaps::Version* firmware_version);
  private:
  const ::chaps::Version& _internal_firmware_version() const;
  ::chaps::Version* _internal_mutable_firmware_version();
  public:
  void unsafe_arena_set_allocated_firmware_version(
      ::chaps::Version* firmware_version);
  ::chaps::Version* unsafe_arena_release_firmware_version();

  // optional uint64 flags = 3;
  bool has_flags() const;
  private:
  bool _internal_has_flags() const;
  public:
  void clear_flags();
  uint64_t flags() const;
  void set_flags(uint64_t value);
  private:
  uint64_t _internal_flags() const;
  void _internal_set_flags(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:chaps.SlotInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr slot_description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr manufacturer_id_;
  ::chaps::Version* hardware_version_;
  ::chaps::Version* firmware_version_;
  uint64_t flags_;
  friend struct ::TableStruct_ck_5fstructs_2eproto;
};
// -------------------------------------------------------------------

class TokenInfo final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:chaps.TokenInfo) */ {
 public:
  inline TokenInfo() : TokenInfo(nullptr) {}
  ~TokenInfo() override;
  explicit constexpr TokenInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TokenInfo(const TokenInfo& from);
  TokenInfo(TokenInfo&& from) noexcept
    : TokenInfo() {
    *this = ::std::move(from);
  }

  inline TokenInfo& operator=(const TokenInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TokenInfo& operator=(TokenInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const TokenInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const TokenInfo* internal_default_instance() {
    return reinterpret_cast<const TokenInfo*>(
               &_TokenInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TokenInfo& a, TokenInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(TokenInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TokenInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TokenInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TokenInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const TokenInfo& from);
  void MergeFrom(const TokenInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TokenInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chaps.TokenInfo";
  }
  protected:
  explicit TokenInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLabelFieldNumber = 1,
    kManufacturerIdFieldNumber = 2,
    kModelFieldNumber = 3,
    kSerialNumberFieldNumber = 4,
    kHardwareVersionFieldNumber = 16,
    kFirmwareVersionFieldNumber = 17,
    kFlagsFieldNumber = 5,
    kMaxSessionCountFieldNumber = 6,
    kSessionCountFieldNumber = 7,
    kMaxSessionCountRwFieldNumber = 8,
    kSessionCountRwFieldNumber = 9,
    kMaxPinLenFieldNumber = 10,
    kMinPinLenFieldNumber = 11,
    kTotalPublicMemoryFieldNumber = 12,
    kFreePublicMemoryFieldNumber = 13,
    kTotalPrivateMemoryFieldNumber = 14,
    kFreePrivateMemoryFieldNumber = 15,
  };
  // optional bytes label = 1;
  bool has_label() const;
  private:
  bool _internal_has_label() const;
  public:
  void clear_label();
  const std::string& label() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_label(ArgT0&& arg0, ArgT... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* label);
  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(const std::string& value);
  std::string* _internal_mutable_label();
  public:

  // optional bytes manufacturer_id = 2;
  bool has_manufacturer_id() const;
  private:
  bool _internal_has_manufacturer_id() const;
  public:
  void clear_manufacturer_id();
  const std::string& manufacturer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_manufacturer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_manufacturer_id();
  PROTOBUF_NODISCARD std::string* release_manufacturer_id();
  void set_allocated_manufacturer_id(std::string* manufacturer_id);
  private:
  const std::string& _internal_manufacturer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_manufacturer_id(const std::string& value);
  std::string* _internal_mutable_manufacturer_id();
  public:

  // optional bytes model = 3;
  bool has_model() const;
  private:
  bool _internal_has_model() const;
  public:
  void clear_model();
  const std::string& model() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_model(ArgT0&& arg0, ArgT... args);
  std::string* mutable_model();
  PROTOBUF_NODISCARD std::string* release_model();
  void set_allocated_model(std::string* model);
  private:
  const std::string& _internal_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model(const std::string& value);
  std::string* _internal_mutable_model();
  public:

  // optional bytes serial_number = 4;
  bool has_serial_number() const;
  private:
  bool _internal_has_serial_number() const;
  public:
  void clear_serial_number();
  const std::string& serial_number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serial_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serial_number();
  PROTOBUF_NODISCARD std::string* release_serial_number();
  void set_allocated_serial_number(std::string* serial_number);
  private:
  const std::string& _internal_serial_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serial_number(const std::string& value);
  std::string* _internal_mutable_serial_number();
  public:

  // optional .chaps.Version hardware_version = 16;
  bool has_hardware_version() const;
  private:
  bool _internal_has_hardware_version() const;
  public:
  void clear_hardware_version();
  const ::chaps::Version& hardware_version() const;
  PROTOBUF_NODISCARD ::chaps::Version* release_hardware_version();
  ::chaps::Version* mutable_hardware_version();
  void set_allocated_hardware_version(::chaps::Version* hardware_version);
  private:
  const ::chaps::Version& _internal_hardware_version() const;
  ::chaps::Version* _internal_mutable_hardware_version();
  public:
  void unsafe_arena_set_allocated_hardware_version(
      ::chaps::Version* hardware_version);
  ::chaps::Version* unsafe_arena_release_hardware_version();

  // optional .chaps.Version firmware_version = 17;
  bool has_firmware_version() const;
  private:
  bool _internal_has_firmware_version() const;
  public:
  void clear_firmware_version();
  const ::chaps::Version& firmware_version() const;
  PROTOBUF_NODISCARD ::chaps::Version* release_firmware_version();
  ::chaps::Version* mutable_firmware_version();
  void set_allocated_firmware_version(::chaps::Version* firmware_version);
  private:
  const ::chaps::Version& _internal_firmware_version() const;
  ::chaps::Version* _internal_mutable_firmware_version();
  public:
  void unsafe_arena_set_allocated_firmware_version(
      ::chaps::Version* firmware_version);
  ::chaps::Version* unsafe_arena_release_firmware_version();

  // optional uint64 flags = 5;
  bool has_flags() const;
  private:
  bool _internal_has_flags() const;
  public:
  void clear_flags();
  uint64_t flags() const;
  void set_flags(uint64_t value);
  private:
  uint64_t _internal_flags() const;
  void _internal_set_flags(uint64_t value);
  public:

  // optional uint64 max_session_count = 6;
  bool has_max_session_count() const;
  private:
  bool _internal_has_max_session_count() const;
  public:
  void clear_max_session_count();
  uint64_t max_session_count() const;
  void set_max_session_count(uint64_t value);
  private:
  uint64_t _internal_max_session_count() const;
  void _internal_set_max_session_count(uint64_t value);
  public:

  // optional uint64 session_count = 7;
  bool has_session_count() const;
  private:
  bool _internal_has_session_count() const;
  public:
  void clear_session_count();
  uint64_t session_count() const;
  void set_session_count(uint64_t value);
  private:
  uint64_t _internal_session_count() const;
  void _internal_set_session_count(uint64_t value);
  public:

  // optional uint64 max_session_count_rw = 8;
  bool has_max_session_count_rw() const;
  private:
  bool _internal_has_max_session_count_rw() const;
  public:
  void clear_max_session_count_rw();
  uint64_t max_session_count_rw() const;
  void set_max_session_count_rw(uint64_t value);
  private:
  uint64_t _internal_max_session_count_rw() const;
  void _internal_set_max_session_count_rw(uint64_t value);
  public:

  // optional uint64 session_count_rw = 9;
  bool has_session_count_rw() const;
  private:
  bool _internal_has_session_count_rw() const;
  public:
  void clear_session_count_rw();
  uint64_t session_count_rw() const;
  void set_session_count_rw(uint64_t value);
  private:
  uint64_t _internal_session_count_rw() const;
  void _internal_set_session_count_rw(uint64_t value);
  public:

  // optional uint64 max_pin_len = 10;
  bool has_max_pin_len() const;
  private:
  bool _internal_has_max_pin_len() const;
  public:
  void clear_max_pin_len();
  uint64_t max_pin_len() const;
  void set_max_pin_len(uint64_t value);
  private:
  uint64_t _internal_max_pin_len() const;
  void _internal_set_max_pin_len(uint64_t value);
  public:

  // optional uint64 min_pin_len = 11;
  bool has_min_pin_len() const;
  private:
  bool _internal_has_min_pin_len() const;
  public:
  void clear_min_pin_len();
  uint64_t min_pin_len() const;
  void set_min_pin_len(uint64_t value);
  private:
  uint64_t _internal_min_pin_len() const;
  void _internal_set_min_pin_len(uint64_t value);
  public:

  // optional uint64 total_public_memory = 12;
  bool has_total_public_memory() const;
  private:
  bool _internal_has_total_public_memory() const;
  public:
  void clear_total_public_memory();
  uint64_t total_public_memory() const;
  void set_total_public_memory(uint64_t value);
  private:
  uint64_t _internal_total_public_memory() const;
  void _internal_set_total_public_memory(uint64_t value);
  public:

  // optional uint64 free_public_memory = 13;
  bool has_free_public_memory() const;
  private:
  bool _internal_has_free_public_memory() const;
  public:
  void clear_free_public_memory();
  uint64_t free_public_memory() const;
  void set_free_public_memory(uint64_t value);
  private:
  uint64_t _internal_free_public_memory() const;
  void _internal_set_free_public_memory(uint64_t value);
  public:

  // optional uint64 total_private_memory = 14;
  bool has_total_private_memory() const;
  private:
  bool _internal_has_total_private_memory() const;
  public:
  void clear_total_private_memory();
  uint64_t total_private_memory() const;
  void set_total_private_memory(uint64_t value);
  private:
  uint64_t _internal_total_private_memory() const;
  void _internal_set_total_private_memory(uint64_t value);
  public:

  // optional uint64 free_private_memory = 15;
  bool has_free_private_memory() const;
  private:
  bool _internal_has_free_private_memory() const;
  public:
  void clear_free_private_memory();
  uint64_t free_private_memory() const;
  void set_free_private_memory(uint64_t value);
  private:
  uint64_t _internal_free_private_memory() const;
  void _internal_set_free_private_memory(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:chaps.TokenInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr manufacturer_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serial_number_;
  ::chaps::Version* hardware_version_;
  ::chaps::Version* firmware_version_;
  uint64_t flags_;
  uint64_t max_session_count_;
  uint64_t session_count_;
  uint64_t max_session_count_rw_;
  uint64_t session_count_rw_;
  uint64_t max_pin_len_;
  uint64_t min_pin_len_;
  uint64_t total_public_memory_;
  uint64_t free_public_memory_;
  uint64_t total_private_memory_;
  uint64_t free_private_memory_;
  friend struct ::TableStruct_ck_5fstructs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MechanismInfo

// optional uint64 min_key_size = 1;
inline bool MechanismInfo::_internal_has_min_key_size() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MechanismInfo::has_min_key_size() const {
  return _internal_has_min_key_size();
}
inline void MechanismInfo::clear_min_key_size() {
  min_key_size_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000001u;
}
inline uint64_t MechanismInfo::_internal_min_key_size() const {
  return min_key_size_;
}
inline uint64_t MechanismInfo::min_key_size() const {
  // @@protoc_insertion_point(field_get:chaps.MechanismInfo.min_key_size)
  return _internal_min_key_size();
}
inline void MechanismInfo::_internal_set_min_key_size(uint64_t value) {
  _has_bits_[0] |= 0x00000001u;
  min_key_size_ = value;
}
inline void MechanismInfo::set_min_key_size(uint64_t value) {
  _internal_set_min_key_size(value);
  // @@protoc_insertion_point(field_set:chaps.MechanismInfo.min_key_size)
}

// optional uint64 max_key_size = 2;
inline bool MechanismInfo::_internal_has_max_key_size() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MechanismInfo::has_max_key_size() const {
  return _internal_has_max_key_size();
}
inline void MechanismInfo::clear_max_key_size() {
  max_key_size_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000002u;
}
inline uint64_t MechanismInfo::_internal_max_key_size() const {
  return max_key_size_;
}
inline uint64_t MechanismInfo::max_key_size() const {
  // @@protoc_insertion_point(field_get:chaps.MechanismInfo.max_key_size)
  return _internal_max_key_size();
}
inline void MechanismInfo::_internal_set_max_key_size(uint64_t value) {
  _has_bits_[0] |= 0x00000002u;
  max_key_size_ = value;
}
inline void MechanismInfo::set_max_key_size(uint64_t value) {
  _internal_set_max_key_size(value);
  // @@protoc_insertion_point(field_set:chaps.MechanismInfo.max_key_size)
}

// optional uint64 flags = 3;
inline bool MechanismInfo::_internal_has_flags() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MechanismInfo::has_flags() const {
  return _internal_has_flags();
}
inline void MechanismInfo::clear_flags() {
  flags_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline uint64_t MechanismInfo::_internal_flags() const {
  return flags_;
}
inline uint64_t MechanismInfo::flags() const {
  // @@protoc_insertion_point(field_get:chaps.MechanismInfo.flags)
  return _internal_flags();
}
inline void MechanismInfo::_internal_set_flags(uint64_t value) {
  _has_bits_[0] |= 0x00000004u;
  flags_ = value;
}
inline void MechanismInfo::set_flags(uint64_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:chaps.MechanismInfo.flags)
}

// -------------------------------------------------------------------

// SessionInfo

// optional uint64 slot_id = 1;
inline bool SessionInfo::_internal_has_slot_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SessionInfo::has_slot_id() const {
  return _internal_has_slot_id();
}
inline void SessionInfo::clear_slot_id() {
  slot_id_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000001u;
}
inline uint64_t SessionInfo::_internal_slot_id() const {
  return slot_id_;
}
inline uint64_t SessionInfo::slot_id() const {
  // @@protoc_insertion_point(field_get:chaps.SessionInfo.slot_id)
  return _internal_slot_id();
}
inline void SessionInfo::_internal_set_slot_id(uint64_t value) {
  _has_bits_[0] |= 0x00000001u;
  slot_id_ = value;
}
inline void SessionInfo::set_slot_id(uint64_t value) {
  _internal_set_slot_id(value);
  // @@protoc_insertion_point(field_set:chaps.SessionInfo.slot_id)
}

// optional uint64 state = 2;
inline bool SessionInfo::_internal_has_state() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SessionInfo::has_state() const {
  return _internal_has_state();
}
inline void SessionInfo::clear_state() {
  state_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000002u;
}
inline uint64_t SessionInfo::_internal_state() const {
  return state_;
}
inline uint64_t SessionInfo::state() const {
  // @@protoc_insertion_point(field_get:chaps.SessionInfo.state)
  return _internal_state();
}
inline void SessionInfo::_internal_set_state(uint64_t value) {
  _has_bits_[0] |= 0x00000002u;
  state_ = value;
}
inline void SessionInfo::set_state(uint64_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:chaps.SessionInfo.state)
}

// optional uint64 flags = 3;
inline bool SessionInfo::_internal_has_flags() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SessionInfo::has_flags() const {
  return _internal_has_flags();
}
inline void SessionInfo::clear_flags() {
  flags_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline uint64_t SessionInfo::_internal_flags() const {
  return flags_;
}
inline uint64_t SessionInfo::flags() const {
  // @@protoc_insertion_point(field_get:chaps.SessionInfo.flags)
  return _internal_flags();
}
inline void SessionInfo::_internal_set_flags(uint64_t value) {
  _has_bits_[0] |= 0x00000004u;
  flags_ = value;
}
inline void SessionInfo::set_flags(uint64_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:chaps.SessionInfo.flags)
}

// optional uint64 device_error = 4;
inline bool SessionInfo::_internal_has_device_error() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool SessionInfo::has_device_error() const {
  return _internal_has_device_error();
}
inline void SessionInfo::clear_device_error() {
  device_error_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline uint64_t SessionInfo::_internal_device_error() const {
  return device_error_;
}
inline uint64_t SessionInfo::device_error() const {
  // @@protoc_insertion_point(field_get:chaps.SessionInfo.device_error)
  return _internal_device_error();
}
inline void SessionInfo::_internal_set_device_error(uint64_t value) {
  _has_bits_[0] |= 0x00000008u;
  device_error_ = value;
}
inline void SessionInfo::set_device_error(uint64_t value) {
  _internal_set_device_error(value);
  // @@protoc_insertion_point(field_set:chaps.SessionInfo.device_error)
}

// -------------------------------------------------------------------

// Version

// optional uint32 major = 1;
inline bool Version::_internal_has_major() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Version::has_major() const {
  return _internal_has_major();
}
inline void Version::clear_major() {
  major_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline uint32_t Version::_internal_major() const {
  return major_;
}
inline uint32_t Version::major() const {
  // @@protoc_insertion_point(field_get:chaps.Version.major)
  return _internal_major();
}
inline void Version::_internal_set_major(uint32_t value) {
  _has_bits_[0] |= 0x00000001u;
  major_ = value;
}
inline void Version::set_major(uint32_t value) {
  _internal_set_major(value);
  // @@protoc_insertion_point(field_set:chaps.Version.major)
}

// optional uint32 minor = 2;
inline bool Version::_internal_has_minor() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Version::has_minor() const {
  return _internal_has_minor();
}
inline void Version::clear_minor() {
  minor_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline uint32_t Version::_internal_minor() const {
  return minor_;
}
inline uint32_t Version::minor() const {
  // @@protoc_insertion_point(field_get:chaps.Version.minor)
  return _internal_minor();
}
inline void Version::_internal_set_minor(uint32_t value) {
  _has_bits_[0] |= 0x00000002u;
  minor_ = value;
}
inline void Version::set_minor(uint32_t value) {
  _internal_set_minor(value);
  // @@protoc_insertion_point(field_set:chaps.Version.minor)
}

// -------------------------------------------------------------------

// SlotInfo

// optional bytes slot_description = 1;
inline bool SlotInfo::_internal_has_slot_description() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SlotInfo::has_slot_description() const {
  return _internal_has_slot_description();
}
inline void SlotInfo::clear_slot_description() {
  slot_description_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SlotInfo::slot_description() const {
  // @@protoc_insertion_point(field_get:chaps.SlotInfo.slot_description)
  return _internal_slot_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SlotInfo::set_slot_description(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 slot_description_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.SlotInfo.slot_description)
}
inline std::string* SlotInfo::mutable_slot_description() {
  std::string* _s = _internal_mutable_slot_description();
  // @@protoc_insertion_point(field_mutable:chaps.SlotInfo.slot_description)
  return _s;
}
inline const std::string& SlotInfo::_internal_slot_description() const {
  return slot_description_.Get();
}
inline void SlotInfo::_internal_set_slot_description(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  slot_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* SlotInfo::_internal_mutable_slot_description() {
  _has_bits_[0] |= 0x00000001u;
  return slot_description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* SlotInfo::release_slot_description() {
  // @@protoc_insertion_point(field_release:chaps.SlotInfo.slot_description)
  if (!_internal_has_slot_description()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = slot_description_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (slot_description_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    slot_description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void SlotInfo::set_allocated_slot_description(std::string* slot_description) {
  if (slot_description != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  slot_description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), slot_description,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (slot_description_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    slot_description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.SlotInfo.slot_description)
}

// optional bytes manufacturer_id = 2;
inline bool SlotInfo::_internal_has_manufacturer_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SlotInfo::has_manufacturer_id() const {
  return _internal_has_manufacturer_id();
}
inline void SlotInfo::clear_manufacturer_id() {
  manufacturer_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SlotInfo::manufacturer_id() const {
  // @@protoc_insertion_point(field_get:chaps.SlotInfo.manufacturer_id)
  return _internal_manufacturer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SlotInfo::set_manufacturer_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 manufacturer_id_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.SlotInfo.manufacturer_id)
}
inline std::string* SlotInfo::mutable_manufacturer_id() {
  std::string* _s = _internal_mutable_manufacturer_id();
  // @@protoc_insertion_point(field_mutable:chaps.SlotInfo.manufacturer_id)
  return _s;
}
inline const std::string& SlotInfo::_internal_manufacturer_id() const {
  return manufacturer_id_.Get();
}
inline void SlotInfo::_internal_set_manufacturer_id(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  manufacturer_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* SlotInfo::_internal_mutable_manufacturer_id() {
  _has_bits_[0] |= 0x00000002u;
  return manufacturer_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* SlotInfo::release_manufacturer_id() {
  // @@protoc_insertion_point(field_release:chaps.SlotInfo.manufacturer_id)
  if (!_internal_has_manufacturer_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = manufacturer_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (manufacturer_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    manufacturer_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void SlotInfo::set_allocated_manufacturer_id(std::string* manufacturer_id) {
  if (manufacturer_id != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  manufacturer_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), manufacturer_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (manufacturer_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    manufacturer_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.SlotInfo.manufacturer_id)
}

// optional uint64 flags = 3;
inline bool SlotInfo::_internal_has_flags() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool SlotInfo::has_flags() const {
  return _internal_has_flags();
}
inline void SlotInfo::clear_flags() {
  flags_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000010u;
}
inline uint64_t SlotInfo::_internal_flags() const {
  return flags_;
}
inline uint64_t SlotInfo::flags() const {
  // @@protoc_insertion_point(field_get:chaps.SlotInfo.flags)
  return _internal_flags();
}
inline void SlotInfo::_internal_set_flags(uint64_t value) {
  _has_bits_[0] |= 0x00000010u;
  flags_ = value;
}
inline void SlotInfo::set_flags(uint64_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:chaps.SlotInfo.flags)
}

// optional .chaps.Version hardware_version = 4;
inline bool SlotInfo::_internal_has_hardware_version() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || hardware_version_ != nullptr);
  return value;
}
inline bool SlotInfo::has_hardware_version() const {
  return _internal_has_hardware_version();
}
inline void SlotInfo::clear_hardware_version() {
  if (hardware_version_ != nullptr) hardware_version_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::chaps::Version& SlotInfo::_internal_hardware_version() const {
  const ::chaps::Version* p = hardware_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::chaps::Version&>(
      ::chaps::_Version_default_instance_);
}
inline const ::chaps::Version& SlotInfo::hardware_version() const {
  // @@protoc_insertion_point(field_get:chaps.SlotInfo.hardware_version)
  return _internal_hardware_version();
}
inline void SlotInfo::unsafe_arena_set_allocated_hardware_version(
    ::chaps::Version* hardware_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(hardware_version_);
  }
  hardware_version_ = hardware_version;
  if (hardware_version) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chaps.SlotInfo.hardware_version)
}
inline ::chaps::Version* SlotInfo::release_hardware_version() {
  _has_bits_[0] &= ~0x00000004u;
  ::chaps::Version* temp = hardware_version_;
  hardware_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chaps::Version* SlotInfo::unsafe_arena_release_hardware_version() {
  // @@protoc_insertion_point(field_release:chaps.SlotInfo.hardware_version)
  _has_bits_[0] &= ~0x00000004u;
  ::chaps::Version* temp = hardware_version_;
  hardware_version_ = nullptr;
  return temp;
}
inline ::chaps::Version* SlotInfo::_internal_mutable_hardware_version() {
  _has_bits_[0] |= 0x00000004u;
  if (hardware_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::chaps::Version>(GetArenaForAllocation());
    hardware_version_ = p;
  }
  return hardware_version_;
}
inline ::chaps::Version* SlotInfo::mutable_hardware_version() {
  ::chaps::Version* _msg = _internal_mutable_hardware_version();
  // @@protoc_insertion_point(field_mutable:chaps.SlotInfo.hardware_version)
  return _msg;
}
inline void SlotInfo::set_allocated_hardware_version(::chaps::Version* hardware_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete hardware_version_;
  }
  if (hardware_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::chaps::Version>::GetOwningArena(hardware_version);
    if (message_arena != submessage_arena) {
      hardware_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hardware_version, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  hardware_version_ = hardware_version;
  // @@protoc_insertion_point(field_set_allocated:chaps.SlotInfo.hardware_version)
}

// optional .chaps.Version firmware_version = 5;
inline bool SlotInfo::_internal_has_firmware_version() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || firmware_version_ != nullptr);
  return value;
}
inline bool SlotInfo::has_firmware_version() const {
  return _internal_has_firmware_version();
}
inline void SlotInfo::clear_firmware_version() {
  if (firmware_version_ != nullptr) firmware_version_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::chaps::Version& SlotInfo::_internal_firmware_version() const {
  const ::chaps::Version* p = firmware_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::chaps::Version&>(
      ::chaps::_Version_default_instance_);
}
inline const ::chaps::Version& SlotInfo::firmware_version() const {
  // @@protoc_insertion_point(field_get:chaps.SlotInfo.firmware_version)
  return _internal_firmware_version();
}
inline void SlotInfo::unsafe_arena_set_allocated_firmware_version(
    ::chaps::Version* firmware_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(firmware_version_);
  }
  firmware_version_ = firmware_version;
  if (firmware_version) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chaps.SlotInfo.firmware_version)
}
inline ::chaps::Version* SlotInfo::release_firmware_version() {
  _has_bits_[0] &= ~0x00000008u;
  ::chaps::Version* temp = firmware_version_;
  firmware_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chaps::Version* SlotInfo::unsafe_arena_release_firmware_version() {
  // @@protoc_insertion_point(field_release:chaps.SlotInfo.firmware_version)
  _has_bits_[0] &= ~0x00000008u;
  ::chaps::Version* temp = firmware_version_;
  firmware_version_ = nullptr;
  return temp;
}
inline ::chaps::Version* SlotInfo::_internal_mutable_firmware_version() {
  _has_bits_[0] |= 0x00000008u;
  if (firmware_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::chaps::Version>(GetArenaForAllocation());
    firmware_version_ = p;
  }
  return firmware_version_;
}
inline ::chaps::Version* SlotInfo::mutable_firmware_version() {
  ::chaps::Version* _msg = _internal_mutable_firmware_version();
  // @@protoc_insertion_point(field_mutable:chaps.SlotInfo.firmware_version)
  return _msg;
}
inline void SlotInfo::set_allocated_firmware_version(::chaps::Version* firmware_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete firmware_version_;
  }
  if (firmware_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::chaps::Version>::GetOwningArena(firmware_version);
    if (message_arena != submessage_arena) {
      firmware_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, firmware_version, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  firmware_version_ = firmware_version;
  // @@protoc_insertion_point(field_set_allocated:chaps.SlotInfo.firmware_version)
}

// -------------------------------------------------------------------

// TokenInfo

// optional bytes label = 1;
inline bool TokenInfo::_internal_has_label() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TokenInfo::has_label() const {
  return _internal_has_label();
}
inline void TokenInfo::clear_label() {
  label_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TokenInfo::label() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.label)
  return _internal_label();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TokenInfo::set_label(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 label_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.label)
}
inline std::string* TokenInfo::mutable_label() {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.label)
  return _s;
}
inline const std::string& TokenInfo::_internal_label() const {
  return label_.Get();
}
inline void TokenInfo::_internal_set_label(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  label_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TokenInfo::_internal_mutable_label() {
  _has_bits_[0] |= 0x00000001u;
  return label_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TokenInfo::release_label() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.label)
  if (!_internal_has_label()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = label_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (label_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    label_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TokenInfo::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  label_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), label,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (label_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    label_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.label)
}

// optional bytes manufacturer_id = 2;
inline bool TokenInfo::_internal_has_manufacturer_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TokenInfo::has_manufacturer_id() const {
  return _internal_has_manufacturer_id();
}
inline void TokenInfo::clear_manufacturer_id() {
  manufacturer_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& TokenInfo::manufacturer_id() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.manufacturer_id)
  return _internal_manufacturer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TokenInfo::set_manufacturer_id(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 manufacturer_id_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.manufacturer_id)
}
inline std::string* TokenInfo::mutable_manufacturer_id() {
  std::string* _s = _internal_mutable_manufacturer_id();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.manufacturer_id)
  return _s;
}
inline const std::string& TokenInfo::_internal_manufacturer_id() const {
  return manufacturer_id_.Get();
}
inline void TokenInfo::_internal_set_manufacturer_id(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  manufacturer_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TokenInfo::_internal_mutable_manufacturer_id() {
  _has_bits_[0] |= 0x00000002u;
  return manufacturer_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TokenInfo::release_manufacturer_id() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.manufacturer_id)
  if (!_internal_has_manufacturer_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = manufacturer_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (manufacturer_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    manufacturer_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TokenInfo::set_allocated_manufacturer_id(std::string* manufacturer_id) {
  if (manufacturer_id != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  manufacturer_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), manufacturer_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (manufacturer_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    manufacturer_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.manufacturer_id)
}

// optional bytes model = 3;
inline bool TokenInfo::_internal_has_model() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TokenInfo::has_model() const {
  return _internal_has_model();
}
inline void TokenInfo::clear_model() {
  model_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& TokenInfo::model() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.model)
  return _internal_model();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TokenInfo::set_model(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 model_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.model)
}
inline std::string* TokenInfo::mutable_model() {
  std::string* _s = _internal_mutable_model();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.model)
  return _s;
}
inline const std::string& TokenInfo::_internal_model() const {
  return model_.Get();
}
inline void TokenInfo::_internal_set_model(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  model_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TokenInfo::_internal_mutable_model() {
  _has_bits_[0] |= 0x00000004u;
  return model_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TokenInfo::release_model() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.model)
  if (!_internal_has_model()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = model_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (model_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    model_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TokenInfo::set_allocated_model(std::string* model) {
  if (model != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  model_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (model_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    model_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.model)
}

// optional bytes serial_number = 4;
inline bool TokenInfo::_internal_has_serial_number() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TokenInfo::has_serial_number() const {
  return _internal_has_serial_number();
}
inline void TokenInfo::clear_serial_number() {
  serial_number_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& TokenInfo::serial_number() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.serial_number)
  return _internal_serial_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TokenInfo::set_serial_number(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 serial_number_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.serial_number)
}
inline std::string* TokenInfo::mutable_serial_number() {
  std::string* _s = _internal_mutable_serial_number();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.serial_number)
  return _s;
}
inline const std::string& TokenInfo::_internal_serial_number() const {
  return serial_number_.Get();
}
inline void TokenInfo::_internal_set_serial_number(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  serial_number_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* TokenInfo::_internal_mutable_serial_number() {
  _has_bits_[0] |= 0x00000008u;
  return serial_number_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* TokenInfo::release_serial_number() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.serial_number)
  if (!_internal_has_serial_number()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  auto* p = serial_number_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (serial_number_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    serial_number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void TokenInfo::set_allocated_serial_number(std::string* serial_number) {
  if (serial_number != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  serial_number_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), serial_number,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (serial_number_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    serial_number_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.serial_number)
}

// optional uint64 flags = 5;
inline bool TokenInfo::_internal_has_flags() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool TokenInfo::has_flags() const {
  return _internal_has_flags();
}
inline void TokenInfo::clear_flags() {
  flags_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000040u;
}
inline uint64_t TokenInfo::_internal_flags() const {
  return flags_;
}
inline uint64_t TokenInfo::flags() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.flags)
  return _internal_flags();
}
inline void TokenInfo::_internal_set_flags(uint64_t value) {
  _has_bits_[0] |= 0x00000040u;
  flags_ = value;
}
inline void TokenInfo::set_flags(uint64_t value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.flags)
}

// optional uint64 max_session_count = 6;
inline bool TokenInfo::_internal_has_max_session_count() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool TokenInfo::has_max_session_count() const {
  return _internal_has_max_session_count();
}
inline void TokenInfo::clear_max_session_count() {
  max_session_count_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000080u;
}
inline uint64_t TokenInfo::_internal_max_session_count() const {
  return max_session_count_;
}
inline uint64_t TokenInfo::max_session_count() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.max_session_count)
  return _internal_max_session_count();
}
inline void TokenInfo::_internal_set_max_session_count(uint64_t value) {
  _has_bits_[0] |= 0x00000080u;
  max_session_count_ = value;
}
inline void TokenInfo::set_max_session_count(uint64_t value) {
  _internal_set_max_session_count(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.max_session_count)
}

// optional uint64 session_count = 7;
inline bool TokenInfo::_internal_has_session_count() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool TokenInfo::has_session_count() const {
  return _internal_has_session_count();
}
inline void TokenInfo::clear_session_count() {
  session_count_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000100u;
}
inline uint64_t TokenInfo::_internal_session_count() const {
  return session_count_;
}
inline uint64_t TokenInfo::session_count() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.session_count)
  return _internal_session_count();
}
inline void TokenInfo::_internal_set_session_count(uint64_t value) {
  _has_bits_[0] |= 0x00000100u;
  session_count_ = value;
}
inline void TokenInfo::set_session_count(uint64_t value) {
  _internal_set_session_count(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.session_count)
}

// optional uint64 max_session_count_rw = 8;
inline bool TokenInfo::_internal_has_max_session_count_rw() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool TokenInfo::has_max_session_count_rw() const {
  return _internal_has_max_session_count_rw();
}
inline void TokenInfo::clear_max_session_count_rw() {
  max_session_count_rw_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000200u;
}
inline uint64_t TokenInfo::_internal_max_session_count_rw() const {
  return max_session_count_rw_;
}
inline uint64_t TokenInfo::max_session_count_rw() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.max_session_count_rw)
  return _internal_max_session_count_rw();
}
inline void TokenInfo::_internal_set_max_session_count_rw(uint64_t value) {
  _has_bits_[0] |= 0x00000200u;
  max_session_count_rw_ = value;
}
inline void TokenInfo::set_max_session_count_rw(uint64_t value) {
  _internal_set_max_session_count_rw(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.max_session_count_rw)
}

// optional uint64 session_count_rw = 9;
inline bool TokenInfo::_internal_has_session_count_rw() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool TokenInfo::has_session_count_rw() const {
  return _internal_has_session_count_rw();
}
inline void TokenInfo::clear_session_count_rw() {
  session_count_rw_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000400u;
}
inline uint64_t TokenInfo::_internal_session_count_rw() const {
  return session_count_rw_;
}
inline uint64_t TokenInfo::session_count_rw() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.session_count_rw)
  return _internal_session_count_rw();
}
inline void TokenInfo::_internal_set_session_count_rw(uint64_t value) {
  _has_bits_[0] |= 0x00000400u;
  session_count_rw_ = value;
}
inline void TokenInfo::set_session_count_rw(uint64_t value) {
  _internal_set_session_count_rw(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.session_count_rw)
}

// optional uint64 max_pin_len = 10;
inline bool TokenInfo::_internal_has_max_pin_len() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool TokenInfo::has_max_pin_len() const {
  return _internal_has_max_pin_len();
}
inline void TokenInfo::clear_max_pin_len() {
  max_pin_len_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000800u;
}
inline uint64_t TokenInfo::_internal_max_pin_len() const {
  return max_pin_len_;
}
inline uint64_t TokenInfo::max_pin_len() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.max_pin_len)
  return _internal_max_pin_len();
}
inline void TokenInfo::_internal_set_max_pin_len(uint64_t value) {
  _has_bits_[0] |= 0x00000800u;
  max_pin_len_ = value;
}
inline void TokenInfo::set_max_pin_len(uint64_t value) {
  _internal_set_max_pin_len(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.max_pin_len)
}

// optional uint64 min_pin_len = 11;
inline bool TokenInfo::_internal_has_min_pin_len() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool TokenInfo::has_min_pin_len() const {
  return _internal_has_min_pin_len();
}
inline void TokenInfo::clear_min_pin_len() {
  min_pin_len_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00001000u;
}
inline uint64_t TokenInfo::_internal_min_pin_len() const {
  return min_pin_len_;
}
inline uint64_t TokenInfo::min_pin_len() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.min_pin_len)
  return _internal_min_pin_len();
}
inline void TokenInfo::_internal_set_min_pin_len(uint64_t value) {
  _has_bits_[0] |= 0x00001000u;
  min_pin_len_ = value;
}
inline void TokenInfo::set_min_pin_len(uint64_t value) {
  _internal_set_min_pin_len(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.min_pin_len)
}

// optional uint64 total_public_memory = 12;
inline bool TokenInfo::_internal_has_total_public_memory() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool TokenInfo::has_total_public_memory() const {
  return _internal_has_total_public_memory();
}
inline void TokenInfo::clear_total_public_memory() {
  total_public_memory_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00002000u;
}
inline uint64_t TokenInfo::_internal_total_public_memory() const {
  return total_public_memory_;
}
inline uint64_t TokenInfo::total_public_memory() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.total_public_memory)
  return _internal_total_public_memory();
}
inline void TokenInfo::_internal_set_total_public_memory(uint64_t value) {
  _has_bits_[0] |= 0x00002000u;
  total_public_memory_ = value;
}
inline void TokenInfo::set_total_public_memory(uint64_t value) {
  _internal_set_total_public_memory(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.total_public_memory)
}

// optional uint64 free_public_memory = 13;
inline bool TokenInfo::_internal_has_free_public_memory() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool TokenInfo::has_free_public_memory() const {
  return _internal_has_free_public_memory();
}
inline void TokenInfo::clear_free_public_memory() {
  free_public_memory_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00004000u;
}
inline uint64_t TokenInfo::_internal_free_public_memory() const {
  return free_public_memory_;
}
inline uint64_t TokenInfo::free_public_memory() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.free_public_memory)
  return _internal_free_public_memory();
}
inline void TokenInfo::_internal_set_free_public_memory(uint64_t value) {
  _has_bits_[0] |= 0x00004000u;
  free_public_memory_ = value;
}
inline void TokenInfo::set_free_public_memory(uint64_t value) {
  _internal_set_free_public_memory(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.free_public_memory)
}

// optional uint64 total_private_memory = 14;
inline bool TokenInfo::_internal_has_total_private_memory() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool TokenInfo::has_total_private_memory() const {
  return _internal_has_total_private_memory();
}
inline void TokenInfo::clear_total_private_memory() {
  total_private_memory_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00008000u;
}
inline uint64_t TokenInfo::_internal_total_private_memory() const {
  return total_private_memory_;
}
inline uint64_t TokenInfo::total_private_memory() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.total_private_memory)
  return _internal_total_private_memory();
}
inline void TokenInfo::_internal_set_total_private_memory(uint64_t value) {
  _has_bits_[0] |= 0x00008000u;
  total_private_memory_ = value;
}
inline void TokenInfo::set_total_private_memory(uint64_t value) {
  _internal_set_total_private_memory(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.total_private_memory)
}

// optional uint64 free_private_memory = 15;
inline bool TokenInfo::_internal_has_free_private_memory() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool TokenInfo::has_free_private_memory() const {
  return _internal_has_free_private_memory();
}
inline void TokenInfo::clear_free_private_memory() {
  free_private_memory_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00010000u;
}
inline uint64_t TokenInfo::_internal_free_private_memory() const {
  return free_private_memory_;
}
inline uint64_t TokenInfo::free_private_memory() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.free_private_memory)
  return _internal_free_private_memory();
}
inline void TokenInfo::_internal_set_free_private_memory(uint64_t value) {
  _has_bits_[0] |= 0x00010000u;
  free_private_memory_ = value;
}
inline void TokenInfo::set_free_private_memory(uint64_t value) {
  _internal_set_free_private_memory(value);
  // @@protoc_insertion_point(field_set:chaps.TokenInfo.free_private_memory)
}

// optional .chaps.Version hardware_version = 16;
inline bool TokenInfo::_internal_has_hardware_version() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || hardware_version_ != nullptr);
  return value;
}
inline bool TokenInfo::has_hardware_version() const {
  return _internal_has_hardware_version();
}
inline void TokenInfo::clear_hardware_version() {
  if (hardware_version_ != nullptr) hardware_version_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::chaps::Version& TokenInfo::_internal_hardware_version() const {
  const ::chaps::Version* p = hardware_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::chaps::Version&>(
      ::chaps::_Version_default_instance_);
}
inline const ::chaps::Version& TokenInfo::hardware_version() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.hardware_version)
  return _internal_hardware_version();
}
inline void TokenInfo::unsafe_arena_set_allocated_hardware_version(
    ::chaps::Version* hardware_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(hardware_version_);
  }
  hardware_version_ = hardware_version;
  if (hardware_version) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chaps.TokenInfo.hardware_version)
}
inline ::chaps::Version* TokenInfo::release_hardware_version() {
  _has_bits_[0] &= ~0x00000010u;
  ::chaps::Version* temp = hardware_version_;
  hardware_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chaps::Version* TokenInfo::unsafe_arena_release_hardware_version() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.hardware_version)
  _has_bits_[0] &= ~0x00000010u;
  ::chaps::Version* temp = hardware_version_;
  hardware_version_ = nullptr;
  return temp;
}
inline ::chaps::Version* TokenInfo::_internal_mutable_hardware_version() {
  _has_bits_[0] |= 0x00000010u;
  if (hardware_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::chaps::Version>(GetArenaForAllocation());
    hardware_version_ = p;
  }
  return hardware_version_;
}
inline ::chaps::Version* TokenInfo::mutable_hardware_version() {
  ::chaps::Version* _msg = _internal_mutable_hardware_version();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.hardware_version)
  return _msg;
}
inline void TokenInfo::set_allocated_hardware_version(::chaps::Version* hardware_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete hardware_version_;
  }
  if (hardware_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::chaps::Version>::GetOwningArena(hardware_version);
    if (message_arena != submessage_arena) {
      hardware_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hardware_version, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  hardware_version_ = hardware_version;
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.hardware_version)
}

// optional .chaps.Version firmware_version = 17;
inline bool TokenInfo::_internal_has_firmware_version() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || firmware_version_ != nullptr);
  return value;
}
inline bool TokenInfo::has_firmware_version() const {
  return _internal_has_firmware_version();
}
inline void TokenInfo::clear_firmware_version() {
  if (firmware_version_ != nullptr) firmware_version_->Clear();
  _has_bits_[0] &= ~0x00000020u;
}
inline const ::chaps::Version& TokenInfo::_internal_firmware_version() const {
  const ::chaps::Version* p = firmware_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::chaps::Version&>(
      ::chaps::_Version_default_instance_);
}
inline const ::chaps::Version& TokenInfo::firmware_version() const {
  // @@protoc_insertion_point(field_get:chaps.TokenInfo.firmware_version)
  return _internal_firmware_version();
}
inline void TokenInfo::unsafe_arena_set_allocated_firmware_version(
    ::chaps::Version* firmware_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(firmware_version_);
  }
  firmware_version_ = firmware_version;
  if (firmware_version) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chaps.TokenInfo.firmware_version)
}
inline ::chaps::Version* TokenInfo::release_firmware_version() {
  _has_bits_[0] &= ~0x00000020u;
  ::chaps::Version* temp = firmware_version_;
  firmware_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::chaps::Version* TokenInfo::unsafe_arena_release_firmware_version() {
  // @@protoc_insertion_point(field_release:chaps.TokenInfo.firmware_version)
  _has_bits_[0] &= ~0x00000020u;
  ::chaps::Version* temp = firmware_version_;
  firmware_version_ = nullptr;
  return temp;
}
inline ::chaps::Version* TokenInfo::_internal_mutable_firmware_version() {
  _has_bits_[0] |= 0x00000020u;
  if (firmware_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::chaps::Version>(GetArenaForAllocation());
    firmware_version_ = p;
  }
  return firmware_version_;
}
inline ::chaps::Version* TokenInfo::mutable_firmware_version() {
  ::chaps::Version* _msg = _internal_mutable_firmware_version();
  // @@protoc_insertion_point(field_mutable:chaps.TokenInfo.firmware_version)
  return _msg;
}
inline void TokenInfo::set_allocated_firmware_version(::chaps::Version* firmware_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete firmware_version_;
  }
  if (firmware_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::chaps::Version>::GetOwningArena(firmware_version);
    if (message_arena != submessage_arena) {
      firmware_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, firmware_version, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  firmware_version_ = firmware_version;
  // @@protoc_insertion_point(field_set_allocated:chaps.TokenInfo.firmware_version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chaps

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ck_5fstructs_2eproto
