// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_vm_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_plugin_5fvm_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_plugin_5fvm_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_plugin_5fvm_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_plugin_5fvm_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace plugin_vm_service {
class GetAppLicenseUserIdResponse;
struct GetAppLicenseUserIdResponseDefaultTypeInternal;
extern GetAppLicenseUserIdResponseDefaultTypeInternal _GetAppLicenseUserIdResponse_default_instance_;
class GetLicenseDataResponse;
struct GetLicenseDataResponseDefaultTypeInternal;
extern GetLicenseDataResponseDefaultTypeInternal _GetLicenseDataResponse_default_instance_;
class GetPermissionsResponse;
struct GetPermissionsResponseDefaultTypeInternal;
extern GetPermissionsResponseDefaultTypeInternal _GetPermissionsResponse_default_instance_;
class ShowSettingsPageRequest;
struct ShowSettingsPageRequestDefaultTypeInternal;
extern ShowSettingsPageRequestDefaultTypeInternal _ShowSettingsPageRequest_default_instance_;
}  // namespace plugin_vm_service
PROTOBUF_NAMESPACE_OPEN
template<> ::plugin_vm_service::GetAppLicenseUserIdResponse* Arena::CreateMaybeMessage<::plugin_vm_service::GetAppLicenseUserIdResponse>(Arena*);
template<> ::plugin_vm_service::GetLicenseDataResponse* Arena::CreateMaybeMessage<::plugin_vm_service::GetLicenseDataResponse>(Arena*);
template<> ::plugin_vm_service::GetPermissionsResponse* Arena::CreateMaybeMessage<::plugin_vm_service::GetPermissionsResponse>(Arena*);
template<> ::plugin_vm_service::ShowSettingsPageRequest* Arena::CreateMaybeMessage<::plugin_vm_service::ShowSettingsPageRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace plugin_vm_service {

// ===================================================================

class GetLicenseDataResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:plugin_vm_service.GetLicenseDataResponse) */ {
 public:
  inline GetLicenseDataResponse() : GetLicenseDataResponse(nullptr) {}
  ~GetLicenseDataResponse() override;
  explicit constexpr GetLicenseDataResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetLicenseDataResponse(const GetLicenseDataResponse& from);
  GetLicenseDataResponse(GetLicenseDataResponse&& from) noexcept
    : GetLicenseDataResponse() {
    *this = ::std::move(from);
  }

  inline GetLicenseDataResponse& operator=(const GetLicenseDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetLicenseDataResponse& operator=(GetLicenseDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GetLicenseDataResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetLicenseDataResponse* internal_default_instance() {
    return reinterpret_cast<const GetLicenseDataResponse*>(
               &_GetLicenseDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetLicenseDataResponse& a, GetLicenseDataResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetLicenseDataResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetLicenseDataResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetLicenseDataResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetLicenseDataResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GetLicenseDataResponse& from);
  void MergeFrom(const GetLicenseDataResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetLicenseDataResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "plugin_vm_service.GetLicenseDataResponse";
  }
  protected:
  explicit GetLicenseDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLicenseKeyFieldNumber = 1,
    kDeviceIdFieldNumber = 2,
  };
  // string license_key = 1;
  void clear_license_key();
  const std::string& license_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_license_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_license_key();
  PROTOBUF_NODISCARD std::string* release_license_key();
  void set_allocated_license_key(std::string* license_key);
  private:
  const std::string& _internal_license_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_license_key(const std::string& value);
  std::string* _internal_mutable_license_key();
  public:

  // string device_id = 2;
  void clear_device_id();
  const std::string& device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_id();
  PROTOBUF_NODISCARD std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // @@protoc_insertion_point(class_scope:plugin_vm_service.GetLicenseDataResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr license_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_plugin_5fvm_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ShowSettingsPageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:plugin_vm_service.ShowSettingsPageRequest) */ {
 public:
  inline ShowSettingsPageRequest() : ShowSettingsPageRequest(nullptr) {}
  ~ShowSettingsPageRequest() override;
  explicit constexpr ShowSettingsPageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShowSettingsPageRequest(const ShowSettingsPageRequest& from);
  ShowSettingsPageRequest(ShowSettingsPageRequest&& from) noexcept
    : ShowSettingsPageRequest() {
    *this = ::std::move(from);
  }

  inline ShowSettingsPageRequest& operator=(const ShowSettingsPageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShowSettingsPageRequest& operator=(ShowSettingsPageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ShowSettingsPageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShowSettingsPageRequest* internal_default_instance() {
    return reinterpret_cast<const ShowSettingsPageRequest*>(
               &_ShowSettingsPageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ShowSettingsPageRequest& a, ShowSettingsPageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ShowSettingsPageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShowSettingsPageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShowSettingsPageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShowSettingsPageRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ShowSettingsPageRequest& from);
  void MergeFrom(const ShowSettingsPageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ShowSettingsPageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "plugin_vm_service.ShowSettingsPageRequest";
  }
  protected:
  explicit ShowSettingsPageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubpagePathFieldNumber = 1,
  };
  // string subpage_path = 1;
  void clear_subpage_path();
  const std::string& subpage_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_subpage_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_subpage_path();
  PROTOBUF_NODISCARD std::string* release_subpage_path();
  void set_allocated_subpage_path(std::string* subpage_path);
  private:
  const std::string& _internal_subpage_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_subpage_path(const std::string& value);
  std::string* _internal_mutable_subpage_path();
  public:

  // @@protoc_insertion_point(class_scope:plugin_vm_service.ShowSettingsPageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr subpage_path_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_plugin_5fvm_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetPermissionsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:plugin_vm_service.GetPermissionsResponse) */ {
 public:
  inline GetPermissionsResponse() : GetPermissionsResponse(nullptr) {}
  ~GetPermissionsResponse() override;
  explicit constexpr GetPermissionsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetPermissionsResponse(const GetPermissionsResponse& from);
  GetPermissionsResponse(GetPermissionsResponse&& from) noexcept
    : GetPermissionsResponse() {
    *this = ::std::move(from);
  }

  inline GetPermissionsResponse& operator=(const GetPermissionsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetPermissionsResponse& operator=(GetPermissionsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GetPermissionsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetPermissionsResponse* internal_default_instance() {
    return reinterpret_cast<const GetPermissionsResponse*>(
               &_GetPermissionsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetPermissionsResponse& a, GetPermissionsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetPermissionsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetPermissionsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetPermissionsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetPermissionsResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GetPermissionsResponse& from);
  void MergeFrom(const GetPermissionsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetPermissionsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "plugin_vm_service.GetPermissionsResponse";
  }
  protected:
  explicit GetPermissionsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataCollectionEnabledFieldNumber = 1,
  };
  // bool data_collection_enabled = 1;
  void clear_data_collection_enabled();
  bool data_collection_enabled() const;
  void set_data_collection_enabled(bool value);
  private:
  bool _internal_data_collection_enabled() const;
  void _internal_set_data_collection_enabled(bool value);
  public:

  // @@protoc_insertion_point(class_scope:plugin_vm_service.GetPermissionsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool data_collection_enabled_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_plugin_5fvm_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetAppLicenseUserIdResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:plugin_vm_service.GetAppLicenseUserIdResponse) */ {
 public:
  inline GetAppLicenseUserIdResponse() : GetAppLicenseUserIdResponse(nullptr) {}
  ~GetAppLicenseUserIdResponse() override;
  explicit constexpr GetAppLicenseUserIdResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAppLicenseUserIdResponse(const GetAppLicenseUserIdResponse& from);
  GetAppLicenseUserIdResponse(GetAppLicenseUserIdResponse&& from) noexcept
    : GetAppLicenseUserIdResponse() {
    *this = ::std::move(from);
  }

  inline GetAppLicenseUserIdResponse& operator=(const GetAppLicenseUserIdResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAppLicenseUserIdResponse& operator=(GetAppLicenseUserIdResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const GetAppLicenseUserIdResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAppLicenseUserIdResponse* internal_default_instance() {
    return reinterpret_cast<const GetAppLicenseUserIdResponse*>(
               &_GetAppLicenseUserIdResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetAppLicenseUserIdResponse& a, GetAppLicenseUserIdResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAppLicenseUserIdResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAppLicenseUserIdResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAppLicenseUserIdResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAppLicenseUserIdResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GetAppLicenseUserIdResponse& from);
  void MergeFrom(const GetAppLicenseUserIdResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetAppLicenseUserIdResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "plugin_vm_service.GetAppLicenseUserIdResponse";
  }
  protected:
  explicit GetAppLicenseUserIdResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
  };
  // string user_id = 1;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // @@protoc_insertion_point(class_scope:plugin_vm_service.GetAppLicenseUserIdResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_plugin_5fvm_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetLicenseDataResponse

// string license_key = 1;
inline void GetLicenseDataResponse::clear_license_key() {
  license_key_.ClearToEmpty();
}
inline const std::string& GetLicenseDataResponse::license_key() const {
  // @@protoc_insertion_point(field_get:plugin_vm_service.GetLicenseDataResponse.license_key)
  return _internal_license_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetLicenseDataResponse::set_license_key(ArgT0&& arg0, ArgT... args) {
 
 license_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:plugin_vm_service.GetLicenseDataResponse.license_key)
}
inline std::string* GetLicenseDataResponse::mutable_license_key() {
  std::string* _s = _internal_mutable_license_key();
  // @@protoc_insertion_point(field_mutable:plugin_vm_service.GetLicenseDataResponse.license_key)
  return _s;
}
inline const std::string& GetLicenseDataResponse::_internal_license_key() const {
  return license_key_.Get();
}
inline void GetLicenseDataResponse::_internal_set_license_key(const std::string& value) {
  
  license_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* GetLicenseDataResponse::_internal_mutable_license_key() {
  
  return license_key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* GetLicenseDataResponse::release_license_key() {
  // @@protoc_insertion_point(field_release:plugin_vm_service.GetLicenseDataResponse.license_key)
  return license_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void GetLicenseDataResponse::set_allocated_license_key(std::string* license_key) {
  if (license_key != nullptr) {
    
  } else {
    
  }
  license_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), license_key,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (license_key_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    license_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:plugin_vm_service.GetLicenseDataResponse.license_key)
}

// string device_id = 2;
inline void GetLicenseDataResponse::clear_device_id() {
  device_id_.ClearToEmpty();
}
inline const std::string& GetLicenseDataResponse::device_id() const {
  // @@protoc_insertion_point(field_get:plugin_vm_service.GetLicenseDataResponse.device_id)
  return _internal_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetLicenseDataResponse::set_device_id(ArgT0&& arg0, ArgT... args) {
 
 device_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:plugin_vm_service.GetLicenseDataResponse.device_id)
}
inline std::string* GetLicenseDataResponse::mutable_device_id() {
  std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:plugin_vm_service.GetLicenseDataResponse.device_id)
  return _s;
}
inline const std::string& GetLicenseDataResponse::_internal_device_id() const {
  return device_id_.Get();
}
inline void GetLicenseDataResponse::_internal_set_device_id(const std::string& value) {
  
  device_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* GetLicenseDataResponse::_internal_mutable_device_id() {
  
  return device_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* GetLicenseDataResponse::release_device_id() {
  // @@protoc_insertion_point(field_release:plugin_vm_service.GetLicenseDataResponse.device_id)
  return device_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void GetLicenseDataResponse::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {
    
  } else {
    
  }
  device_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (device_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:plugin_vm_service.GetLicenseDataResponse.device_id)
}

// -------------------------------------------------------------------

// ShowSettingsPageRequest

// string subpage_path = 1;
inline void ShowSettingsPageRequest::clear_subpage_path() {
  subpage_path_.ClearToEmpty();
}
inline const std::string& ShowSettingsPageRequest::subpage_path() const {
  // @@protoc_insertion_point(field_get:plugin_vm_service.ShowSettingsPageRequest.subpage_path)
  return _internal_subpage_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShowSettingsPageRequest::set_subpage_path(ArgT0&& arg0, ArgT... args) {
 
 subpage_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:plugin_vm_service.ShowSettingsPageRequest.subpage_path)
}
inline std::string* ShowSettingsPageRequest::mutable_subpage_path() {
  std::string* _s = _internal_mutable_subpage_path();
  // @@protoc_insertion_point(field_mutable:plugin_vm_service.ShowSettingsPageRequest.subpage_path)
  return _s;
}
inline const std::string& ShowSettingsPageRequest::_internal_subpage_path() const {
  return subpage_path_.Get();
}
inline void ShowSettingsPageRequest::_internal_set_subpage_path(const std::string& value) {
  
  subpage_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ShowSettingsPageRequest::_internal_mutable_subpage_path() {
  
  return subpage_path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ShowSettingsPageRequest::release_subpage_path() {
  // @@protoc_insertion_point(field_release:plugin_vm_service.ShowSettingsPageRequest.subpage_path)
  return subpage_path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ShowSettingsPageRequest::set_allocated_subpage_path(std::string* subpage_path) {
  if (subpage_path != nullptr) {
    
  } else {
    
  }
  subpage_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), subpage_path,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (subpage_path_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    subpage_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:plugin_vm_service.ShowSettingsPageRequest.subpage_path)
}

// -------------------------------------------------------------------

// GetPermissionsResponse

// bool data_collection_enabled = 1;
inline void GetPermissionsResponse::clear_data_collection_enabled() {
  data_collection_enabled_ = false;
}
inline bool GetPermissionsResponse::_internal_data_collection_enabled() const {
  return data_collection_enabled_;
}
inline bool GetPermissionsResponse::data_collection_enabled() const {
  // @@protoc_insertion_point(field_get:plugin_vm_service.GetPermissionsResponse.data_collection_enabled)
  return _internal_data_collection_enabled();
}
inline void GetPermissionsResponse::_internal_set_data_collection_enabled(bool value) {
  
  data_collection_enabled_ = value;
}
inline void GetPermissionsResponse::set_data_collection_enabled(bool value) {
  _internal_set_data_collection_enabled(value);
  // @@protoc_insertion_point(field_set:plugin_vm_service.GetPermissionsResponse.data_collection_enabled)
}

// -------------------------------------------------------------------

// GetAppLicenseUserIdResponse

// string user_id = 1;
inline void GetAppLicenseUserIdResponse::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& GetAppLicenseUserIdResponse::user_id() const {
  // @@protoc_insertion_point(field_get:plugin_vm_service.GetAppLicenseUserIdResponse.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAppLicenseUserIdResponse::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:plugin_vm_service.GetAppLicenseUserIdResponse.user_id)
}
inline std::string* GetAppLicenseUserIdResponse::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:plugin_vm_service.GetAppLicenseUserIdResponse.user_id)
  return _s;
}
inline const std::string& GetAppLicenseUserIdResponse::_internal_user_id() const {
  return user_id_.Get();
}
inline void GetAppLicenseUserIdResponse::_internal_set_user_id(const std::string& value) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* GetAppLicenseUserIdResponse::_internal_mutable_user_id() {
  
  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* GetAppLicenseUserIdResponse::release_user_id() {
  // @@protoc_insertion_point(field_release:plugin_vm_service.GetAppLicenseUserIdResponse.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void GetAppLicenseUserIdResponse::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:plugin_vm_service.GetAppLicenseUserIdResponse.user_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace plugin_vm_service

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_plugin_5fvm_5fservice_2eproto
